export default [{
  "id": 0,
  "name": "Top Nations",
  "cname": "9强",
  "children": [{
    "id": "54",
    "name": "Brasil",
    "cname": "巴西"
  }, {
    "id": "18",
    "name": "France",
    "cname": "法国"
  }, {
    "id": "27",
    "name": "Italy",
    "cname": "意大利"
  }, {
    "id": "14",
    "name": "England",
    "cname": "英格兰"
  }, {
    "id": "34",
    "name": "Netherlands",
    "cname": "荷兰"
  }, {
    "id": "45",
    "name": "Spain",
    "cname": "西班牙"
  }, {
    "id": "21",
    "name": "Germany",
    "cname": "德国"
  }, {
    "id": "38",
    "name": "Portugal",
    "cname": "葡萄牙"
  }, {
    "id": "52",
    "name": "Argentina",
    "cname": "阿根廷"
  }]
}, {
  "id": 0,
  "name": "Europe",
  "cname": "欧洲",
  "children": [{
    "id": "1",
    "name": "Albania",
    "cname": "阿尔巴尼亚"
  }, {
    "id": "3",
    "name": "Armenia",
    "cname": "亚美尼亚"
  }, {
    "id": "4",
    "name": "Austria",
    "cname": "奥地利"
  }, {
    "id": "5",
    "name": "Azerbaijan",
    "cname": "阿塞拜疆"
  }, {
    "id": "6",
    "name": "Belarus",
    "cname": "白俄罗斯"
  }, {
    "id": "7",
    "name": "Belgium",
    "cname": "比利时"
  }, {
    "id": "8",
    "name": "Bosnia Herzegovina",
    "cname": "波斯尼亚和黑塞哥维那"
  }, {
    "id": "9",
    "name": "Bulgaria",
    "cname": "保加利亚"
  }, {
    "id": "10",
    "name": "Croatia",
    "cname": "克罗地亚"
  }, {
    "id": "11",
    "name": "Cyprus",
    "cname": "塞浦路斯"
  }, {
    "id": "12",
    "name": "Czech Republic",
    "cname": "捷克共和国"
  }, {
    "id": "13",
    "name": "Denmark",
    "cname": "丹麦"
  }, {
    "id": "14",
    "name": "England",
    "cname": "英格兰"
  }, {
    "id": "15",
    "name": "Montenegro",
    "cname": "黑山"
  }, {
    "id": "16",
    "name": "Faroe Islands",
    "cname": "法罗群岛"
  }, {
    "id": "17",
    "name": "Finland",
    "cname": "芬兰"
  }, {
    "id": "18",
    "name": "France",
    "cname": "法国"
  }, {
    "id": "19",
    "name": "FYR Macedonia",
    "cname": "马其顿"
  }, {
    "id": "20",
    "name": "Georgia",
    "cname": "格鲁吉亚"
  }, {
    "id": "21",
    "name": "Germany",
    "cname": "德国"
  }, {
    "id": "22",
    "name": "Greece",
    "cname": "希腊"
  }, {
    "id": "23",
    "name": "Hungary",
    "cname": "匈牙利"
  }, {
    "id": "24",
    "name": "Iceland",
    "cname": "冰岛"
  }, {
    "id": "25",
    "name": "Republic of Ireland",
    "cname": "爱尔兰共和国"
  }, {
    "id": "26",
    "name": "Israel",
    "cname": "以色列"
  }, {
    "id": "27",
    "name": "Italy",
    "cname": "意大利"
  }, {
    "id": "28",
    "name": "Latvia",
    "cname": "拉脱维亚"
  }, {
    "id": "29",
    "name": "Liechtenstein",
    "cname": "列支敦士登"
  }, {
    "id": "30",
    "name": "Lithuania",
    "cname": "立陶宛"
  }, {
    "id": "31",
    "name": "Luxembourg",
    "cname": "卢森堡"
  }, {
    "id": "32",
    "name": "Malta",
    "cname": "马耳他"
  }, {
    "id": "33",
    "name": "Moldova",
    "cname": "摩尔多瓦"
  }, {
    "id": "34",
    "name": "Netherlands",
    "cname": "荷兰"
  }, {
    "id": "35",
    "name": "Northern Ireland",
    "cname": "北爱尔兰"
  }, {
    "id": "36",
    "name": "Norway",
    "cname": "挪威"
  }, {
    "id": "37",
    "name": "Poland",
    "cname": "波兰"
  }, {
    "id": "38",
    "name": "Portugal",
    "cname": "葡萄牙"
  }, {
    "id": "39",
    "name": "Romania",
    "cname": "罗马尼亚"
  }, {
    "id": "40",
    "name": "Russia",
    "cname": "俄罗斯"
  }, {
    "id": "41",
    "name": "San Marino",
    "cname": "圣马力诺"
  }, {
    "id": "42",
    "name": "Scotland",
    "cname": "苏格兰"
  }, {
    "id": "43",
    "name": "Slovakia",
    "cname": "斯洛伐克"
  }, {
    "id": "44",
    "name": "Slovenia",
    "cname": "斯洛文尼亚"
  }, {
    "id": "45",
    "name": "Spain",
    "cname": "西班牙"
  }, {
    "id": "46",
    "name": "Sweden",
    "cname": "瑞典"
  }, {
    "id": "47",
    "name": "Switzerland",
    "cname": "瑞士"
  }, {
    "id": "48",
    "name": "Turkey",
    "cname": "土耳其"
  }, {
    "id": "49",
    "name": "Ukraine",
    "cname": "乌克兰"
  }, {
    "id": "50",
    "name": "Wales",
    "cname": "威尔士"
  }, {
    "id": "51",
    "name": "Serbia",
    "cname": "塞尔维亚"
  }, {
    "id": "205",
    "name": "Gibraltar",
    "cname": "直布罗陀"
  }, {
    "id": "208",
    "name": "Estonia",
    "cname": "爱沙尼亚"
  }, {
    "id": "219",
    "name": "Kosovo",
    "cname": "科索沃"
  }]
}, {
  "id": 1,
  "name": "South America",
  "cname": "南美洲",
  "children": [{
    "id": "52",
    "name": "Argentina",
    "cname": "阿根廷"
  }, {
    "id": "53",
    "name": "Bolivia",
    "cname": "玻利维亚"
  }, {
    "id": "54",
    "name": "Brazil",
    "cname": "巴西"
  }, {
    "id": "55",
    "name": "Chile",
    "cname": "智利"
  }, {
    "id": "56",
    "name": "Colombia",
    "cname": "哥伦比亚"
  }, {
    "id": "57",
    "name": "Ecuador",
    "cname": "厄瓜多尔"
  }, {
    "id": "58",
    "name": "Paraguay",
    "cname": "巴拉圭"
  }, {
    "id": "59",
    "name": "Peru",
    "cname": "秘鲁"
  }, {
    "id": "60",
    "name": "Uruguay",
    "cname": "乌拉圭"
  }, {
    "id": "61",
    "name": "Venezuela",
    "cname": "委内瑞拉"
  }]
}, {
  "id": 2,
  "name": "North America",
  "cname": "北美洲",
  "children": [{
    "id": "63",
    "name": "Antigua & Barbuda",
    "cname": "安提瓜和巴布达"
  }, {
    "id": "66",
    "name": "Barbados",
    "cname": "巴巴多斯"
  }, {
    "id": "68",
    "name": "Bermuda",
    "cname": "百慕大"
  }, {
    "id": "70",
    "name": "Canada",
    "cname": "加拿大"
  }, {
    "id": "72",
    "name": "Costa Rica",
    "cname": "哥斯达黎加"
  }, {
    "id": "73",
    "name": "Cuba",
    "cname": "古巴"
  }, {
    "id": "76",
    "name": "El Salvador",
    "cname": "萨尔瓦多"
  }, {
    "id": "77",
    "name": "Grenada",
    "cname": "格林纳达"
  }, {
    "id": "78",
    "name": "Guatemala",
    "cname": "危地马拉"
  }, {
    "id": "79",
    "name": "Guyana",
    "cname": "圭亚那"
  }, {
    "id": "80",
    "name": "Haiti",
    "cname": "海地"
  }, {
    "id": "81",
    "name": "Honduras",
    "cname": "洪都拉斯"
  }, {
    "id": "82",
    "name": "Jamaica",
    "cname": "牙买加"
  }, {
    "id": "83",
    "name": "Mexico",
    "cname": "墨西哥"
  }, {
    "id": "84",
    "name": "Montserrat",
    "cname": "蒙特塞拉特"
  }, {
    "id": "85",
    "name": "Curacao",
    "cname": "库拉索"
  }, {
    "id": "87",
    "name": "Panama",
    "cname": "巴拿马"
  }, {
    "id": "89",
    "name": "St Kitts Nevis",
    "cname": "圣基茨和尼维斯"
  }, {
    "id": "90",
    "name": "St Lucia",
    "cname": "圣卢西亚"
  }, {
    "id": "92",
    "name": "Suriname",
    "cname": "苏里南"
  }, {
    "id": "93",
    "name": "Trinidad & Tobago",
    "cname": "特立尼达和多巴哥"
  }, {
    "id": "95",
    "name": "United States",
    "cname": "美国"
  }, {
    "id": "207",
    "name": "Dominican Republic",
    "cname": "多米尼加共和国"
  }]
}, {
  "id": 3,
  "name": "Africa",
  "cname": "非洲",
  "children": [{
    "id": "97",
    "name": "Algeria",
    "cname": "阿尔及利亚"
  }, {
    "id": "98",
    "name": "Angola",
    "cname": "安哥拉"
  }, {
    "id": "99",
    "name": "Benin",
    "cname": "贝宁"
  }, {
    "id": "101",
    "name": "Burkina Faso",
    "cname": "布基纳法索"
  }, {
    "id": "102",
    "name": "Burundi",
    "cname": "布隆迪"
  }, {
    "id": "103",
    "name": "Cameroon",
    "cname": "喀麦隆"
  }, {
    "id": "104",
    "name": "Cape Verde",
    "cname": "佛得角"
  }, {
    "id": "105",
    "name": "Central African Rep.",
    "cname": "中非共和国"
  }, {
    "id": "106",
    "name": "Chad",
    "cname": "乍得"
  }, {
    "id": "107",
    "name": "Congo",
    "cname": "刚果"
  }, {
    "id": "108",
    "name": "Côte d’Ivoire",
    "cname": "科特迪瓦"
  }, {
    "id": "110",
    "name": "DR Congo",
    "cname": "民主刚果"
  }, {
    "id": "111",
    "name": "Egypt",
    "cname": "埃及"
  }, {
    "id": "112",
    "name": "Equatorial Guinea",
    "cname": "赤道几内亚"
  }, {
    "id": "113",
    "name": "Eritrea",
    "cname": "厄立特里亚"
  }, {
    "id": "114",
    "name": "Ethiopia",
    "cname": "埃塞俄比亚"
  }, {
    "id": "115",
    "name": "Gabon",
    "cname": "加蓬"
  }, {
    "id": "116",
    "name": "Gambia",
    "cname": "冈比亚"
  }, {
    "id": "117",
    "name": "Ghana",
    "cname": "加纳"
  }, {
    "id": "118",
    "name": "Guinea",
    "cname": "几内亚"
  }, {
    "id": "119",
    "name": "Guinea Bissau",
    "cname": "几内亚比绍"
  }, {
    "id": "120",
    "name": "Kenya",
    "cname": "肯尼亚"
  }, {
    "id": "122",
    "name": "Liberia",
    "cname": "利比里亚"
  }, {
    "id": "123",
    "name": "Libya",
    "cname": "利比亚"
  }, {
    "id": "124",
    "name": "Madagascar",
    "cname": "马达加斯加"
  }, {
    "id": "126",
    "name": "Mali",
    "cname": "马里"
  }, {
    "id": "127",
    "name": "Mauritania",
    "cname": "毛里塔尼亚"
  }, {
    "id": "128",
    "name": "Mauritius",
    "cname": "毛里求斯"
  }, {
    "id": "129",
    "name": "Morocco",
    "cname": "摩洛哥"
  }, {
    "id": "130",
    "name": "Mozambique",
    "cname": "莫桑比克"
  }, {
    "id": "131",
    "name": "Namibia",
    "cname": "纳米比亚"
  }, {
    "id": "132",
    "name": "Niger",
    "cname": "尼日尔"
  }, {
    "id": "133",
    "name": "Nigeria",
    "cname": "尼日利亚"
  }, {
    "id": "135",
    "name": "São Tomé & Príncipe",
    "cname": "圣多美和普林西比"
  }, {
    "id": "136",
    "name": "Senegal",
    "cname": "塞内加尔"
  }, {
    "id": "138",
    "name": "Sierra Leone",
    "cname": "塞拉利昂"
  }, {
    "id": "139",
    "name": "Somalia",
    "cname": "索马里"
  }, {
    "id": "140",
    "name": "South Africa",
    "cname": "南非"
  }, {
    "id": "141",
    "name": "Sudan",
    "cname": "苏丹"
  }, {
    "id": "143",
    "name": "Tanzania",
    "cname": "坦桑尼亚"
  }, {
    "id": "144",
    "name": "Togo",
    "cname": "多哥"
  }, {
    "id": "145",
    "name": "Tunisia",
    "cname": "突尼斯"
  }, {
    "id": "146",
    "name": "Uganda",
    "cname": "乌干达"
  }, {
    "id": "147",
    "name": "Zambia",
    "cname": "赞比亚"
  }, {
    "id": "148",
    "name": "Zimbabwe",
    "cname": "津巴布韦"
  }]
}, {
  "id": 4,
  "name": "Asia",
  "cname": "亚洲",
  "children": [{
    "id": "149",
    "name": "Afghanistan",
    "cname": "阿富汗"
  }, {
    "id": "153",
    "name": "Brunei Darussalam",
    "cname": "文莱"
  }, {
    "id": "155",
    "name": "China PR",
    "cname": "中国"
  }, {
    "id": "157",
    "name": "Guam",
    "cname": "关岛"
  }, {
    "id": "158",
    "name": "Hong Kong",
    "cname": "中国香港"
  }, {
    "id": "159",
    "name": "India",
    "cname": "印度"
  }, {
    "id": "161",
    "name": "Iran",
    "cname": "伊朗"
  }, {
    "id": "162",
    "name": "Iraq",
    "cname": "伊拉克"
  }, {
    "id": "163",
    "name": "Japan",
    "cname": "日本"
  }, {
    "id": "165",
    "name": "Kazakhstan",
    "cname": "哈萨克斯坦"
  }, {
    "id": "166",
    "name": "Korea DPR",
    "cname": "韩国"
  }, {
    "id": "167",
    "name": "Korea Republic",
    "cname": "朝鲜"
  }, {
    "id": "168",
    "name": "Kuwait",
    "cname": "科威特"
  }, {
    "id": "169",
    "name": "Kyrgyzstan",
    "cname": "吉尔吉斯斯坦"
  }, {
    "id": "171",
    "name": "Lebanon",
    "cname": "黎巴嫩"
  }, {
    "id": "178",
    "name": "Oman",
    "cname": "阿曼"
  }, {
    "id": "180",
    "name": "Palestine",
    "cname": "巴勒斯坦"
  }, {
    "id": "181",
    "name": "Philippines",
    "cname": "菲律宾"
  }, {
    "id": "183",
    "name": "Saudi Arabia",
    "cname": "沙特阿拉伯"
  }, {
    "id": "185",
    "name": "Sri Lanka",
    "cname": "斯里兰卡"
  }, {
    "id": "186",
    "name": "Syria",
    "cname": "叙利亚"
  }, {
    "id": "188",
    "name": "Thailand",
    "cname": "泰国"
  }, {
    "id": "189",
    "name": "Turkmenistan",
    "cname": "土库曼斯坦"
  }, {
    "id": "191",
    "name": "Uzbekistan",
    "cname": "乌兹别克斯坦"
  }, {
    "id": "213",
    "name": "Chinese Taipei",
    "cname": "中华台北"
  }, {
    "id": "214",
    "name": "Comoros",
    "cname": "科摩罗"
  }, {
    "id": "218",
    "name": "South Sudan",
    "cname": "南苏丹"
  }]
}, {
  "id": 5,
  "name": "Oceania",
  "cname": "大洋洲",
  "children": [{
    "id": "195",
    "name": "Australia",
    "cname": "澳大利亚"
  }, {
    "id": "197",
    "name": "Fiji",
    "cname": "斐济"
  }, {
    "id": "198",
    "name": "New Zealand",
    "cname": "新西兰"
  }, {
    "id": "215",
    "name": "New Caledonia",
    "cname": "新喀里多尼亚"
  }]
}]
