export default [{
  "Acceleration": 1,
  "Sprint Speed": 0,
  "Finishing": 1,
  "Long Shot": 1,
  "Shot Power": 0,
  "Positioning": 1,
  "Crossing": 0,
  "Short Passing": 1,
  "Long Passing": 0,
  "Free Kick": 1,
  "Awareness": 0,
  "Reactions": 1,
  "Ball Control": 0,
  "Dribbling": 1,
  "Composure": 0,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 0,
  "Strength": 0,
  "Aggression": 0
}, {
  "Acceleration": 2,
  "Sprint Speed": 1,
  "Finishing": 2,
  "Long Shot": 2,
  "Shot Power": 0,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 2,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 1,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 0,
  "Strength": 0,
  "Aggression": 1
}, {
  "Acceleration": 3,
  "Sprint Speed": 2,
  "Finishing": 3,
  "Long Shot": 2,
  "Shot Power": 0,
  "Positioning": 2,
  "Crossing": 1,
  "Short Passing": 2,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 3,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 2,
  "Heading": 1,
  "Marking": 2,
  "Tackling": 1,
  "Strength": 0,
  "Aggression": 1
}, {
  "Acceleration": 3,
  "Sprint Speed": 2,
  "Finishing": 3,
  "Long Shot": 3,
  "Shot Power": 0,
  "Positioning": 3,
  "Crossing": 2,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 3,
  "Ball Control": 2,
  "Dribbling": 2,
  "Composure": 3,
  "Heading": 2,
  "Marking": 3,
  "Tackling": 1,
  "Strength": 0,
  "Aggression": 2
}, {
  "Acceleration": 4,
  "Sprint Speed": 2,
  "Finishing": 4,
  "Long Shot": 3,
  "Shot Power": 1,
  "Positioning": 3,
  "Crossing": 2,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 4,
  "Ball Control": 3,
  "Dribbling": 2,
  "Composure": 3,
  "Heading": 2,
  "Marking": 3,
  "Tackling": 2,
  "Strength": 1,
  "Aggression": 3
}, {
  "Acceleration": 4,
  "Sprint Speed": 2,
  "Finishing": 5,
  "Long Shot": 3,
  "Shot Power": 1,
  "Positioning": 4,
  "Crossing": 3,
  "Short Passing": 3,
  "Long Passing": 3,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 4,
  "Ball Control": 3,
  "Dribbling": 3,
  "Composure": 4,
  "Heading": 3,
  "Marking": 3,
  "Tackling": 3,
  "Strength": 1,
  "Aggression": 3
}, {
  "Acceleration": 5,
  "Sprint Speed": 3,
  "Finishing": 6,
  "Long Shot": 3,
  "Shot Power": 1,
  "Positioning": 4,
  "Crossing": 3,
  "Short Passing": 3,
  "Long Passing": 4,
  "Free Kick": 1,
  "Awareness": 3,
  "Reactions": 5,
  "Ball Control": 4,
  "Dribbling": 3,
  "Composure": 4,
  "Heading": 3,
  "Marking": 4,
  "Tackling": 3,
  "Strength": 2,
  "Aggression": 4
}, {
  "Acceleration": 6,
  "Sprint Speed": 3,
  "Finishing": 7,
  "Long Shot": 4,
  "Shot Power": 1,
  "Positioning": 5,
  "Crossing": 4,
  "Short Passing": 3,
  "Long Passing": 4,
  "Free Kick": 1,
  "Awareness": 4,
  "Reactions": 6,
  "Ball Control": 5,
  "Dribbling": 3,
  "Composure": 5,
  "Heading": 3,
  "Marking": 4,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 4
}, {
  "Acceleration": 6,
  "Sprint Speed": 4,
  "Finishing": 7,
  "Long Shot": 4,
  "Shot Power": 2,
  "Positioning": 5,
  "Crossing": 4,
  "Short Passing": 4,
  "Long Passing": 5,
  "Free Kick": 2,
  "Awareness": 4,
  "Reactions": 6,
  "Ball Control": 6,
  "Dribbling": 4,
  "Composure": 5,
  "Heading": 3,
  "Marking": 5,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 5
}, {
  "Acceleration": 7,
  "Sprint Speed": 5,
  "Finishing": 8,
  "Long Shot": 4,
  "Shot Power": 3,
  "Positioning": 5,
  "Crossing": 5,
  "Short Passing": 4,
  "Long Passing": 5,
  "Free Kick": 2,
  "Awareness": 5,
  "Reactions": 6,
  "Ball Control": 6,
  "Dribbling": 4,
  "Composure": 5,
  "Heading": 4,
  "Marking": 5,
  "Tackling": 5,
  "Strength": 3,
  "Aggression": 6
}, {
  "Acceleration": 7,
  "Sprint Speed": 5,
  "Finishing": 8,
  "Long Shot": 5,
  "Shot Power": 3,
  "Positioning": 6,
  "Crossing": 6,
  "Short Passing": 5,
  "Long Passing": 5,
  "Free Kick": 2,
  "Awareness": 5,
  "Reactions": 7,
  "Ball Control": 6,
  "Dribbling": 5,
  "Composure": 6,
  "Heading": 4,
  "Marking": 6,
  "Tackling": 6,
  "Strength": 4,
  "Aggression": 6
}, {
  "Acceleration": 7,
  "Sprint Speed": 6,
  "Finishing": 8,
  "Long Shot": 5,
  "Shot Power": 3,
  "Positioning": 7,
  "Crossing": 6,
  "Short Passing": 5,
  "Long Passing": 6,
  "Free Kick": 2,
  "Awareness": 6,
  "Reactions": 7,
  "Ball Control": 7,
  "Dribbling": 5,
  "Composure": 6,
  "Heading": 5,
  "Marking": 6,
  "Tackling": 7,
  "Strength": 5,
  "Aggression": 7
}, {
  "Acceleration": 8,
  "Sprint Speed": 6,
  "Finishing": 9,
  "Long Shot": 6,
  "Shot Power": 4,
  "Positioning": 7,
  "Crossing": 7,
  "Short Passing": 5,
  "Long Passing": 7,
  "Free Kick": 3,
  "Awareness": 6,
  "Reactions": 7,
  "Ball Control": 7,
  "Dribbling": 6,
  "Composure": 7,
  "Heading": 5,
  "Marking": 7,
  "Tackling": 7,
  "Strength": 5,
  "Aggression": 7
}, {
  "Acceleration": 8,
  "Sprint Speed": 7,
  "Finishing": 10,
  "Long Shot": 6,
  "Shot Power": 4,
  "Positioning": 8,
  "Crossing": 8,
  "Short Passing": 6,
  "Long Passing": 7,
  "Free Kick": 3,
  "Awareness": 7,
  "Reactions": 7,
  "Ball Control": 8,
  "Dribbling": 6,
  "Composure": 8,
  "Heading": 6,
  "Marking": 7,
  "Tackling": 7,
  "Strength": 5,
  "Aggression": 8
}, {
  "Acceleration": 11,
  "Sprint Speed": 10,
  "Finishing": 13,
  "Long Shot": 9,
  "Shot Power": 7,
  "Positioning": 11,
  "Crossing": 11,
  "Short Passing": 9,
  "Long Passing": 10,
  "Free Kick": 3,
  "Awareness": 10,
  "Reactions": 10,
  "Ball Control": 11,
  "Dribbling": 9,
  "Composure": 8,
  "Heading": 6,
  "Marking": 7,
  "Tackling": 7,
  "Strength": 5,
  "Aggression": 8
}, {
  "Acceleration": 11,
  "Sprint Speed": 11,
  "Finishing": 13,
  "Long Shot": 10,
  "Shot Power": 8,
  "Positioning": 11,
  "Crossing": 11,
  "Short Passing": 10,
  "Long Passing": 11,
  "Free Kick": 4,
  "Awareness": 10,
  "Reactions": 11,
  "Ball Control": 11,
  "Dribbling": 9,
  "Composure": 8,
  "Heading": 6,
  "Marking": 8,
  "Tackling": 8,
  "Strength": 6,
  "Aggression": 9
}, {
  "Acceleration": 12,
  "Sprint Speed": 12,
  "Finishing": 13,
  "Long Shot": 10,
  "Shot Power": 9,
  "Positioning": 12,
  "Crossing": 12,
  "Short Passing": 11,
  "Long Passing": 11,
  "Free Kick": 4,
  "Awareness": 10,
  "Reactions": 11,
  "Ball Control": 11,
  "Dribbling": 9,
  "Composure": 9,
  "Heading": 7,
  "Marking": 9,
  "Tackling": 8,
  "Strength": 6,
  "Aggression": 10
}, {
  "Acceleration": 12,
  "Sprint Speed": 12,
  "Finishing": 13,
  "Long Shot": 11,
  "Shot Power": 9,
  "Positioning": 12,
  "Crossing": 13,
  "Short Passing": 11,
  "Long Passing": 12,
  "Free Kick": 5,
  "Awareness": 11,
  "Reactions": 12,
  "Ball Control": 12,
  "Dribbling": 10,
  "Composure": 9,
  "Heading": 7,
  "Marking": 9,
  "Tackling": 9,
  "Strength": 7,
  "Aggression": 10
}, {
  "Acceleration": 13,
  "Sprint Speed": 13,
  "Finishing": 14,
  "Long Shot": 12,
  "Shot Power": 9,
  "Positioning": 12,
  "Crossing": 13,
  "Short Passing": 12,
  "Long Passing": 13,
  "Free Kick": 6,
  "Awareness": 11,
  "Reactions": 13,
  "Ball Control": 13,
  "Dribbling": 11,
  "Composure": 9,
  "Heading": 7,
  "Marking": 9,
  "Tackling": 9,
  "Strength": 7,
  "Aggression": 10
}, {
  "Acceleration": 13,
  "Sprint Speed": 14,
  "Finishing": 15,
  "Long Shot": 12,
  "Shot Power": 10,
  "Positioning": 13,
  "Crossing": 13,
  "Short Passing": 12,
  "Long Passing": 14,
  "Free Kick": 6,
  "Awareness": 12,
  "Reactions": 13,
  "Ball Control": 13,
  "Dribbling": 11,
  "Composure": 10,
  "Heading": 7,
  "Marking": 9,
  "Tackling": 10,
  "Strength": 8,
  "Aggression": 11
}, {
  "Acceleration": 14,
  "Sprint Speed": 15,
  "Finishing": 15,
  "Long Shot": 12,
  "Shot Power": 10,
  "Positioning": 13,
  "Crossing": 14,
  "Short Passing": 13,
  "Long Passing": 15,
  "Free Kick": 6,
  "Awareness": 13,
  "Reactions": 14,
  "Ball Control": 13,
  "Dribbling": 12,
  "Composure": 11,
  "Heading": 8,
  "Marking": 9,
  "Tackling": 10,
  "Strength": 8,
  "Aggression": 11
}, {
  "Acceleration": 15,
  "Sprint Speed": 16,
  "Finishing": 15,
  "Long Shot": 13,
  "Shot Power": 11,
  "Positioning": 14,
  "Crossing": 14,
  "Short Passing": 14,
  "Long Passing": 15,
  "Free Kick": 7,
  "Awareness": 13,
  "Reactions": 14,
  "Ball Control": 14,
  "Dribbling": 12,
  "Composure": 12,
  "Heading": 8,
  "Marking": 10,
  "Tackling": 10,
  "Strength": 9,
  "Aggression": 11
}, {
  "Acceleration": 15,
  "Sprint Speed": 16,
  "Finishing": 16,
  "Long Shot": 13,
  "Shot Power": 11,
  "Positioning": 15,
  "Crossing": 15,
  "Short Passing": 14,
  "Long Passing": 16,
  "Free Kick": 7,
  "Awareness": 13,
  "Reactions": 15,
  "Ball Control": 14,
  "Dribbling": 12,
  "Composure": 13,
  "Heading": 9,
  "Marking": 11,
  "Tackling": 11,
  "Strength": 9,
  "Aggression": 12
}, {
  "Acceleration": 16,
  "Sprint Speed": 17,
  "Finishing": 16,
  "Long Shot": 13,
  "Shot Power": 11,
  "Positioning": 15,
  "Crossing": 15,
  "Short Passing": 15,
  "Long Passing": 17,
  "Free Kick": 7,
  "Awareness": 14,
  "Reactions": 15,
  "Ball Control": 15,
  "Dribbling": 13,
  "Composure": 14,
  "Heading": 9,
  "Marking": 12,
  "Tackling": 11,
  "Strength": 10,
  "Aggression": 12
}, {
  "Acceleration": 19,
  "Sprint Speed": 20,
  "Finishing": 19,
  "Long Shot": 16,
  "Shot Power": 14,
  "Positioning": 18,
  "Crossing": 18,
  "Short Passing": 18,
  "Long Passing": 20,
  "Free Kick": 7,
  "Awareness": 17,
  "Reactions": 18,
  "Ball Control": 18,
  "Dribbling": 16,
  "Composure": 14,
  "Heading": 9,
  "Marking": 12,
  "Tackling": 11,
  "Strength": 10,
  "Aggression": 12
}, {
  "Acceleration": 20,
  "Sprint Speed": 20,
  "Finishing": 20,
  "Long Shot": 16,
  "Shot Power": 14,
  "Positioning": 18,
  "Crossing": 18,
  "Short Passing": 19,
  "Long Passing": 21,
  "Free Kick": 8,
  "Awareness": 17,
  "Reactions": 19,
  "Ball Control": 19,
  "Dribbling": 17,
  "Composure": 15,
  "Heading": 9,
  "Marking": 12,
  "Tackling": 12,
  "Strength": 11,
  "Aggression": 12
}, {
  "Acceleration": 20,
  "Sprint Speed": 21,
  "Finishing": 21,
  "Long Shot": 17,
  "Shot Power": 15,
  "Positioning": 19,
  "Crossing": 19,
  "Short Passing": 20,
  "Long Passing": 22,
  "Free Kick": 8,
  "Awareness": 17,
  "Reactions": 19,
  "Ball Control": 20,
  "Dribbling": 17,
  "Composure": 15,
  "Heading": 10,
  "Marking": 12,
  "Tackling": 12,
  "Strength": 11,
  "Aggression": 12
}, {
  "Acceleration": 21,
  "Sprint Speed": 22,
  "Finishing": 22,
  "Long Shot": 18,
  "Shot Power": 15,
  "Positioning": 19,
  "Crossing": 19,
  "Short Passing": 21,
  "Long Passing": 23,
  "Free Kick": 8,
  "Awareness": 18,
  "Reactions": 19,
  "Ball Control": 20,
  "Dribbling": 17,
  "Composure": 15,
  "Heading": 11,
  "Marking": 12,
  "Tackling": 12,
  "Strength": 11,
  "Aggression": 13
}, {
  "Acceleration": 22,
  "Sprint Speed": 22,
  "Finishing": 23,
  "Long Shot": 18,
  "Shot Power": 16,
  "Positioning": 20,
  "Crossing": 19,
  "Short Passing": 21,
  "Long Passing": 24,
  "Free Kick": 8,
  "Awareness": 18,
  "Reactions": 20,
  "Ball Control": 21,
  "Dribbling": 18,
  "Composure": 15,
  "Heading": 11,
  "Marking": 12,
  "Tackling": 13,
  "Strength": 12,
  "Aggression": 13
}, {
  "Acceleration": 22,
  "Sprint Speed": 23,
  "Finishing": 24,
  "Long Shot": 18,
  "Shot Power": 16,
  "Positioning": 21,
  "Crossing": 20,
  "Short Passing": 22,
  "Long Passing": 25,
  "Free Kick": 9,
  "Awareness": 19,
  "Reactions": 20,
  "Ball Control": 22,
  "Dribbling": 18,
  "Composure": 16,
  "Heading": 11,
  "Marking": 12,
  "Tackling": 13,
  "Strength": 12,
  "Aggression": 13
}, {
  "Acceleration": 23,
  "Sprint Speed": 23,
  "Finishing": 24,
  "Long Shot": 19,
  "Shot Power": 16,
  "Positioning": 21,
  "Crossing": 20,
  "Short Passing": 22,
  "Long Passing": 26,
  "Free Kick": 9,
  "Awareness": 19,
  "Reactions": 21,
  "Ball Control": 23,
  "Dribbling": 19,
  "Composure": 17,
  "Heading": 11,
  "Marking": 12,
  "Tackling": 14,
  "Strength": 12,
  "Aggression": 14
}, {
  "Acceleration": 24,
  "Sprint Speed": 24,
  "Finishing": 25,
  "Long Shot": 20,
  "Shot Power": 17,
  "Positioning": 22,
  "Crossing": 21,
  "Short Passing": 22,
  "Long Passing": 27,
  "Free Kick": 9,
  "Awareness": 20,
  "Reactions": 21,
  "Ball Control": 23,
  "Dribbling": 19,
  "Composure": 18,
  "Heading": 11,
  "Marking": 12,
  "Tackling": 14,
  "Strength": 13,
  "Aggression": 14
}, {
  "Acceleration": 24,
  "Sprint Speed": 24,
  "Finishing": 26,
  "Long Shot": 21,
  "Shot Power": 17,
  "Positioning": 23,
  "Crossing": 22,
  "Short Passing": 23,
  "Long Passing": 28,
  "Free Kick": 9,
  "Awareness": 20,
  "Reactions": 21,
  "Ball Control": 24,
  "Dribbling": 20,
  "Composure": 18,
  "Heading": 11,
  "Marking": 12,
  "Tackling": 14,
  "Strength": 13,
  "Aggression": 15
}, {
  "Acceleration": 24,
  "Sprint Speed": 25,
  "Finishing": 27,
  "Long Shot": 22,
  "Shot Power": 17,
  "Positioning": 23,
  "Crossing": 22,
  "Short Passing": 24,
  "Long Passing": 29,
  "Free Kick": 10,
  "Awareness": 21,
  "Reactions": 22,
  "Ball Control": 25,
  "Dribbling": 20,
  "Composure": 19,
  "Heading": 12,
  "Marking": 12,
  "Tackling": 14,
  "Strength": 13,
  "Aggression": 15
}, {
  "Acceleration": 27,
  "Sprint Speed": 28,
  "Finishing": 30,
  "Long Shot": 25,
  "Shot Power": 20,
  "Positioning": 26,
  "Crossing": 25,
  "Short Passing": 27,
  "Long Passing": 32,
  "Free Kick": 10,
  "Awareness": 24,
  "Reactions": 25,
  "Ball Control": 28,
  "Dribbling": 23,
  "Composure": 19,
  "Heading": 12,
  "Marking": 12,
  "Tackling": 14,
  "Strength": 13,
  "Aggression": 15
}, {
  "Acceleration": 27,
  "Sprint Speed": 28,
  "Finishing": 31,
  "Long Shot": 26,
  "Shot Power": 20,
  "Positioning": 27,
  "Crossing": 26,
  "Short Passing": 28,
  "Long Passing": 33,
  "Free Kick": 10,
  "Awareness": 25,
  "Reactions": 26,
  "Ball Control": 29,
  "Dribbling": 24,
  "Composure": 19,
  "Heading": 13,
  "Marking": 12,
  "Tackling": 14,
  "Strength": 13,
  "Aggression": 15
}, {
  "Acceleration": 28,
  "Sprint Speed": 29,
  "Finishing": 32,
  "Long Shot": 26,
  "Shot Power": 21,
  "Positioning": 28,
  "Crossing": 26,
  "Short Passing": 28,
  "Long Passing": 34,
  "Free Kick": 10,
  "Awareness": 26,
  "Reactions": 26,
  "Ball Control": 29,
  "Dribbling": 25,
  "Composure": 20,
  "Heading": 13,
  "Marking": 12,
  "Tackling": 14,
  "Strength": 13,
  "Aggression": 16
}, {
  "Acceleration": 28,
  "Sprint Speed": 30,
  "Finishing": 32,
  "Long Shot": 27,
  "Shot Power": 21,
  "Positioning": 28,
  "Crossing": 27,
  "Short Passing": 29,
  "Long Passing": 35,
  "Free Kick": 11,
  "Awareness": 26,
  "Reactions": 27,
  "Ball Control": 30,
  "Dribbling": 25,
  "Composure": 21,
  "Heading": 13,
  "Marking": 12,
  "Tackling": 14,
  "Strength": 14,
  "Aggression": 16
}, {
  "Acceleration": 29,
  "Sprint Speed": 31,
  "Finishing": 33,
  "Long Shot": 28,
  "Shot Power": 22,
  "Positioning": 29,
  "Crossing": 27,
  "Short Passing": 30,
  "Long Passing": 36,
  "Free Kick": 11,
  "Awareness": 26,
  "Reactions": 28,
  "Ball Control": 30,
  "Dribbling": 26,
  "Composure": 21,
  "Heading": 13,
  "Marking": 12,
  "Tackling": 15,
  "Strength": 14,
  "Aggression": 16
}, {
  "Acceleration": 29,
  "Sprint Speed": 31,
  "Finishing": 34,
  "Long Shot": 29,
  "Shot Power": 22,
  "Positioning": 29,
  "Crossing": 28,
  "Short Passing": 31,
  "Long Passing": 37,
  "Free Kick": 11,
  "Awareness": 27,
  "Reactions": 28,
  "Ball Control": 31,
  "Dribbling": 27,
  "Composure": 21,
  "Heading": 14,
  "Marking": 12,
  "Tackling": 15,
  "Strength": 15,
  "Aggression": 17
}, {
  "Acceleration": 30,
  "Sprint Speed": 32,
  "Finishing": 34,
  "Long Shot": 29,
  "Shot Power": 23,
  "Positioning": 30,
  "Crossing": 28,
  "Short Passing": 32,
  "Long Passing": 38,
  "Free Kick": 11,
  "Awareness": 27,
  "Reactions": 29,
  "Ball Control": 32,
  "Dribbling": 27,
  "Composure": 22,
  "Heading": 14,
  "Marking": 12,
  "Tackling": 16,
  "Strength": 15,
  "Aggression": 17
}, {
  "Acceleration": 30,
  "Sprint Speed": 33,
  "Finishing": 35,
  "Long Shot": 30,
  "Shot Power": 23,
  "Positioning": 30,
  "Crossing": 28,
  "Short Passing": 33,
  "Long Passing": 39,
  "Free Kick": 12,
  "Awareness": 28,
  "Reactions": 29,
  "Ball Control": 33,
  "Dribbling": 28,
  "Composure": 22,
  "Heading": 14,
  "Marking": 12,
  "Tackling": 17,
  "Strength": 15,
  "Aggression": 18
}, {
  "Acceleration": 31,
  "Sprint Speed": 34,
  "Finishing": 35,
  "Long Shot": 31,
  "Shot Power": 24,
  "Positioning": 32,
  "Crossing": 29,
  "Short Passing": 34,
  "Long Passing": 40,
  "Free Kick": 12,
  "Awareness": 29,
  "Reactions": 30,
  "Ball Control": 33,
  "Dribbling": 29,
  "Composure": 22,
  "Heading": 14,
  "Marking": 12,
  "Tackling": 17,
  "Strength": 15,
  "Aggression": 18
}, {
  "Acceleration": 32,
  "Sprint Speed": 35,
  "Finishing": 36,
  "Long Shot": 31,
  "Shot Power": 24,
  "Positioning": 32,
  "Crossing": 30,
  "Short Passing": 35,
  "Long Passing": 41,
  "Free Kick": 12,
  "Awareness": 29,
  "Reactions": 30,
  "Ball Control": 35,
  "Dribbling": 30,
  "Composure": 23,
  "Heading": 14,
  "Marking": 12,
  "Tackling": 17,
  "Strength": 16,
  "Aggression": 19
}, {
  "Acceleration": 34,
  "Sprint Speed": 38,
  "Finishing": 39,
  "Long Shot": 34,
  "Shot Power": 24,
  "Positioning": 35,
  "Crossing": 30,
  "Short Passing": 40,
  "Long Passing": 44,
  "Free Kick": 12,
  "Awareness": 39,
  "Reactions": 33,
  "Ball Control": 35,
  "Dribbling": 30,
  "Composure": 33,
  "Heading": 14,
  "Marking": 17,
  "Tackling": 17,
  "Strength": 16,
  "Aggression": 19
}, {
  "Acceleration": 37,
  "Sprint Speed": 38,
  "Finishing": 41,
  "Long Shot": 36,
  "Shot Power": 29,
  "Positioning": 37,
  "Crossing": 35,
  "Short Passing": 43,
  "Long Passing": 48,
  "Free Kick": 12,
  "Awareness": 39,
  "Reactions": 36,
  "Ball Control": 37,
  "Dribbling": 33,
  "Composure": 33,
  "Heading": 14,
  "Marking": 17,
  "Tackling": 17,
  "Strength": 20,
  "Aggression": 19
}, {
  "Acceleration": 40,
  "Sprint Speed": 40,
  "Finishing": 44,
  "Long Shot": 39,
  "Shot Power": 29,
  "Positioning": 40,
  "Crossing": 35,
  "Short Passing": 45,
  "Long Passing": 48,
  "Free Kick": 22,
  "Awareness": 39,
  "Reactions": 39,
  "Ball Control": 40,
  "Dribbling": 36,
  "Composure": 33,
  "Heading": 19,
  "Marking": 17,
  "Tackling": 17,
  "Strength": 20,
  "Aggression": 24
}, {
  "Acceleration": 44,
  "Sprint Speed": 43,
  "Finishing": 46,
  "Long Shot": 43,
  "Shot Power": 34,
  "Positioning": 40,
  "Crossing": 35,
  "Short Passing": 49,
  "Long Passing": 51,
  "Free Kick": 22,
  "Awareness": 39,
  "Reactions": 42,
  "Ball Control": 44,
  "Dribbling": 39,
  "Composure": 33,
  "Heading": 19,
  "Marking": 17,
  "Tackling": 22,
  "Strength": 20,
  "Aggression": 29
}, {
  "Acceleration": 47,
  "Sprint Speed": 47,
  "Finishing": 49,
  "Long Shot": 46,
  "Shot Power": 34,
  "Positioning": 44,
  "Crossing": 40,
  "Short Passing": 52,
  "Long Passing": 54,
  "Free Kick": 22,
  "Awareness": 44,
  "Reactions": 45,
  "Ball Control": 46,
  "Dribbling": 42,
  "Composure": 33,
  "Heading": 19,
  "Marking": 17,
  "Tackling": 22,
  "Strength": 20,
  "Aggression": 29
}, {
  "Acceleration": 49,
  "Sprint Speed": 50,
  "Finishing": 49,
  "Long Shot": 48,
  "Shot Power": 39,
  "Positioning": 47,
  "Crossing": 40,
  "Short Passing": 55,
  "Long Passing": 57,
  "Free Kick": 22,
  "Awareness": 51,
  "Reactions": 48,
  "Ball Control": 49,
  "Dribbling": 46,
  "Composure": 33,
  "Heading": 24,
  "Marking": 17,
  "Tackling": 22,
  "Strength": 23,
  "Aggression": 29
}, {
  "Acceleration": 52,
  "Sprint Speed": 53,
  "Finishing": 53,
  "Long Shot": 51,
  "Shot Power": 39,
  "Positioning": 50,
  "Crossing": 40,
  "Short Passing": 57,
  "Long Passing": 61,
  "Free Kick": 22,
  "Awareness": 55,
  "Reactions": 51,
  "Ball Control": 51,
  "Dribbling": 49,
  "Composure": 33,
  "Heading": 24,
  "Marking": 17,
  "Tackling": 22,
  "Strength": 27,
  "Aggression": 29
}, {
  "Acceleration": 54,
  "Sprint Speed": 57,
  "Finishing": 55,
  "Long Shot": 55,
  "Shot Power": 39,
  "Positioning": 55,
  "Crossing": 45,
  "Short Passing": 60,
  "Long Passing": 64,
  "Free Kick": 22,
  "Awareness": 55,
  "Reactions": 54,
  "Ball Control": 54,
  "Dribbling": 52,
  "Composure": 38,
  "Heading": 24,
  "Marking": 17,
  "Tackling": 22,
  "Strength": 27,
  "Aggression": 29
}, {
  "Acceleration": 57,
  "Sprint Speed": 60,
  "Finishing": 58,
  "Long Shot": 58,
  "Shot Power": 39,
  "Positioning": 57,
  "Crossing": 45,
  "Short Passing": 62,
  "Long Passing": 68,
  "Free Kick": 32,
  "Awareness": 60,
  "Reactions": 57,
  "Ball Control": 58,
  "Dribbling": 56,
  "Composure": 38,
  "Heading": 24,
  "Marking": 17,
  "Tackling": 22,
  "Strength": 27,
  "Aggression": 29
}, {
  "Acceleration": 57,
  "Sprint Speed": 63,
  "Finishing": 61,
  "Long Shot": 60,
  "Shot Power": 39,
  "Positioning": 61,
  "Crossing": 45,
  "Short Passing": 65,
  "Long Passing": 71,
  "Free Kick": 32,
  "Awareness": 63,
  "Reactions": 60,
  "Ball Control": 60,
  "Dribbling": 59,
  "Composure": 48,
  "Heading": 24,
  "Marking": 17,
  "Tackling": 22,
  "Strength": 30,
  "Aggression": 29
}, {
  "Acceleration": 61,
  "Sprint Speed": 66,
  "Finishing": 66,
  "Long Shot": 65,
  "Shot Power": 39,
  "Positioning": 64,
  "Crossing": 45,
  "Short Passing": 70,
  "Long Passing": 74,
  "Free Kick": 32,
  "Awareness": 73,
  "Reactions": 65,
  "Ball Control": 65,
  "Dribbling": 64,
  "Composure": 48,
  "Heading": 29,
  "Marking": 17,
  "Tackling": 22,
  "Strength": 30,
  "Aggression": 29
}]