export default [{
  "Acceleration": 0,
  "Sprint Speed": 0,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 0,
  "Positioning": 0,
  "Crossing": 1,
  "Short Passing": 0,
  "Long Passing": 0,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 0,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 0,
  "Heading": 0,
  "Marking": 0,
  "Tackling": 0,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 0,
  "Sprint Speed": 1,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 1,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 0,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 1,
  "Heading": 1,
  "Marking": 0,
  "Tackling": 0,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 1,
  "Long Shot": 0,
  "Shot Power": 1,
  "Positioning": 2,
  "Crossing": 1,
  "Short Passing": 0,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 2,
  "Ball Control": 1,
  "Dribbling": 2,
  "Composure": 2,
  "Heading": 1,
  "Marking": 0,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 1,
  "Long Shot": 1,
  "Shot Power": 1,
  "Positioning": 2,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 3,
  "Ball Control": 2,
  "Dribbling": 2,
  "Composure": 3,
  "Heading": 1,
  "Marking": 0,
  "Tackling": 1,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 1,
  "Sprint Speed": 2,
  "Finishing": 1,
  "Long Shot": 1,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 2,
  "Short Passing": 1,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 3,
  "Ball Control": 2,
  "Dribbling": 2,
  "Composure": 3,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 1,
  "Strength": 2,
  "Aggression": 3
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 1,
  "Shot Power": 2,
  "Positioning": 4,
  "Crossing": 2,
  "Short Passing": 1,
  "Long Passing": 3,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 3,
  "Ball Control": 2,
  "Dribbling": 2,
  "Composure": 4,
  "Heading": 2,
  "Marking": 1,
  "Tackling": 2,
  "Strength": 2,
  "Aggression": 3
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 2,
  "Shot Power": 2,
  "Positioning": 4,
  "Crossing": 3,
  "Short Passing": 2,
  "Long Passing": 3,
  "Free Kick": 1,
  "Awareness": 3,
  "Reactions": 4,
  "Ball Control": 3,
  "Dribbling": 3,
  "Composure": 4,
  "Heading": 2,
  "Marking": 1,
  "Tackling": 2,
  "Strength": 2,
  "Aggression": 4
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 3,
  "Long Shot": 2,
  "Shot Power": 2,
  "Positioning": 5,
  "Crossing": 3,
  "Short Passing": 2,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 3,
  "Reactions": 5,
  "Ball Control": 3,
  "Dribbling": 3,
  "Composure": 4,
  "Heading": 3,
  "Marking": 1,
  "Tackling": 2,
  "Strength": 3,
  "Aggression": 4
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 3,
  "Long Shot": 2,
  "Shot Power": 2,
  "Positioning": 5,
  "Crossing": 3,
  "Short Passing": 2,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 4,
  "Reactions": 6,
  "Ball Control": 4,
  "Dribbling": 3,
  "Composure": 5,
  "Heading": 4,
  "Marking": 1,
  "Tackling": 3,
  "Strength": 3,
  "Aggression": 5
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 4,
  "Long Shot": 2,
  "Shot Power": 3,
  "Positioning": 5,
  "Crossing": 4,
  "Short Passing": 3,
  "Long Passing": 4,
  "Free Kick": 2,
  "Awareness": 4,
  "Reactions": 6,
  "Ball Control": 4,
  "Dribbling": 4,
  "Composure": 5,
  "Heading": 4,
  "Marking": 2,
  "Tackling": 3,
  "Strength": 4,
  "Aggression": 6
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 4,
  "Long Shot": 3,
  "Shot Power": 3,
  "Positioning": 6,
  "Crossing": 4,
  "Short Passing": 3,
  "Long Passing": 4,
  "Free Kick": 3,
  "Awareness": 4,
  "Reactions": 7,
  "Ball Control": 4,
  "Dribbling": 4,
  "Composure": 5,
  "Heading": 5,
  "Marking": 3,
  "Tackling": 4,
  "Strength": 5,
  "Aggression": 7
}, {
  "Acceleration": 4,
  "Sprint Speed": 3,
  "Finishing": 4,
  "Long Shot": 3,
  "Shot Power": 3,
  "Positioning": 6,
  "Crossing": 4,
  "Short Passing": 4,
  "Long Passing": 4,
  "Free Kick": 4,
  "Awareness": 5,
  "Reactions": 8,
  "Ball Control": 5,
  "Dribbling": 5,
  "Composure": 6,
  "Heading": 5,
  "Marking": 3,
  "Tackling": 4,
  "Strength": 5,
  "Aggression": 7
}, {
  "Acceleration": 7,
  "Sprint Speed": 6,
  "Finishing": 4,
  "Long Shot": 6,
  "Shot Power": 6,
  "Positioning": 9,
  "Crossing": 5,
  "Short Passing": 7,
  "Long Passing": 7,
  "Free Kick": 4,
  "Awareness": 8,
  "Reactions": 11,
  "Ball Control": 8,
  "Dribbling": 5,
  "Composure": 6,
  "Heading": 8,
  "Marking": 6,
  "Tackling": 7,
  "Strength": 8,
  "Aggression": 10
}, {
  "Acceleration": 7,
  "Sprint Speed": 6,
  "Finishing": 4,
  "Long Shot": 7,
  "Shot Power": 7,
  "Positioning": 9,
  "Crossing": 6,
  "Short Passing": 7,
  "Long Passing": 7,
  "Free Kick": 5,
  "Awareness": 9,
  "Reactions": 12,
  "Ball Control": 9,
  "Dribbling": 5,
  "Composure": 7,
  "Heading": 9,
  "Marking": 6,
  "Tackling": 7,
  "Strength": 8,
  "Aggression": 11
}, {
  "Acceleration": 8,
  "Sprint Speed": 6,
  "Finishing": 5,
  "Long Shot": 8,
  "Shot Power": 7,
  "Positioning": 10,
  "Crossing": 6,
  "Short Passing": 7,
  "Long Passing": 7,
  "Free Kick": 5,
  "Awareness": 9,
  "Reactions": 12,
  "Ball Control": 9,
  "Dribbling": 6,
  "Composure": 8,
  "Heading": 9,
  "Marking": 6,
  "Tackling": 7,
  "Strength": 9,
  "Aggression": 12
}, {
  "Acceleration": 8,
  "Sprint Speed": 7,
  "Finishing": 6,
  "Long Shot": 8,
  "Shot Power": 7,
  "Positioning": 10,
  "Crossing": 7,
  "Short Passing": 8,
  "Long Passing": 8,
  "Free Kick": 5,
  "Awareness": 9,
  "Reactions": 13,
  "Ball Control": 9,
  "Dribbling": 6,
  "Composure": 8,
  "Heading": 10,
  "Marking": 7,
  "Tackling": 7,
  "Strength": 9,
  "Aggression": 12
}, {
  "Acceleration": 8,
  "Sprint Speed": 7,
  "Finishing": 7,
  "Long Shot": 9,
  "Shot Power": 7,
  "Positioning": 10,
  "Crossing": 7,
  "Short Passing": 8,
  "Long Passing": 8,
  "Free Kick": 5,
  "Awareness": 10,
  "Reactions": 13,
  "Ball Control": 10,
  "Dribbling": 7,
  "Composure": 8,
  "Heading": 11,
  "Marking": 7,
  "Tackling": 8,
  "Strength": 9,
  "Aggression": 13
}, {
  "Acceleration": 9,
  "Sprint Speed": 7,
  "Finishing": 7,
  "Long Shot": 9,
  "Shot Power": 8,
  "Positioning": 11,
  "Crossing": 8,
  "Short Passing": 8,
  "Long Passing": 9,
  "Free Kick": 6,
  "Awareness": 10,
  "Reactions": 13,
  "Ball Control": 10,
  "Dribbling": 7,
  "Composure": 9,
  "Heading": 12,
  "Marking": 7,
  "Tackling": 8,
  "Strength": 10,
  "Aggression": 13
}, {
  "Acceleration": 9,
  "Sprint Speed": 7,
  "Finishing": 7,
  "Long Shot": 9,
  "Shot Power": 8,
  "Positioning": 12,
  "Crossing": 9,
  "Short Passing": 9,
  "Long Passing": 10,
  "Free Kick": 6,
  "Awareness": 10,
  "Reactions": 14,
  "Ball Control": 10,
  "Dribbling": 8,
  "Composure": 9,
  "Heading": 13,
  "Marking": 8,
  "Tackling": 8,
  "Strength": 11,
  "Aggression": 14
}, {
  "Acceleration": 9,
  "Sprint Speed": 8,
  "Finishing": 7,
  "Long Shot": 10,
  "Shot Power": 8,
  "Positioning": 12,
  "Crossing": 9,
  "Short Passing": 9,
  "Long Passing": 10,
  "Free Kick": 6,
  "Awareness": 11,
  "Reactions": 15,
  "Ball Control": 11,
  "Dribbling": 8,
  "Composure": 10,
  "Heading": 13,
  "Marking": 8,
  "Tackling": 9,
  "Strength": 12,
  "Aggression": 14
}, {
  "Acceleration": 10,
  "Sprint Speed": 8,
  "Finishing": 8,
  "Long Shot": 10,
  "Shot Power": 8,
  "Positioning": 13,
  "Crossing": 9,
  "Short Passing": 9,
  "Long Passing": 11,
  "Free Kick": 6,
  "Awareness": 11,
  "Reactions": 15,
  "Ball Control": 11,
  "Dribbling": 8,
  "Composure": 11,
  "Heading": 14,
  "Marking": 9,
  "Tackling": 9,
  "Strength": 12,
  "Aggression": 15
}, {
  "Acceleration": 10,
  "Sprint Speed": 8,
  "Finishing": 8,
  "Long Shot": 10,
  "Shot Power": 8,
  "Positioning": 14,
  "Crossing": 10,
  "Short Passing": 10,
  "Long Passing": 12,
  "Free Kick": 6,
  "Awareness": 12,
  "Reactions": 15,
  "Ball Control": 11,
  "Dribbling": 9,
  "Composure": 11,
  "Heading": 15,
  "Marking": 9,
  "Tackling": 10,
  "Strength": 13,
  "Aggression": 16
}, {
  "Acceleration": 13,
  "Sprint Speed": 11,
  "Finishing": 8,
  "Long Shot": 13,
  "Shot Power": 11,
  "Positioning": 17,
  "Crossing": 11,
  "Short Passing": 13,
  "Long Passing": 15,
  "Free Kick": 6,
  "Awareness": 15,
  "Reactions": 18,
  "Ball Control": 14,
  "Dribbling": 9,
  "Composure": 11,
  "Heading": 18,
  "Marking": 12,
  "Tackling": 13,
  "Strength": 16,
  "Aggression": 19
}, {
  "Acceleration": 13,
  "Sprint Speed": 11,
  "Finishing": 8,
  "Long Shot": 14,
  "Shot Power": 11,
  "Positioning": 17,
  "Crossing": 11,
  "Short Passing": 13,
  "Long Passing": 15,
  "Free Kick": 6,
  "Awareness": 15,
  "Reactions": 19,
  "Ball Control": 14,
  "Dribbling": 9,
  "Composure": 12,
  "Heading": 19,
  "Marking": 13,
  "Tackling": 13,
  "Strength": 17,
  "Aggression": 20
}, {
  "Acceleration": 13,
  "Sprint Speed": 11,
  "Finishing": 9,
  "Long Shot": 14,
  "Shot Power": 12,
  "Positioning": 17,
  "Crossing": 11,
  "Short Passing": 14,
  "Long Passing": 16,
  "Free Kick": 7,
  "Awareness": 16,
  "Reactions": 19,
  "Ball Control": 15,
  "Dribbling": 10,
  "Composure": 12,
  "Heading": 19,
  "Marking": 13,
  "Tackling": 14,
  "Strength": 17,
  "Aggression": 21
}, {
  "Acceleration": 13,
  "Sprint Speed": 11,
  "Finishing": 9,
  "Long Shot": 15,
  "Shot Power": 12,
  "Positioning": 18,
  "Crossing": 12,
  "Short Passing": 14,
  "Long Passing": 17,
  "Free Kick": 7,
  "Awareness": 16,
  "Reactions": 20,
  "Ball Control": 15,
  "Dribbling": 10,
  "Composure": 13,
  "Heading": 20,
  "Marking": 14,
  "Tackling": 14,
  "Strength": 18,
  "Aggression": 22
}, {
  "Acceleration": 13,
  "Sprint Speed": 11,
  "Finishing": 9,
  "Long Shot": 15,
  "Shot Power": 12,
  "Positioning": 19,
  "Crossing": 12,
  "Short Passing": 15,
  "Long Passing": 17,
  "Free Kick": 7,
  "Awareness": 17,
  "Reactions": 21,
  "Ball Control": 15,
  "Dribbling": 11,
  "Composure": 13,
  "Heading": 20,
  "Marking": 14,
  "Tackling": 15,
  "Strength": 18,
  "Aggression": 23
}, {
  "Acceleration": 13,
  "Sprint Speed": 12,
  "Finishing": 10,
  "Long Shot": 16,
  "Shot Power": 12,
  "Positioning": 20,
  "Crossing": 12,
  "Short Passing": 15,
  "Long Passing": 17,
  "Free Kick": 8,
  "Awareness": 17,
  "Reactions": 21,
  "Ball Control": 16,
  "Dribbling": 11,
  "Composure": 14,
  "Heading": 21,
  "Marking": 15,
  "Tackling": 15,
  "Strength": 18,
  "Aggression": 23
}, {
  "Acceleration": 14,
  "Sprint Speed": 12,
  "Finishing": 10,
  "Long Shot": 16,
  "Shot Power": 13,
  "Positioning": 20,
  "Crossing": 13,
  "Short Passing": 15,
  "Long Passing": 18,
  "Free Kick": 8,
  "Awareness": 18,
  "Reactions": 22,
  "Ball Control": 16,
  "Dribbling": 11,
  "Composure": 15,
  "Heading": 21,
  "Marking": 16,
  "Tackling": 15,
  "Strength": 18,
  "Aggression": 24
}, {
  "Acceleration": 15,
  "Sprint Speed": 12,
  "Finishing": 10,
  "Long Shot": 16,
  "Shot Power": 13,
  "Positioning": 21,
  "Crossing": 13,
  "Short Passing": 16,
  "Long Passing": 19,
  "Free Kick": 8,
  "Awareness": 18,
  "Reactions": 22,
  "Ball Control": 17,
  "Dribbling": 12,
  "Composure": 15,
  "Heading": 22,
  "Marking": 16,
  "Tackling": 16,
  "Strength": 18,
  "Aggression": 25
}, {
  "Acceleration": 16,
  "Sprint Speed": 12,
  "Finishing": 11,
  "Long Shot": 17,
  "Shot Power": 13,
  "Positioning": 21,
  "Crossing": 13,
  "Short Passing": 16,
  "Long Passing": 19,
  "Free Kick": 9,
  "Awareness": 19,
  "Reactions": 23,
  "Ball Control": 17,
  "Dribbling": 12,
  "Composure": 15,
  "Heading": 22,
  "Marking": 16,
  "Tackling": 16,
  "Strength": 19,
  "Aggression": 26
}, {
  "Acceleration": 17,
  "Sprint Speed": 13,
  "Finishing": 11,
  "Long Shot": 17,
  "Shot Power": 14,
  "Positioning": 22,
  "Crossing": 13,
  "Short Passing": 17,
  "Long Passing": 20,
  "Free Kick": 9,
  "Awareness": 19,
  "Reactions": 23,
  "Ball Control": 17,
  "Dribbling": 13,
  "Composure": 16,
  "Heading": 23,
  "Marking": 17,
  "Tackling": 16,
  "Strength": 19,
  "Aggression": 26
}, {
  "Acceleration": 20,
  "Sprint Speed": 16,
  "Finishing": 11,
  "Long Shot": 20,
  "Shot Power": 17,
  "Positioning": 25,
  "Crossing": 14,
  "Short Passing": 20,
  "Long Passing": 23,
  "Free Kick": 9,
  "Awareness": 22,
  "Reactions": 26,
  "Ball Control": 20,
  "Dribbling": 13,
  "Composure": 16,
  "Heading": 26,
  "Marking": 20,
  "Tackling": 19,
  "Strength": 22,
  "Aggression": 29
}, {
  "Acceleration": 21,
  "Sprint Speed": 17,
  "Finishing": 12,
  "Long Shot": 20,
  "Shot Power": 17,
  "Positioning": 26,
  "Crossing": 14,
  "Short Passing": 20,
  "Long Passing": 23,
  "Free Kick": 10,
  "Awareness": 23,
  "Reactions": 26,
  "Ball Control": 20,
  "Dribbling": 13,
  "Composure": 17,
  "Heading": 27,
  "Marking": 20,
  "Tackling": 20,
  "Strength": 22,
  "Aggression": 30
}, {
  "Acceleration": 22,
  "Sprint Speed": 18,
  "Finishing": 12,
  "Long Shot": 20,
  "Shot Power": 18,
  "Positioning": 27,
  "Crossing": 14,
  "Short Passing": 21,
  "Long Passing": 24,
  "Free Kick": 10,
  "Awareness": 23,
  "Reactions": 27,
  "Ball Control": 20,
  "Dribbling": 13,
  "Composure": 17,
  "Heading": 27,
  "Marking": 20,
  "Tackling": 21,
  "Strength": 23,
  "Aggression": 31
}, {
  "Acceleration": 23,
  "Sprint Speed": 19,
  "Finishing": 12,
  "Long Shot": 21,
  "Shot Power": 18,
  "Positioning": 27,
  "Crossing": 15,
  "Short Passing": 22,
  "Long Passing": 24,
  "Free Kick": 10,
  "Awareness": 23,
  "Reactions": 27,
  "Ball Control": 21,
  "Dribbling": 14,
  "Composure": 18,
  "Heading": 28,
  "Marking": 21,
  "Tackling": 22,
  "Strength": 23,
  "Aggression": 31
}, {
  "Acceleration": 24,
  "Sprint Speed": 20,
  "Finishing": 12,
  "Long Shot": 21,
  "Shot Power": 18,
  "Positioning": 28,
  "Crossing": 15,
  "Short Passing": 23,
  "Long Passing": 25,
  "Free Kick": 11,
  "Awareness": 23,
  "Reactions": 28,
  "Ball Control": 22,
  "Dribbling": 15,
  "Composure": 19,
  "Heading": 28,
  "Marking": 21,
  "Tackling": 23,
  "Strength": 23,
  "Aggression": 32
}, {
  "Acceleration": 25,
  "Sprint Speed": 21,
  "Finishing": 13,
  "Long Shot": 21,
  "Shot Power": 19,
  "Positioning": 29,
  "Crossing": 15,
  "Short Passing": 23,
  "Long Passing": 26,
  "Free Kick": 11,
  "Awareness": 23,
  "Reactions": 28,
  "Ball Control": 22,
  "Dribbling": 15,
  "Composure": 19,
  "Heading": 29,
  "Marking": 22,
  "Tackling": 24,
  "Strength": 24,
  "Aggression": 33
}, {
  "Acceleration": 26,
  "Sprint Speed": 22,
  "Finishing": 13,
  "Long Shot": 21,
  "Shot Power": 19,
  "Positioning": 29,
  "Crossing": 15,
  "Short Passing": 24,
  "Long Passing": 27,
  "Free Kick": 11,
  "Awareness": 24,
  "Reactions": 29,
  "Ball Control": 23,
  "Dribbling": 16,
  "Composure": 19,
  "Heading": 29,
  "Marking": 23,
  "Tackling": 24,
  "Strength": 24,
  "Aggression": 34
}, {
  "Acceleration": 27,
  "Sprint Speed": 23,
  "Finishing": 13,
  "Long Shot": 22,
  "Shot Power": 19,
  "Positioning": 30,
  "Crossing": 15,
  "Short Passing": 26,
  "Long Passing": 27,
  "Free Kick": 11,
  "Awareness": 25,
  "Reactions": 29,
  "Ball Control": 23,
  "Dribbling": 16,
  "Composure": 19,
  "Heading": 30,
  "Marking": 24,
  "Tackling": 25,
  "Strength": 25,
  "Aggression": 35
}, {
  "Acceleration": 28,
  "Sprint Speed": 24,
  "Finishing": 13,
  "Long Shot": 22,
  "Shot Power": 19,
  "Positioning": 30,
  "Crossing": 16,
  "Short Passing": 27,
  "Long Passing": 28,
  "Free Kick": 12,
  "Awareness": 25,
  "Reactions": 29,
  "Ball Control": 24,
  "Dribbling": 17,
  "Composure": 19,
  "Heading": 30,
  "Marking": 24,
  "Tackling": 26,
  "Strength": 25,
  "Aggression": 36
}, {
  "Acceleration": 29,
  "Sprint Speed": 25,
  "Finishing": 14,
  "Long Shot": 22,
  "Shot Power": 20,
  "Positioning": 33,
  "Crossing": 16,
  "Short Passing": 27,
  "Long Passing": 28,
  "Free Kick": 12,
  "Awareness": 26,
  "Reactions": 30,
  "Ball Control": 24,
  "Dribbling": 17,
  "Composure": 20,
  "Heading": 30,
  "Marking": 25,
  "Tackling": 28,
  "Strength": 25,
  "Aggression": 37
}, {
  "Acceleration": 29,
  "Sprint Speed": 27,
  "Finishing": 14,
  "Long Shot": 32,
  "Shot Power": 20,
  "Positioning": 38,
  "Crossing": 16,
  "Short Passing": 30,
  "Long Passing": 30,
  "Free Kick": 12,
  "Awareness": 29,
  "Reactions": 33,
  "Ball Control": 28,
  "Dribbling": 22,
  "Composure": 20,
  "Heading": 32,
  "Marking": 28,
  "Tackling": 31,
  "Strength": 27,
  "Aggression": 40
}, {
  "Acceleration": 33,
  "Sprint Speed": 30,
  "Finishing": 17,
  "Long Shot": 32,
  "Shot Power": 20,
  "Positioning": 38,
  "Crossing": 21,
  "Short Passing": 34,
  "Long Passing": 32,
  "Free Kick": 12,
  "Awareness": 29,
  "Reactions": 33,
  "Ball Control": 31,
  "Dribbling": 22,
  "Composure": 30,
  "Heading": 35,
  "Marking": 31,
  "Tackling": 34,
  "Strength": 30,
  "Aggression": 43
}, {
  "Acceleration": 36,
  "Sprint Speed": 34,
  "Finishing": 17,
  "Long Shot": 37,
  "Shot Power": 24,
  "Positioning": 43,
  "Crossing": 21,
  "Short Passing": 37,
  "Long Passing": 32,
  "Free Kick": 22,
  "Awareness": 34,
  "Reactions": 37,
  "Ball Control": 33,
  "Dribbling": 27,
  "Composure": 30,
  "Heading": 35,
  "Marking": 31,
  "Tackling": 37,
  "Strength": 32,
  "Aggression": 46
}, {
  "Acceleration": 39,
  "Sprint Speed": 34,
  "Finishing": 20,
  "Long Shot": 37,
  "Shot Power": 24,
  "Positioning": 43,
  "Crossing": 21,
  "Short Passing": 39,
  "Long Passing": 37,
  "Free Kick": 22,
  "Awareness": 37,
  "Reactions": 40,
  "Ball Control": 38,
  "Dribbling": 27,
  "Composure": 35,
  "Heading": 40,
  "Marking": 35,
  "Tackling": 41,
  "Strength": 35,
  "Aggression": 48
}, {
  "Acceleration": 42,
  "Sprint Speed": 37,
  "Finishing": 20,
  "Long Shot": 37,
  "Shot Power": 24,
  "Positioning": 48,
  "Crossing": 21,
  "Short Passing": 44,
  "Long Passing": 40,
  "Free Kick": 22,
  "Awareness": 41,
  "Reactions": 44,
  "Ball Control": 41,
  "Dribbling": 27,
  "Composure": 35,
  "Heading": 45,
  "Marking": 38,
  "Tackling": 44,
  "Strength": 38,
  "Aggression": 50
}, {
  "Acceleration": 45,
  "Sprint Speed": 41,
  "Finishing": 20,
  "Long Shot": 42,
  "Shot Power": 28,
  "Positioning": 48,
  "Crossing": 26,
  "Short Passing": 47,
  "Long Passing": 44,
  "Free Kick": 22,
  "Awareness": 41,
  "Reactions": 47,
  "Ball Control": 45,
  "Dribbling": 27,
  "Composure": 35,
  "Heading": 45,
  "Marking": 41,
  "Tackling": 47,
  "Strength": 40,
  "Aggression": 53
}, {
  "Acceleration": 48,
  "Sprint Speed": 46,
  "Finishing": 20,
  "Long Shot": 42,
  "Shot Power": 28,
  "Positioning": 53,
  "Crossing": 26,
  "Short Passing": 50,
  "Long Passing": 44,
  "Free Kick": 22,
  "Awareness": 45,
  "Reactions": 51,
  "Ball Control": 50,
  "Dribbling": 32,
  "Composure": 40,
  "Heading": 45,
  "Marking": 44,
  "Tackling": 50,
  "Strength": 45,
  "Aggression": 56
}, {
  "Acceleration": 51,
  "Sprint Speed": 51,
  "Finishing": 23,
  "Long Shot": 47,
  "Shot Power": 28,
  "Positioning": 53,
  "Crossing": 26,
  "Short Passing": 54,
  "Long Passing": 47,
  "Free Kick": 22,
  "Awareness": 48,
  "Reactions": 54,
  "Ball Control": 53,
  "Dribbling": 32,
  "Composure": 40,
  "Heading": 50,
  "Marking": 47,
  "Tackling": 53,
  "Strength": 45,
  "Aggression": 58
}, {
  "Acceleration": 54,
  "Sprint Speed": 51,
  "Finishing": 23,
  "Long Shot": 47,
  "Shot Power": 31,
  "Positioning": 58,
  "Crossing": 31,
  "Short Passing": 56,
  "Long Passing": 50,
  "Free Kick": 22,
  "Awareness": 50,
  "Reactions": 57,
  "Ball Control": 56,
  "Dribbling": 32,
  "Composure": 40,
  "Heading": 50,
  "Marking": 50,
  "Tackling": 57,
  "Strength": 50,
  "Aggression": 60
}, {
  "Acceleration": 57,
  "Sprint Speed": 54,
  "Finishing": 26,
  "Long Shot": 47,
  "Shot Power": 31,
  "Positioning": 58,
  "Crossing": 31,
  "Short Passing": 59,
  "Long Passing": 52,
  "Free Kick": 22,
  "Awareness": 53,
  "Reactions": 60,
  "Ball Control": 58,
  "Dribbling": 37,
  "Composure": 45,
  "Heading": 50,
  "Marking": 52,
  "Tackling": 60,
  "Strength": 50,
  "Aggression": 63
}, {
  "Acceleration": 57,
  "Sprint Speed": 54,
  "Finishing": 26,
  "Long Shot": 52,
  "Shot Power": 36,
  "Positioning": 63,
  "Crossing": 31,
  "Short Passing": 64,
  "Long Passing": 57,
  "Free Kick": 22,
  "Awareness": 56,
  "Reactions": 65,
  "Ball Control": 63,
  "Dribbling": 37,
  "Composure": 45,
  "Heading": 55,
  "Marking": 57,
  "Tackling": 65,
  "Strength": 55,
  "Aggression": 67
}]