export default [{
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 0,
  "Long Shot": 1,
  "Shot Power": 0,
  "Positioning": 0,
  "Crossing": 0,
  "Short Passing": 1,
  "Long Passing": 0,
  "Free Kick": 1,
  "Awareness": 0,
  "Reactions": 0,
  "Ball Control": 0,
  "Dribbling": 1,
  "Composure": 0,
  "Heading": 1,
  "Marking": 0,
  "Tackling": 0,
  "Strength": 1,
  "Aggression": 0
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 1,
  "Long Shot": 1,
  "Shot Power": 1,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 0,
  "Dribbling": 1,
  "Composure": 0,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 0
}, {
  "Acceleration": 2,
  "Sprint Speed": 1,
  "Finishing": 1,
  "Long Shot": 2,
  "Shot Power": 1,
  "Positioning": 2,
  "Crossing": 1,
  "Short Passing": 2,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 0,
  "Heading": 2,
  "Marking": 2,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 0
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 3,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 1,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 2,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 0,
  "Heading": 3,
  "Marking": 2,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 3,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 2,
  "Short Passing": 3,
  "Long Passing": 3,
  "Free Kick": 1,
  "Awareness": 3,
  "Reactions": 3,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 1,
  "Heading": 4,
  "Marking": 2,
  "Tackling": 2,
  "Strength": 2,
  "Aggression": 1
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 3,
  "Long Shot": 4,
  "Shot Power": 3,
  "Positioning": 3,
  "Crossing": 2,
  "Short Passing": 3,
  "Long Passing": 3,
  "Free Kick": 1,
  "Awareness": 4,
  "Reactions": 3,
  "Ball Control": 2,
  "Dribbling": 2,
  "Composure": 1,
  "Heading": 4,
  "Marking": 2,
  "Tackling": 2,
  "Strength": 2,
  "Aggression": 1
}, {
  "Acceleration": 3,
  "Sprint Speed": 4,
  "Finishing": 3,
  "Long Shot": 5,
  "Shot Power": 3,
  "Positioning": 4,
  "Crossing": 2,
  "Short Passing": 4,
  "Long Passing": 4,
  "Free Kick": 2,
  "Awareness": 4,
  "Reactions": 3,
  "Ball Control": 2,
  "Dribbling": 2,
  "Composure": 1,
  "Heading": 5,
  "Marking": 3,
  "Tackling": 3,
  "Strength": 2,
  "Aggression": 1
}, {
  "Acceleration": 3,
  "Sprint Speed": 4,
  "Finishing": 4,
  "Long Shot": 6,
  "Shot Power": 4,
  "Positioning": 4,
  "Crossing": 2,
  "Short Passing": 4,
  "Long Passing": 4,
  "Free Kick": 3,
  "Awareness": 5,
  "Reactions": 4,
  "Ball Control": 2,
  "Dribbling": 2,
  "Composure": 2,
  "Heading": 5,
  "Marking": 4,
  "Tackling": 3,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 4,
  "Sprint Speed": 5,
  "Finishing": 4,
  "Long Shot": 6,
  "Shot Power": 4,
  "Positioning": 5,
  "Crossing": 3,
  "Short Passing": 5,
  "Long Passing": 5,
  "Free Kick": 3,
  "Awareness": 5,
  "Reactions": 4,
  "Ball Control": 3,
  "Dribbling": 2,
  "Composure": 2,
  "Heading": 6,
  "Marking": 4,
  "Tackling": 3,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 4,
  "Sprint Speed": 5,
  "Finishing": 5,
  "Long Shot": 7,
  "Shot Power": 4,
  "Positioning": 5,
  "Crossing": 3,
  "Short Passing": 5,
  "Long Passing": 5,
  "Free Kick": 3,
  "Awareness": 6,
  "Reactions": 5,
  "Ball Control": 3,
  "Dribbling": 3,
  "Composure": 3,
  "Heading": 6,
  "Marking": 5,
  "Tackling": 4,
  "Strength": 3,
  "Aggression": 2
}, {
  "Acceleration": 5,
  "Sprint Speed": 6,
  "Finishing": 6,
  "Long Shot": 8,
  "Shot Power": 4,
  "Positioning": 6,
  "Crossing": 3,
  "Short Passing": 6,
  "Long Passing": 6,
  "Free Kick": 3,
  "Awareness": 6,
  "Reactions": 6,
  "Ball Control": 3,
  "Dribbling": 3,
  "Composure": 4,
  "Heading": 6,
  "Marking": 5,
  "Tackling": 4,
  "Strength": 3,
  "Aggression": 2
}, {
  "Acceleration": 5,
  "Sprint Speed": 6,
  "Finishing": 6,
  "Long Shot": 8,
  "Shot Power": 4,
  "Positioning": 7,
  "Crossing": 4,
  "Short Passing": 6,
  "Long Passing": 6,
  "Free Kick": 4,
  "Awareness": 7,
  "Reactions": 6,
  "Ball Control": 4,
  "Dribbling": 3,
  "Composure": 4,
  "Heading": 7,
  "Marking": 6,
  "Tackling": 5,
  "Strength": 3,
  "Aggression": 3
}, {
  "Acceleration": 5,
  "Sprint Speed": 7,
  "Finishing": 7,
  "Long Shot": 9,
  "Shot Power": 5,
  "Positioning": 8,
  "Crossing": 4,
  "Short Passing": 7,
  "Long Passing": 7,
  "Free Kick": 4,
  "Awareness": 7,
  "Reactions": 6,
  "Ball Control": 5,
  "Dribbling": 3,
  "Composure": 4,
  "Heading": 7,
  "Marking": 7,
  "Tackling": 5,
  "Strength": 3,
  "Aggression": 3
}, {
  "Acceleration": 6,
  "Sprint Speed": 8,
  "Finishing": 7,
  "Long Shot": 9,
  "Shot Power": 5,
  "Positioning": 8,
  "Crossing": 4,
  "Short Passing": 7,
  "Long Passing": 8,
  "Free Kick": 4,
  "Awareness": 8,
  "Reactions": 7,
  "Ball Control": 6,
  "Dribbling": 4,
  "Composure": 5,
  "Heading": 7,
  "Marking": 7,
  "Tackling": 5,
  "Strength": 4,
  "Aggression": 3
}, {
  "Acceleration": 6,
  "Sprint Speed": 8,
  "Finishing": 8,
  "Long Shot": 10,
  "Shot Power": 5,
  "Positioning": 9,
  "Crossing": 4,
  "Short Passing": 8,
  "Long Passing": 9,
  "Free Kick": 4,
  "Awareness": 8,
  "Reactions": 7,
  "Ball Control": 6,
  "Dribbling": 4,
  "Composure": 5,
  "Heading": 8,
  "Marking": 8,
  "Tackling": 6,
  "Strength": 4,
  "Aggression": 3
}, {
  "Acceleration": 9,
  "Sprint Speed": 11,
  "Finishing": 11,
  "Long Shot": 13,
  "Shot Power": 5,
  "Positioning": 12,
  "Crossing": 4,
  "Short Passing": 11,
  "Long Passing": 12,
  "Free Kick": 4,
  "Awareness": 11,
  "Reactions": 10,
  "Ball Control": 9,
  "Dribbling": 7,
  "Composure": 5,
  "Heading": 8,
  "Marking": 11,
  "Tackling": 9,
  "Strength": 4,
  "Aggression": 3
}, {
  "Acceleration": 10,
  "Sprint Speed": 12,
  "Finishing": 11,
  "Long Shot": 14,
  "Shot Power": 6,
  "Positioning": 13,
  "Crossing": 4,
  "Short Passing": 12,
  "Long Passing": 12,
  "Free Kick": 4,
  "Awareness": 11,
  "Reactions": 10,
  "Ball Control": 10,
  "Dribbling": 7,
  "Composure": 6,
  "Heading": 8,
  "Marking": 11,
  "Tackling": 10,
  "Strength": 4,
  "Aggression": 3
}, {
  "Acceleration": 10,
  "Sprint Speed": 12,
  "Finishing": 12,
  "Long Shot": 14,
  "Shot Power": 7,
  "Positioning": 13,
  "Crossing": 4,
  "Short Passing": 12,
  "Long Passing": 12,
  "Free Kick": 4,
  "Awareness": 12,
  "Reactions": 11,
  "Ball Control": 10,
  "Dribbling": 8,
  "Composure": 6,
  "Heading": 9,
  "Marking": 12,
  "Tackling": 11,
  "Strength": 4,
  "Aggression": 3
}, {
  "Acceleration": 10,
  "Sprint Speed": 13,
  "Finishing": 12,
  "Long Shot": 15,
  "Shot Power": 7,
  "Positioning": 14,
  "Crossing": 5,
  "Short Passing": 12,
  "Long Passing": 13,
  "Free Kick": 4,
  "Awareness": 12,
  "Reactions": 12,
  "Ball Control": 11,
  "Dribbling": 8,
  "Composure": 6,
  "Heading": 9,
  "Marking": 13,
  "Tackling": 11,
  "Strength": 4,
  "Aggression": 4
}, {
  "Acceleration": 11,
  "Sprint Speed": 13,
  "Finishing": 12,
  "Long Shot": 15,
  "Shot Power": 7,
  "Positioning": 15,
  "Crossing": 5,
  "Short Passing": 12,
  "Long Passing": 14,
  "Free Kick": 5,
  "Awareness": 13,
  "Reactions": 12,
  "Ball Control": 12,
  "Dribbling": 8,
  "Composure": 7,
  "Heading": 9,
  "Marking": 13,
  "Tackling": 12,
  "Strength": 4,
  "Aggression": 4
}, {
  "Acceleration": 11,
  "Sprint Speed": 14,
  "Finishing": 13,
  "Long Shot": 16,
  "Shot Power": 8,
  "Positioning": 15,
  "Crossing": 5,
  "Short Passing": 13,
  "Long Passing": 14,
  "Free Kick": 6,
  "Awareness": 13,
  "Reactions": 12,
  "Ball Control": 12,
  "Dribbling": 8,
  "Composure": 7,
  "Heading": 10,
  "Marking": 14,
  "Tackling": 13,
  "Strength": 4,
  "Aggression": 4
}, {
  "Acceleration": 12,
  "Sprint Speed": 14,
  "Finishing": 13,
  "Long Shot": 16,
  "Shot Power": 8,
  "Positioning": 16,
  "Crossing": 5,
  "Short Passing": 14,
  "Long Passing": 15,
  "Free Kick": 6,
  "Awareness": 13,
  "Reactions": 13,
  "Ball Control": 13,
  "Dribbling": 9,
  "Composure": 7,
  "Heading": 10,
  "Marking": 14,
  "Tackling": 13,
  "Strength": 5,
  "Aggression": 5
}, {
  "Acceleration": 12,
  "Sprint Speed": 15,
  "Finishing": 14,
  "Long Shot": 17,
  "Shot Power": 8,
  "Positioning": 16,
  "Crossing": 6,
  "Short Passing": 14,
  "Long Passing": 15,
  "Free Kick": 7,
  "Awareness": 14,
  "Reactions": 13,
  "Ball Control": 13,
  "Dribbling": 9,
  "Composure": 7,
  "Heading": 10,
  "Marking": 14,
  "Tackling": 14,
  "Strength": 6,
  "Aggression": 5
}, {
  "Acceleration": 12,
  "Sprint Speed": 16,
  "Finishing": 14,
  "Long Shot": 17,
  "Shot Power": 9,
  "Positioning": 17,
  "Crossing": 6,
  "Short Passing": 15,
  "Long Passing": 16,
  "Free Kick": 7,
  "Awareness": 14,
  "Reactions": 13,
  "Ball Control": 13,
  "Dribbling": 9,
  "Composure": 8,
  "Heading": 11,
  "Marking": 15,
  "Tackling": 14,
  "Strength": 7,
  "Aggression": 5
}, {
  "Acceleration": 13,
  "Sprint Speed": 16,
  "Finishing": 14,
  "Long Shot": 18,
  "Shot Power": 9,
  "Positioning": 18,
  "Crossing": 6,
  "Short Passing": 16,
  "Long Passing": 16,
  "Free Kick": 7,
  "Awareness": 15,
  "Reactions": 14,
  "Ball Control": 13,
  "Dribbling": 9,
  "Composure": 8,
  "Heading": 11,
  "Marking": 15,
  "Tackling": 14,
  "Strength": 8,
  "Aggression": 6
}, {
  "Acceleration": 16,
  "Sprint Speed": 19,
  "Finishing": 17,
  "Long Shot": 21,
  "Shot Power": 9,
  "Positioning": 21,
  "Crossing": 6,
  "Short Passing": 19,
  "Long Passing": 19,
  "Free Kick": 7,
  "Awareness": 18,
  "Reactions": 17,
  "Ball Control": 16,
  "Dribbling": 12,
  "Composure": 8,
  "Heading": 11,
  "Marking": 18,
  "Tackling": 17,
  "Strength": 8,
  "Aggression": 6
}, {
  "Acceleration": 16,
  "Sprint Speed": 20,
  "Finishing": 18,
  "Long Shot": 21,
  "Shot Power": 9,
  "Positioning": 22,
  "Crossing": 6,
  "Short Passing": 19,
  "Long Passing": 20,
  "Free Kick": 7,
  "Awareness": 19,
  "Reactions": 17,
  "Ball Control": 17,
  "Dribbling": 12,
  "Composure": 8,
  "Heading": 11,
  "Marking": 19,
  "Tackling": 17,
  "Strength": 8,
  "Aggression": 7
}, {
  "Acceleration": 17,
  "Sprint Speed": 20,
  "Finishing": 18,
  "Long Shot": 22,
  "Shot Power": 10,
  "Positioning": 22,
  "Crossing": 6,
  "Short Passing": 19,
  "Long Passing": 20,
  "Free Kick": 7,
  "Awareness": 19,
  "Reactions": 18,
  "Ball Control": 17,
  "Dribbling": 12,
  "Composure": 9,
  "Heading": 12,
  "Marking": 20,
  "Tackling": 18,
  "Strength": 8,
  "Aggression": 8
}, {
  "Acceleration": 17,
  "Sprint Speed": 21,
  "Finishing": 18,
  "Long Shot": 22,
  "Shot Power": 10,
  "Positioning": 23,
  "Crossing": 7,
  "Short Passing": 20,
  "Long Passing": 20,
  "Free Kick": 8,
  "Awareness": 20,
  "Reactions": 19,
  "Ball Control": 17,
  "Dribbling": 12,
  "Composure": 9,
  "Heading": 12,
  "Marking": 20,
  "Tackling": 19,
  "Strength": 9,
  "Aggression": 8
}, {
  "Acceleration": 18,
  "Sprint Speed": 22,
  "Finishing": 19,
  "Long Shot": 22,
  "Shot Power": 10,
  "Positioning": 24,
  "Crossing": 8,
  "Short Passing": 21,
  "Long Passing": 21,
  "Free Kick": 8,
  "Awareness": 20,
  "Reactions": 19,
  "Ball Control": 18,
  "Dribbling": 13,
  "Composure": 9,
  "Heading": 12,
  "Marking": 20,
  "Tackling": 19,
  "Strength": 9,
  "Aggression": 8
}, {
  "Acceleration": 19,
  "Sprint Speed": 22,
  "Finishing": 20,
  "Long Shot": 23,
  "Shot Power": 11,
  "Positioning": 24,
  "Crossing": 8,
  "Short Passing": 22,
  "Long Passing": 22,
  "Free Kick": 8,
  "Awareness": 21,
  "Reactions": 19,
  "Ball Control": 18,
  "Dribbling": 13,
  "Composure": 10,
  "Heading": 12,
  "Marking": 21,
  "Tackling": 20,
  "Strength": 9,
  "Aggression": 9
}, {
  "Acceleration": 19,
  "Sprint Speed": 22,
  "Finishing": 21,
  "Long Shot": 23,
  "Shot Power": 11,
  "Positioning": 25,
  "Crossing": 8,
  "Short Passing": 22,
  "Long Passing": 23,
  "Free Kick": 9,
  "Awareness": 21,
  "Reactions": 20,
  "Ball Control": 19,
  "Dribbling": 13,
  "Composure": 10,
  "Heading": 13,
  "Marking": 22,
  "Tackling": 20,
  "Strength": 10,
  "Aggression": 10
}, {
  "Acceleration": 20,
  "Sprint Speed": 23,
  "Finishing": 22,
  "Long Shot": 23,
  "Shot Power": 11,
  "Positioning": 25,
  "Crossing": 8,
  "Short Passing": 23,
  "Long Passing": 24,
  "Free Kick": 9,
  "Awareness": 22,
  "Reactions": 21,
  "Ball Control": 20,
  "Dribbling": 13,
  "Composure": 10,
  "Heading": 13,
  "Marking": 22,
  "Tackling": 21,
  "Strength": 11,
  "Aggression": 10
}, {
  "Acceleration": 20,
  "Sprint Speed": 23,
  "Finishing": 22,
  "Long Shot": 24,
  "Shot Power": 11,
  "Positioning": 26,
  "Crossing": 8,
  "Short Passing": 23,
  "Long Passing": 24,
  "Free Kick": 9,
  "Awareness": 22,
  "Reactions": 22,
  "Ball Control": 21,
  "Dribbling": 14,
  "Composure": 12,
  "Heading": 13,
  "Marking": 23,
  "Tackling": 22,
  "Strength": 11,
  "Aggression": 11
}, {
  "Acceleration": 21,
  "Sprint Speed": 23,
  "Finishing": 23,
  "Long Shot": 24,
  "Shot Power": 12,
  "Positioning": 27,
  "Crossing": 9,
  "Short Passing": 24,
  "Long Passing": 25,
  "Free Kick": 10,
  "Awareness": 22,
  "Reactions": 22,
  "Ball Control": 21,
  "Dribbling": 15,
  "Composure": 13,
  "Heading": 13,
  "Marking": 23,
  "Tackling": 22,
  "Strength": 11,
  "Aggression": 11
}, {
  "Acceleration": 24,
  "Sprint Speed": 26,
  "Finishing": 26,
  "Long Shot": 27,
  "Shot Power": 12,
  "Positioning": 30,
  "Crossing": 9,
  "Short Passing": 27,
  "Long Passing": 28,
  "Free Kick": 10,
  "Awareness": 25,
  "Reactions": 25,
  "Ball Control": 24,
  "Dribbling": 18,
  "Composure": 13,
  "Heading": 13,
  "Marking": 26,
  "Tackling": 25,
  "Strength": 11,
  "Aggression": 11
}, {
  "Acceleration": 25,
  "Sprint Speed": 26,
  "Finishing": 27,
  "Long Shot": 28,
  "Shot Power": 13,
  "Positioning": 31,
  "Crossing": 9,
  "Short Passing": 28,
  "Long Passing": 29,
  "Free Kick": 10,
  "Awareness": 25,
  "Reactions": 26,
  "Ball Control": 24,
  "Dribbling": 19,
  "Composure": 14,
  "Heading": 13,
  "Marking": 27,
  "Tackling": 26,
  "Strength": 11,
  "Aggression": 12
}, {
  "Acceleration": 25,
  "Sprint Speed": 27,
  "Finishing": 28,
  "Long Shot": 28,
  "Shot Power": 13,
  "Positioning": 32,
  "Crossing": 9,
  "Short Passing": 28,
  "Long Passing": 29,
  "Free Kick": 11,
  "Awareness": 26,
  "Reactions": 27,
  "Ball Control": 25,
  "Dribbling": 20,
  "Composure": 14,
  "Heading": 13,
  "Marking": 28,
  "Tackling": 27,
  "Strength": 11,
  "Aggression": 12
}, {
  "Acceleration": 26,
  "Sprint Speed": 28,
  "Finishing": 28,
  "Long Shot": 29,
  "Shot Power": 14,
  "Positioning": 32,
  "Crossing": 10,
  "Short Passing": 29,
  "Long Passing": 30,
  "Free Kick": 11,
  "Awareness": 26,
  "Reactions": 28,
  "Ball Control": 26,
  "Dribbling": 20,
  "Composure": 16,
  "Heading": 14,
  "Marking": 28,
  "Tackling": 27,
  "Strength": 11,
  "Aggression": 13
}, {
  "Acceleration": 26,
  "Sprint Speed": 29,
  "Finishing": 29,
  "Long Shot": 29,
  "Shot Power": 14,
  "Positioning": 34,
  "Crossing": 11,
  "Short Passing": 29,
  "Long Passing": 30,
  "Free Kick": 11,
  "Awareness": 27,
  "Reactions": 29,
  "Ball Control": 27,
  "Dribbling": 20,
  "Composure": 16,
  "Heading": 14,
  "Marking": 29,
  "Tackling": 28,
  "Strength": 12,
  "Aggression": 14
}, {
  "Acceleration": 27,
  "Sprint Speed": 29,
  "Finishing": 30,
  "Long Shot": 30,
  "Shot Power": 15,
  "Positioning": 35,
  "Crossing": 11,
  "Short Passing": 30,
  "Long Passing": 30,
  "Free Kick": 11,
  "Awareness": 28,
  "Reactions": 30,
  "Ball Control": 27,
  "Dribbling": 21,
  "Composure": 19,
  "Heading": 15,
  "Marking": 30,
  "Tackling": 28,
  "Strength": 12,
  "Aggression": 14
}, {
  "Acceleration": 27,
  "Sprint Speed": 30,
  "Finishing": 31,
  "Long Shot": 30,
  "Shot Power": 15,
  "Positioning": 35,
  "Crossing": 12,
  "Short Passing": 30,
  "Long Passing": 31,
  "Free Kick": 12,
  "Awareness": 29,
  "Reactions": 31,
  "Ball Control": 28,
  "Dribbling": 22,
  "Composure": 20,
  "Heading": 15,
  "Marking": 31,
  "Tackling": 28,
  "Strength": 13,
  "Aggression": 14
}, {
  "Acceleration": 28,
  "Sprint Speed": 31,
  "Finishing": 31,
  "Long Shot": 30,
  "Shot Power": 16,
  "Positioning": 36,
  "Crossing": 12,
  "Short Passing": 31,
  "Long Passing": 31,
  "Free Kick": 12,
  "Awareness": 30,
  "Reactions": 32,
  "Ball Control": 29,
  "Dribbling": 22,
  "Composure": 20,
  "Heading": 16,
  "Marking": 31,
  "Tackling": 29,
  "Strength": 14,
  "Aggression": 15
}, {
  "Acceleration": 28,
  "Sprint Speed": 31,
  "Finishing": 32,
  "Long Shot": 32,
  "Shot Power": 16,
  "Positioning": 36,
  "Crossing": 12,
  "Short Passing": 31,
  "Long Passing": 31,
  "Free Kick": 13,
  "Awareness": 31,
  "Reactions": 33,
  "Ball Control": 30,
  "Dribbling": 23,
  "Composure": 23,
  "Heading": 16,
  "Marking": 32,
  "Tackling": 30,
  "Strength": 15,
  "Aggression": 15
}, {
  "Acceleration": 30,
  "Sprint Speed": 32,
  "Finishing": 34,
  "Long Shot": 32,
  "Shot Power": 19,
  "Positioning": 38,
  "Crossing": 13,
  "Short Passing": 32,
  "Long Passing": 32,
  "Free Kick": 13,
  "Awareness": 33,
  "Reactions": 34,
  "Ball Control": 30,
  "Dribbling": 24,
  "Composure": 23,
  "Heading": 16,
  "Marking": 32,
  "Tackling": 30,
  "Strength": 15,
  "Aggression": 16
}, {
  "Acceleration": 33,
  "Sprint Speed": 35,
  "Finishing": 34,
  "Long Shot": 32,
  "Shot Power": 19,
  "Positioning": 41,
  "Crossing": 13,
  "Short Passing": 42,
  "Long Passing": 32,
  "Free Kick": 13,
  "Awareness": 36,
  "Reactions": 36,
  "Ball Control": 33,
  "Dribbling": 26,
  "Composure": 23,
  "Heading": 16,
  "Marking": 33,
  "Tackling": 34,
  "Strength": 20,
  "Aggression": 16
}, {
  "Acceleration": 37,
  "Sprint Speed": 38,
  "Finishing": 34,
  "Long Shot": 38,
  "Shot Power": 19,
  "Positioning": 41,
  "Crossing": 13,
  "Short Passing": 47,
  "Long Passing": 32,
  "Free Kick": 13,
  "Awareness": 38,
  "Reactions": 39,
  "Ball Control": 35,
  "Dribbling": 29,
  "Composure": 38,
  "Heading": 19,
  "Marking": 37,
  "Tackling": 34,
  "Strength": 20,
  "Aggression": 21
}, {
  "Acceleration": 40,
  "Sprint Speed": 41,
  "Finishing": 37,
  "Long Shot": 38,
  "Shot Power": 19,
  "Positioning": 41,
  "Crossing": 18,
  "Short Passing": 52,
  "Long Passing": 39,
  "Free Kick": 18,
  "Awareness": 41,
  "Reactions": 41,
  "Ball Control": 38,
  "Dribbling": 32,
  "Composure": 38,
  "Heading": 19,
  "Marking": 37,
  "Tackling": 37,
  "Strength": 20,
  "Aggression": 21
}, {
  "Acceleration": 43,
  "Sprint Speed": 44,
  "Finishing": 37,
  "Long Shot": 42,
  "Shot Power": 24,
  "Positioning": 45,
  "Crossing": 18,
  "Short Passing": 52,
  "Long Passing": 39,
  "Free Kick": 18,
  "Awareness": 44,
  "Reactions": 44,
  "Ball Control": 41,
  "Dribbling": 37,
  "Composure": 38,
  "Heading": 19,
  "Marking": 40,
  "Tackling": 37,
  "Strength": 20,
  "Aggression": 26
}, {
  "Acceleration": 48,
  "Sprint Speed": 48,
  "Finishing": 42,
  "Long Shot": 42,
  "Shot Power": 29,
  "Positioning": 48,
  "Crossing": 18,
  "Short Passing": 57,
  "Long Passing": 39,
  "Free Kick": 18,
  "Awareness": 46,
  "Reactions": 46,
  "Ball Control": 43,
  "Dribbling": 40,
  "Composure": 38,
  "Heading": 25,
  "Marking": 40,
  "Tackling": 40,
  "Strength": 20,
  "Aggression": 26
}, {
  "Acceleration": 52,
  "Sprint Speed": 50,
  "Finishing": 42,
  "Long Shot": 45,
  "Shot Power": 29,
  "Positioning": 48,
  "Crossing": 18,
  "Short Passing": 62,
  "Long Passing": 49,
  "Free Kick": 18,
  "Awareness": 49,
  "Reactions": 50,
  "Ball Control": 47,
  "Dribbling": 44,
  "Composure": 48,
  "Heading": 25,
  "Marking": 40,
  "Tackling": 44,
  "Strength": 25,
  "Aggression": 26
}, {
  "Acceleration": 55,
  "Sprint Speed": 52,
  "Finishing": 42,
  "Long Shot": 45,
  "Shot Power": 29,
  "Positioning": 54,
  "Crossing": 23,
  "Short Passing": 67,
  "Long Passing": 49,
  "Free Kick": 23,
  "Awareness": 52,
  "Reactions": 52,
  "Ball Control": 49,
  "Dribbling": 49,
  "Composure": 48,
  "Heading": 25,
  "Marking": 44,
  "Tackling": 44,
  "Strength": 25,
  "Aggression": 26
}, {
  "Acceleration": 60,
  "Sprint Speed": 56,
  "Finishing": 45,
  "Long Shot": 49,
  "Shot Power": 29,
  "Positioning": 54,
  "Crossing": 23,
  "Short Passing": 67,
  "Long Passing": 49,
  "Free Kick": 23,
  "Awareness": 54,
  "Reactions": 56,
  "Ball Control": 52,
  "Dribbling": 52,
  "Composure": 48,
  "Heading": 29,
  "Marking": 47,
  "Tackling": 47,
  "Strength": 25,
  "Aggression": 26
}, {
  "Acceleration": 64,
  "Sprint Speed": 59,
  "Finishing": 49,
  "Long Shot": 53,
  "Shot Power": 34,
  "Positioning": 57,
  "Crossing": 23,
  "Short Passing": 67,
  "Long Passing": 57,
  "Free Kick": 23,
  "Awareness": 57,
  "Reactions": 59,
  "Ball Control": 56,
  "Dribbling": 56,
  "Composure": 48,
  "Heading": 29,
  "Marking": 47,
  "Tackling": 47,
  "Strength": 25,
  "Aggression": 26
}, {
  "Acceleration": 67,
  "Sprint Speed": 64,
  "Finishing": 52,
  "Long Shot": 53,
  "Shot Power": 34,
  "Positioning": 60,
  "Crossing": 23,
  "Short Passing": 70,
  "Long Passing": 57,
  "Free Kick": 23,
  "Awareness": 60,
  "Reactions": 62,
  "Ball Control": 58,
  "Dribbling": 59,
  "Composure": 48,
  "Heading": 29,
  "Marking": 51,
  "Tackling": 50,
  "Strength": 28,
  "Aggression": 26
}, {
  "Acceleration": 67,
  "Sprint Speed": 64,
  "Finishing": 52,
  "Long Shot": 58,
  "Shot Power": 34,
  "Positioning": 65,
  "Crossing": 28,
  "Short Passing": 70,
  "Long Passing": 62,
  "Free Kick": 23,
  "Awareness": 65,
  "Reactions": 66,
  "Ball Control": 63,
  "Dribbling": 64,
  "Composure": 48,
  "Heading": 29,
  "Marking": 56,
  "Tackling": 55,
  "Strength": 28,
  "Aggression": 31
}]