export default [{
  "Acceleration": 0,
  "Sprint Speed": 2,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 0,
  "Positioning": 0,
  "Crossing": 0,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 0,
  "Reactions": 0,
  "Ball Control": 0,
  "Dribbling": 0,
  "Composure": 0,
  "Heading": 0,
  "Marking": 1,
  "Tackling": 0,
  "Strength": 0,
  "Aggression": 1,
  "GK Diving": 1,
  "GK Positioning": 1,
  "Handling": 1,
  "Reflexes": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 2,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 0,
  "Positioning": 1,
  "Crossing": 0,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 0,
  "Reactions": 1,
  "Ball Control": 0,
  "Dribbling": 0,
  "Composure": 1,
  "Heading": 0,
  "Marking": 2,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 3,
  "GK Diving": 1,
  "GK Positioning": 1,
  "Handling": 2,
  "Reflexes": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 3,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 0,
  "Positioning": 1,
  "Crossing": 0,
  "Short Passing": 1,
  "Long Passing": 2,
  "Free Kick": 2,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 0,
  "Dribbling": 0,
  "Composure": 1,
  "Heading": 1,
  "Marking": 2,
  "Tackling": 2,
  "Strength": 1,
  "Aggression": 4,
  "GK Diving": 1,
  "GK Positioning": 2,
  "Handling": 3,
  "Reflexes": 2
}, {
  "Acceleration": 1,
  "Sprint Speed": 3,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 1,
  "Positioning": 1,
  "Crossing": 0,
  "Short Passing": 1,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 1,
  "Reactions": 2,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 2,
  "Heading": 1,
  "Marking": 3,
  "Tackling": 3,
  "Strength": 1,
  "Aggression": 4,
  "GK Diving": 2,
  "GK Positioning": 2,
  "Handling": 4,
  "Reflexes": 2
}, {
  "Acceleration": 2,
  "Sprint Speed": 3,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 2,
  "Positioning": 2,
  "Crossing": 0,
  "Short Passing": 2,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 1,
  "Reactions": 2,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 3,
  "Heading": 1,
  "Marking": 3,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 6,
  "GK Diving": 2,
  "GK Positioning": 2,
  "Handling": 5,
  "Reflexes": 3
}, {
  "Acceleration": 2,
  "Sprint Speed": 5,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 2,
  "Positioning": 2,
  "Crossing": 0,
  "Short Passing": 2,
  "Long Passing": 3,
  "Free Kick": 3,
  "Awareness": 2,
  "Reactions": 3,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 4,
  "Heading": 2,
  "Marking": 3,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 6,
  "GK Diving": 2,
  "GK Positioning": 2,
  "Handling": 6,
  "Reflexes": 4
}, {
  "Acceleration": 2,
  "Sprint Speed": 6,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 0,
  "Short Passing": 2,
  "Long Passing": 4,
  "Free Kick": 3,
  "Awareness": 2,
  "Reactions": 3,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 5,
  "Heading": 2,
  "Marking": 3,
  "Tackling": 4,
  "Strength": 3,
  "Aggression": 7,
  "GK Diving": 3,
  "GK Positioning": 3,
  "Handling": 7,
  "Reflexes": 4
}, {
  "Acceleration": 3,
  "Sprint Speed": 6,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 0,
  "Short Passing": 3,
  "Long Passing": 4,
  "Free Kick": 4,
  "Awareness": 2,
  "Reactions": 4,
  "Ball Control": 2,
  "Dribbling": 0,
  "Composure": 5,
  "Heading": 3,
  "Marking": 4,
  "Tackling": 4,
  "Strength": 3,
  "Aggression": 7,
  "GK Diving": 3,
  "GK Positioning": 3,
  "Handling": 7,
  "Reflexes": 5
}, {
  "Acceleration": 3,
  "Sprint Speed": 8,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 3,
  "Positioning": 3,
  "Crossing": 0,
  "Short Passing": 3,
  "Long Passing": 4,
  "Free Kick": 4,
  "Awareness": 3,
  "Reactions": 5,
  "Ball Control": 2,
  "Dribbling": 0,
  "Composure": 5,
  "Heading": 3,
  "Marking": 4,
  "Tackling": 5,
  "Strength": 3,
  "Aggression": 8,
  "GK Diving": 3,
  "GK Positioning": 3,
  "Handling": 8,
  "Reflexes": 5
}, {
  "Acceleration": 3,
  "Sprint Speed": 8,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 3,
  "Positioning": 4,
  "Crossing": 0,
  "Short Passing": 3,
  "Long Passing": 4,
  "Free Kick": 5,
  "Awareness": 3,
  "Reactions": 5,
  "Ball Control": 3,
  "Dribbling": 0,
  "Composure": 6,
  "Heading": 3,
  "Marking": 5,
  "Tackling": 6,
  "Strength": 4,
  "Aggression": 8,
  "GK Diving": 4,
  "GK Positioning": 4,
  "Handling": 8,
  "Reflexes": 5
}, {
  "Acceleration": 4,
  "Sprint Speed": 9,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 3,
  "Positioning": 4,
  "Crossing": 0,
  "Short Passing": 3,
  "Long Passing": 5,
  "Free Kick": 6,
  "Awareness": 4,
  "Reactions": 5,
  "Ball Control": 4,
  "Dribbling": 0,
  "Composure": 6,
  "Heading": 3,
  "Marking": 5,
  "Tackling": 6,
  "Strength": 4,
  "Aggression": 10,
  "GK Diving": 4,
  "GK Positioning": 4,
  "Handling": 9,
  "Reflexes": 6
}, {
  "Acceleration": 4,
  "Sprint Speed": 9,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 4,
  "Positioning": 5,
  "Crossing": 0,
  "Short Passing": 4,
  "Long Passing": 5,
  "Free Kick": 6,
  "Awareness": 4,
  "Reactions": 6,
  "Ball Control": 4,
  "Dribbling": 0,
  "Composure": 6,
  "Heading": 4,
  "Marking": 6,
  "Tackling": 6,
  "Strength": 4,
  "Aggression": 11,
  "GK Diving": 4,
  "GK Positioning": 4,
  "Handling": 9,
  "Reflexes": 6
}, {
  "Acceleration": 4,
  "Sprint Speed": 9,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 4,
  "Positioning": 5,
  "Crossing": 0,
  "Short Passing": 4,
  "Long Passing": 5,
  "Free Kick": 7,
  "Awareness": 4,
  "Reactions": 6,
  "Ball Control": 4,
  "Dribbling": 0,
  "Composure": 7,
  "Heading": 4,
  "Marking": 6,
  "Tackling": 6,
  "Strength": 5,
  "Aggression": 11,
  "GK Diving": 5,
  "GK Positioning": 5,
  "Handling": 10,
  "Reflexes": 7
}, {
  "Acceleration": 5,
  "Sprint Speed": 9,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 4,
  "Positioning": 5,
  "Crossing": 0,
  "Short Passing": 4,
  "Long Passing": 5,
  "Free Kick": 7,
  "Awareness": 5,
  "Reactions": 7,
  "Ball Control": 4,
  "Dribbling": 0,
  "Composure": 7,
  "Heading": 4,
  "Marking": 7,
  "Tackling": 6,
  "Strength": 6,
  "Aggression": 12,
  "GK Diving": 5,
  "GK Positioning": 5,
  "Handling": 11,
  "Reflexes": 7
}, {
  "Acceleration": 5,
  "Sprint Speed": 10,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 5,
  "Positioning": 6,
  "Crossing": 0,
  "Short Passing": 4,
  "Long Passing": 6,
  "Free Kick": 7,
  "Awareness": 5,
  "Reactions": 7,
  "Ball Control": 5,
  "Dribbling": 0,
  "Composure": 8,
  "Heading": 4,
  "Marking": 7,
  "Tackling": 6,
  "Strength": 6,
  "Aggression": 12,
  "GK Diving": 5,
  "GK Positioning": 5,
  "Handling": 12,
  "Reflexes": 8
}, {
  "Acceleration": 7,
  "Sprint Speed": 12,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 5,
  "Positioning": 8,
  "Crossing": 0,
  "Short Passing": 6,
  "Long Passing": 8,
  "Free Kick": 9,
  "Awareness": 7,
  "Reactions": 10,
  "Ball Control": 7,
  "Dribbling": 0,
  "Composure": 10,
  "Heading": 6,
  "Marking": 9,
  "Tackling": 8,
  "Strength": 8,
  "Aggression": 14,
  "GK Diving": 8,
  "GK Positioning": 8,
  "Handling": 15,
  "Reflexes": 11
}, {
  "Acceleration": 8,
  "Sprint Speed": 13,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 6,
  "Positioning": 9,
  "Crossing": 0,
  "Short Passing": 7,
  "Long Passing": 8,
  "Free Kick": 10,
  "Awareness": 7,
  "Reactions": 10,
  "Ball Control": 7,
  "Dribbling": 0,
  "Composure": 10,
  "Heading": 6,
  "Marking": 10,
  "Tackling": 9,
  "Strength": 8,
  "Aggression": 16,
  "GK Diving": 8,
  "GK Positioning": 8,
  "Handling": 15,
  "Reflexes": 12
}, {
  "Acceleration": 8,
  "Sprint Speed": 14,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 6,
  "Positioning": 9,
  "Crossing": 0,
  "Short Passing": 7,
  "Long Passing": 9,
  "Free Kick": 10,
  "Awareness": 8,
  "Reactions": 10,
  "Ball Control": 7,
  "Dribbling": 0,
  "Composure": 11,
  "Heading": 7,
  "Marking": 10,
  "Tackling": 10,
  "Strength": 9,
  "Aggression": 17,
  "GK Diving": 8,
  "GK Positioning": 8,
  "Handling": 16,
  "Reflexes": 12
}, {
  "Acceleration": 8,
  "Sprint Speed": 14,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 6,
  "Positioning": 9,
  "Crossing": 0,
  "Short Passing": 7,
  "Long Passing": 10,
  "Free Kick": 11,
  "Awareness": 9,
  "Reactions": 11,
  "Ball Control": 7,
  "Dribbling": 0,
  "Composure": 12,
  "Heading": 7,
  "Marking": 10,
  "Tackling": 10,
  "Strength": 9,
  "Aggression": 17,
  "GK Diving": 9,
  "GK Positioning": 9,
  "Handling": 17,
  "Reflexes": 13
}, {
  "Acceleration": 8,
  "Sprint Speed": 16,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 7,
  "Positioning": 10,
  "Crossing": 0,
  "Short Passing": 8,
  "Long Passing": 10,
  "Free Kick": 11,
  "Awareness": 10,
  "Reactions": 11,
  "Ball Control": 8,
  "Dribbling": 0,
  "Composure": 12,
  "Heading": 7,
  "Marking": 11,
  "Tackling": 11,
  "Strength": 10,
  "Aggression": 17,
  "GK Diving": 9,
  "GK Positioning": 9,
  "Handling": 17,
  "Reflexes": 13
}, {
  "Acceleration": 9,
  "Sprint Speed": 17,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 7,
  "Positioning": 11,
  "Crossing": 0,
  "Short Passing": 8,
  "Long Passing": 10,
  "Free Kick": 11,
  "Awareness": 10,
  "Reactions": 11,
  "Ball Control": 8,
  "Dribbling": 0,
  "Composure": 12,
  "Heading": 8,
  "Marking": 11,
  "Tackling": 11,
  "Strength": 10,
  "Aggression": 19,
  "GK Diving": 9,
  "GK Positioning": 9,
  "Handling": 18,
  "Reflexes": 14
}, {
  "Acceleration": 9,
  "Sprint Speed": 17,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 7,
  "Positioning": 11,
  "Crossing": 0,
  "Short Passing": 8,
  "Long Passing": 11,
  "Free Kick": 12,
  "Awareness": 11,
  "Reactions": 12,
  "Ball Control": 8,
  "Dribbling": 0,
  "Composure": 13,
  "Heading": 8,
  "Marking": 11,
  "Tackling": 11,
  "Strength": 11,
  "Aggression": 19,
  "GK Diving": 10,
  "GK Positioning": 10,
  "Handling": 19,
  "Reflexes": 14
}, {
  "Acceleration": 9,
  "Sprint Speed": 18,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 7,
  "Positioning": 11,
  "Crossing": 0,
  "Short Passing": 9,
  "Long Passing": 12,
  "Free Kick": 12,
  "Awareness": 11,
  "Reactions": 12,
  "Ball Control": 9,
  "Dribbling": 0,
  "Composure": 13,
  "Heading": 9,
  "Marking": 12,
  "Tackling": 12,
  "Strength": 11,
  "Aggression": 20,
  "GK Diving": 10,
  "GK Positioning": 10,
  "Handling": 19,
  "Reflexes": 15
}, {
  "Acceleration": 10,
  "Sprint Speed": 18,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 8,
  "Positioning": 12,
  "Crossing": 0,
  "Short Passing": 9,
  "Long Passing": 13,
  "Free Kick": 12,
  "Awareness": 12,
  "Reactions": 12,
  "Ball Control": 9,
  "Dribbling": 0,
  "Composure": 13,
  "Heading": 9,
  "Marking": 13,
  "Tackling": 12,
  "Strength": 11,
  "Aggression": 22,
  "GK Diving": 10,
  "GK Positioning": 12,
  "Handling": 20,
  "Reflexes": 15
}, {
  "Acceleration": 10,
  "Sprint Speed": 18,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 8,
  "Positioning": 12,
  "Crossing": 0,
  "Short Passing": 9,
  "Long Passing": 13,
  "Free Kick": 13,
  "Awareness": 12,
  "Reactions": 13,
  "Ball Control": 9,
  "Dribbling": 0,
  "Composure": 14,
  "Heading": 9,
  "Marking": 13,
  "Tackling": 12,
  "Strength": 12,
  "Aggression": 22,
  "GK Diving": 11,
  "GK Positioning": 12,
  "Handling": 21,
  "Reflexes": 16
}, {
  "Acceleration": 12,
  "Sprint Speed": 20,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 8,
  "Positioning": 14,
  "Crossing": 0,
  "Short Passing": 11,
  "Long Passing": 15,
  "Free Kick": 15,
  "Awareness": 14,
  "Reactions": 16,
  "Ball Control": 11,
  "Dribbling": 0,
  "Composure": 16,
  "Heading": 11,
  "Marking": 15,
  "Tackling": 14,
  "Strength": 14,
  "Aggression": 24,
  "GK Diving": 14,
  "GK Positioning": 15,
  "Handling": 24,
  "Reflexes": 19
}, {
  "Acceleration": 12,
  "Sprint Speed": 20,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 8,
  "Positioning": 15,
  "Crossing": 0,
  "Short Passing": 11,
  "Long Passing": 16,
  "Free Kick": 15,
  "Awareness": 14,
  "Reactions": 17,
  "Ball Control": 11,
  "Dribbling": 0,
  "Composure": 17,
  "Heading": 11,
  "Marking": 16,
  "Tackling": 15,
  "Strength": 15,
  "Aggression": 25,
  "GK Diving": 14,
  "GK Positioning": 15,
  "Handling": 24,
  "Reflexes": 19
}, {
  "Acceleration": 13,
  "Sprint Speed": 20,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 8,
  "Positioning": 15,
  "Crossing": 0,
  "Short Passing": 11,
  "Long Passing": 17,
  "Free Kick": 16,
  "Awareness": 15,
  "Reactions": 17,
  "Ball Control": 12,
  "Dribbling": 0,
  "Composure": 17,
  "Heading": 11,
  "Marking": 16,
  "Tackling": 16,
  "Strength": 15,
  "Aggression": 25,
  "GK Diving": 15,
  "GK Positioning": 15,
  "Handling": 24,
  "Reflexes": 20
}, {
  "Acceleration": 13,
  "Sprint Speed": 21,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 9,
  "Positioning": 16,
  "Crossing": 0,
  "Short Passing": 12,
  "Long Passing": 18,
  "Free Kick": 16,
  "Awareness": 15,
  "Reactions": 17,
  "Ball Control": 12,
  "Dribbling": 0,
  "Composure": 17,
  "Heading": 12,
  "Marking": 16,
  "Tackling": 16,
  "Strength": 15,
  "Aggression": 25,
  "GK Diving": 16,
  "GK Positioning": 15,
  "Handling": 25,
  "Reflexes": 21
}, {
  "Acceleration": 13,
  "Sprint Speed": 21,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 9,
  "Positioning": 17,
  "Crossing": 0,
  "Short Passing": 12,
  "Long Passing": 18,
  "Free Kick": 16,
  "Awareness": 16,
  "Reactions": 18,
  "Ball Control": 12,
  "Dribbling": 0,
  "Composure": 18,
  "Heading": 12,
  "Marking": 16,
  "Tackling": 17,
  "Strength": 16,
  "Aggression": 26,
  "GK Diving": 17,
  "GK Positioning": 16,
  "Handling": 26,
  "Reflexes": 22
}, {
  "Acceleration": 14,
  "Sprint Speed": 22,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 10,
  "Positioning": 18,
  "Crossing": 0,
  "Short Passing": 12,
  "Long Passing": 18,
  "Free Kick": 16,
  "Awareness": 16,
  "Reactions": 18,
  "Ball Control": 12,
  "Dribbling": 0,
  "Composure": 18,
  "Heading": 13,
  "Marking": 16,
  "Tackling": 17,
  "Strength": 17,
  "Aggression": 27,
  "GK Diving": 17,
  "GK Positioning": 16,
  "Handling": 26,
  "Reflexes": 23
}, {
  "Acceleration": 14,
  "Sprint Speed": 22,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 11,
  "Positioning": 19,
  "Crossing": 0,
  "Short Passing": 12,
  "Long Passing": 18,
  "Free Kick": 17,
  "Awareness": 16,
  "Reactions": 19,
  "Ball Control": 13,
  "Dribbling": 0,
  "Composure": 18,
  "Heading": 13,
  "Marking": 16,
  "Tackling": 17,
  "Strength": 17,
  "Aggression": 28,
  "GK Diving": 18,
  "GK Positioning": 17,
  "Handling": 26,
  "Reflexes": 24
}, {
  "Acceleration": 14,
  "Sprint Speed": 22,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 11,
  "Positioning": 20,
  "Crossing": 0,
  "Short Passing": 14,
  "Long Passing": 19,
  "Free Kick": 17,
  "Awareness": 17,
  "Reactions": 19,
  "Ball Control": 13,
  "Dribbling": 0,
  "Composure": 19,
  "Heading": 13,
  "Marking": 17,
  "Tackling": 18,
  "Strength": 17,
  "Aggression": 28,
  "GK Diving": 19,
  "GK Positioning": 17,
  "Handling": 27,
  "Reflexes": 25
}, {
  "Acceleration": 15,
  "Sprint Speed": 23,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 11,
  "Positioning": 20,
  "Crossing": 0,
  "Short Passing": 14,
  "Long Passing": 20,
  "Free Kick": 18,
  "Awareness": 17,
  "Reactions": 19,
  "Ball Control": 13,
  "Dribbling": 0,
  "Composure": 19,
  "Heading": 14,
  "Marking": 17,
  "Tackling": 19,
  "Strength": 18,
  "Aggression": 29,
  "GK Diving": 20,
  "GK Positioning": 17,
  "Handling": 27,
  "Reflexes": 26
}, {
  "Acceleration": 15,
  "Sprint Speed": 23,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 11,
  "Positioning": 21,
  "Crossing": 0,
  "Short Passing": 14,
  "Long Passing": 21,
  "Free Kick": 18,
  "Awareness": 17,
  "Reactions": 20,
  "Ball Control": 13,
  "Dribbling": 0,
  "Composure": 20,
  "Heading": 14,
  "Marking": 18,
  "Tackling": 19,
  "Strength": 18,
  "Aggression": 30,
  "GK Diving": 21,
  "GK Positioning": 17,
  "Handling": 27,
  "Reflexes": 27
}, {
  "Acceleration": 17,
  "Sprint Speed": 25,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 11,
  "Positioning": 23,
  "Crossing": 0,
  "Short Passing": 16,
  "Long Passing": 23,
  "Free Kick": 20,
  "Awareness": 19,
  "Reactions": 23,
  "Ball Control": 15,
  "Dribbling": 0,
  "Composure": 22,
  "Heading": 16,
  "Marking": 20,
  "Tackling": 21,
  "Strength": 20,
  "Aggression": 32,
  "GK Diving": 24,
  "GK Positioning": 20,
  "Handling": 30,
  "Reflexes": 30
}, {
  "Acceleration": 18,
  "Sprint Speed": 26,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 11,
  "Positioning": 24,
  "Crossing": 0,
  "Short Passing": 18,
  "Long Passing": 23,
  "Free Kick": 21,
  "Awareness": 20,
  "Reactions": 24,
  "Ball Control": 15,
  "Dribbling": 0,
  "Composure": 22,
  "Heading": 16,
  "Marking": 20,
  "Tackling": 22,
  "Strength": 20,
  "Aggression": 33,
  "GK Diving": 26,
  "GK Positioning": 20,
  "Handling": 30,
  "Reflexes": 31
}, {
  "Acceleration": 18,
  "Sprint Speed": 26,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 11,
  "Positioning": 25,
  "Crossing": 0,
  "Short Passing": 18,
  "Long Passing": 24,
  "Free Kick": 21,
  "Awareness": 21,
  "Reactions": 24,
  "Ball Control": 15,
  "Dribbling": 0,
  "Composure": 23,
  "Heading": 17,
  "Marking": 20,
  "Tackling": 22,
  "Strength": 21,
  "Aggression": 34,
  "GK Diving": 27,
  "GK Positioning": 21,
  "Handling": 31,
  "Reflexes": 32
}, {
  "Acceleration": 18,
  "Sprint Speed": 26,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 12,
  "Positioning": 26,
  "Crossing": 0,
  "Short Passing": 19,
  "Long Passing": 24,
  "Free Kick": 21,
  "Awareness": 21,
  "Reactions": 25,
  "Ball Control": 15,
  "Dribbling": 0,
  "Composure": 24,
  "Heading": 17,
  "Marking": 21,
  "Tackling": 22,
  "Strength": 22,
  "Aggression": 34,
  "GK Diving": 28,
  "GK Positioning": 22,
  "Handling": 31,
  "Reflexes": 33
}, {
  "Acceleration": 19,
  "Sprint Speed": 27,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 12,
  "Positioning": 27,
  "Crossing": 0,
  "Short Passing": 19,
  "Long Passing": 25,
  "Free Kick": 21,
  "Awareness": 22,
  "Reactions": 25,
  "Ball Control": 15,
  "Dribbling": 0,
  "Composure": 24,
  "Heading": 17,
  "Marking": 22,
  "Tackling": 23,
  "Strength": 23,
  "Aggression": 35,
  "GK Diving": 30,
  "GK Positioning": 22,
  "Handling": 31,
  "Reflexes": 34
}, {
  "Acceleration": 19,
  "Sprint Speed": 27,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 13,
  "Positioning": 28,
  "Crossing": 0,
  "Short Passing": 19,
  "Long Passing": 25,
  "Free Kick": 22,
  "Awareness": 23,
  "Reactions": 25,
  "Ball Control": 15,
  "Dribbling": 0,
  "Composure": 25,
  "Heading": 17,
  "Marking": 22,
  "Tackling": 23,
  "Strength": 23,
  "Aggression": 35,
  "GK Diving": 32,
  "GK Positioning": 23,
  "Handling": 32,
  "Reflexes": 35
}, {
  "Acceleration": 19,
  "Sprint Speed": 27,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 13,
  "Positioning": 29,
  "Crossing": 0,
  "Short Passing": 19,
  "Long Passing": 26,
  "Free Kick": 22,
  "Awareness": 23,
  "Reactions": 26,
  "Ball Control": 16,
  "Dribbling": 0,
  "Composure": 25,
  "Heading": 18,
  "Marking": 22,
  "Tackling": 24,
  "Strength": 24,
  "Aggression": 36,
  "GK Diving": 32,
  "GK Positioning": 25,
  "Handling": 32,
  "Reflexes": 36
}, {
  "Acceleration": 20,
  "Sprint Speed": 27,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 13,
  "Positioning": 30,
  "Crossing": 0,
  "Short Passing": 19,
  "Long Passing": 26,
  "Free Kick": 23,
  "Awareness": 24,
  "Reactions": 26,
  "Ball Control": 16,
  "Dribbling": 0,
  "Composure": 26,
  "Heading": 18,
  "Marking": 23,
  "Tackling": 24,
  "Strength": 24,
  "Aggression": 37,
  "GK Diving": 34,
  "GK Positioning": 25,
  "Handling": 32,
  "Reflexes": 37
}, {
  "Acceleration": 20,
  "Sprint Speed": 27,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 13,
  "Positioning": 31,
  "Crossing": 0,
  "Short Passing": 19,
  "Long Passing": 27,
  "Free Kick": 23,
  "Awareness": 24,
  "Reactions": 26,
  "Ball Control": 17,
  "Dribbling": 0,
  "Composure": 26,
  "Heading": 19,
  "Marking": 23,
  "Tackling": 25,
  "Strength": 24,
  "Aggression": 38,
  "GK Diving": 34,
  "GK Positioning": 27,
  "Handling": 33,
  "Reflexes": 38
}, {
  "Acceleration": 21,
  "Sprint Speed": 28,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 13,
  "Positioning": 32,
  "Crossing": 0,
  "Short Passing": 19,
  "Long Passing": 28,
  "Free Kick": 23,
  "Awareness": 25,
  "Reactions": 26,
  "Ball Control": 17,
  "Dribbling": 0,
  "Composure": 26,
  "Heading": 19,
  "Marking": 23,
  "Tackling": 25,
  "Strength": 25,
  "Aggression": 38,
  "GK Diving": 34,
  "GK Positioning": 29,
  "Handling": 34,
  "Reflexes": 39
}, {
  "Acceleration": 21,
  "Sprint Speed": 29,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 13,
  "Positioning": 37,
  "Crossing": 0,
  "Short Passing": 19,
  "Long Passing": 29,
  "Free Kick": 23,
  "Awareness": 25,
  "Reactions": 31,
  "Ball Control": 17,
  "Dribbling": 0,
  "Composure": 37,
  "Heading": 19,
  "Marking": 23,
  "Tackling": 25,
  "Strength": 25,
  "Aggression": 40,
  "GK Diving": 38,
  "GK Positioning": 31,
  "Handling": 36,
  "Reflexes": 40
}, {
  "Acceleration": 24,
  "Sprint Speed": 29,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 23,
  "Positioning": 37,
  "Crossing": 0,
  "Short Passing": 22,
  "Long Passing": 29,
  "Free Kick": 38,
  "Awareness": 30,
  "Reactions": 36,
  "Ball Control": 17,
  "Dribbling": 0,
  "Composure": 37,
  "Heading": 19,
  "Marking": 23,
  "Tackling": 26,
  "Strength": 26,
  "Aggression": 40,
  "GK Diving": 41,
  "GK Positioning": 36,
  "Handling": 39,
  "Reflexes": 45
}, {
  "Acceleration": 24,
  "Sprint Speed": 29,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 23,
  "Positioning": 42,
  "Crossing": 0,
  "Short Passing": 26,
  "Long Passing": 32,
  "Free Kick": 38,
  "Awareness": 30,
  "Reactions": 38,
  "Ball Control": 22,
  "Dribbling": 0,
  "Composure": 37,
  "Heading": 19,
  "Marking": 28,
  "Tackling": 26,
  "Strength": 27,
  "Aggression": 44,
  "GK Diving": 45,
  "GK Positioning": 39,
  "Handling": 43,
  "Reflexes": 47
}, {
  "Acceleration": 27,
  "Sprint Speed": 34,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 23,
  "Positioning": 42,
  "Crossing": 0,
  "Short Passing": 29,
  "Long Passing": 36,
  "Free Kick": 38,
  "Awareness": 35,
  "Reactions": 40,
  "Ball Control": 22,
  "Dribbling": 0,
  "Composure": 37,
  "Heading": 19,
  "Marking": 28,
  "Tackling": 26,
  "Strength": 27,
  "Aggression": 48,
  "GK Diving": 48,
  "GK Positioning": 44,
  "Handling": 46,
  "Reflexes": 50
}, {
  "Acceleration": 27,
  "Sprint Speed": 34,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 23,
  "Positioning": 42,
  "Crossing": 0,
  "Short Passing": 32,
  "Long Passing": 39,
  "Free Kick": 38,
  "Awareness": 35,
  "Reactions": 43,
  "Ball Control": 26,
  "Dribbling": 0,
  "Composure": 37,
  "Heading": 29,
  "Marking": 33,
  "Tackling": 31,
  "Strength": 27,
  "Aggression": 48,
  "GK Diving": 52,
  "GK Positioning": 50,
  "Handling": 50,
  "Reflexes": 53
}, {
  "Acceleration": 30,
  "Sprint Speed": 34,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 23,
  "Positioning": 48,
  "Crossing": 0,
  "Short Passing": 36,
  "Long Passing": 43,
  "Free Kick": 38,
  "Awareness": 40,
  "Reactions": 43,
  "Ball Control": 26,
  "Dribbling": 0,
  "Composure": 37,
  "Heading": 29,
  "Marking": 33,
  "Tackling": 31,
  "Strength": 32,
  "Aggression": 51,
  "GK Diving": 55,
  "GK Positioning": 53,
  "Handling": 55,
  "Reflexes": 57
}, {
  "Acceleration": 30,
  "Sprint Speed": 34,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 23,
  "Positioning": 48,
  "Crossing": 0,
  "Short Passing": 38,
  "Long Passing": 46,
  "Free Kick": 38,
  "Awareness": 40,
  "Reactions": 51,
  "Ball Control": 32,
  "Dribbling": 0,
  "Composure": 43,
  "Heading": 29,
  "Marking": 33,
  "Tackling": 36,
  "Strength": 32,
  "Aggression": 56,
  "GK Diving": 58,
  "GK Positioning": 58,
  "Handling": 59,
  "Reflexes": 60
}, {
  "Acceleration": 33,
  "Sprint Speed": 34,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 23,
  "Positioning": 54,
  "Crossing": 0,
  "Short Passing": 43,
  "Long Passing": 49,
  "Free Kick": 38,
  "Awareness": 45,
  "Reactions": 56,
  "Ball Control": 32,
  "Dribbling": 0,
  "Composure": 43,
  "Heading": 29,
  "Marking": 33,
  "Tackling": 36,
  "Strength": 37,
  "Aggression": 56,
  "GK Diving": 62,
  "GK Positioning": 61,
  "Handling": 64,
  "Reflexes": 62
}, {
  "Acceleration": 36,
  "Sprint Speed": 39,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 23,
  "Positioning": 54,
  "Crossing": 0,
  "Short Passing": 46,
  "Long Passing": 53,
  "Free Kick": 38,
  "Awareness": 45,
  "Reactions": 61,
  "Ball Control": 32,
  "Dribbling": 0,
  "Composure": 43,
  "Heading": 39,
  "Marking": 33,
  "Tackling": 36,
  "Strength": 37,
  "Aggression": 60,
  "GK Diving": 67,
  "GK Positioning": 64,
  "Handling": 68,
  "Reflexes": 67
}, {
  "Acceleration": 39,
  "Sprint Speed": 39,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 33,
  "Positioning": 54,
  "Crossing": 0,
  "Short Passing": 50,
  "Long Passing": 56,
  "Free Kick": 38,
  "Awareness": 50,
  "Reactions": 67,
  "Ball Control": 32,
  "Dribbling": 0,
  "Composure": 63,
  "Heading": 39,
  "Marking": 33,
  "Tackling": 36,
  "Strength": 37,
  "Aggression": 60,
  "GK Diving": 70,
  "GK Positioning": 69,
  "Handling": 72,
  "Reflexes": 67
}, {
  "Acceleration": 44,
  "Sprint Speed": 44,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 33,
  "Positioning": 64,
  "Crossing": 0,
  "Short Passing": 53,
  "Long Passing": 61,
  "Free Kick": 38,
  "Awareness": 60,
  "Reactions": 67,
  "Ball Control": 32,
  "Dribbling": 0,
  "Composure": 63,
  "Heading": 39,
  "Marking": 33,
  "Tackling": 36,
  "Strength": 37,
  "Aggression": 63,
  "GK Diving": 72,
  "GK Positioning": 74,
  "Handling": 77,
  "Reflexes": 67
}]