export default [{
  "Acceleration": 1,
  "Sprint Speed": 0,
  "Finishing": 1,
  "Long Shot": 0,
  "Shot Power": 0,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 0,
  "Dribbling": 0,
  "Composure": 0,
  "Heading": 0,
  "Marking": 1,
  "Tackling": 0,
  "Strength": 0,
  "Aggression": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 1,
  "Long Shot": 1,
  "Shot Power": 1,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 0,
  "Dribbling": 0,
  "Composure": 0,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 2,
  "Finishing": 1,
  "Long Shot": 2,
  "Shot Power": 1,
  "Positioning": 2,
  "Crossing": 2,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 2,
  "Ball Control": 0,
  "Dribbling": 0,
  "Composure": 0,
  "Heading": 1,
  "Marking": 2,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 2
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 2,
  "Shot Power": 1,
  "Positioning": 2,
  "Crossing": 2,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 3,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 1,
  "Heading": 2,
  "Marking": 2,
  "Tackling": 1,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 3,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 3,
  "Shot Power": 2,
  "Positioning": 2,
  "Crossing": 2,
  "Short Passing": 3,
  "Long Passing": 2,
  "Free Kick": 2,
  "Awareness": 2,
  "Reactions": 3,
  "Ball Control": 2,
  "Dribbling": 1,
  "Composure": 1,
  "Heading": 3,
  "Marking": 2,
  "Tackling": 1,
  "Strength": 3,
  "Aggression": 2
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 3,
  "Long Shot": 4,
  "Shot Power": 2,
  "Positioning": 2,
  "Crossing": 2,
  "Short Passing": 4,
  "Long Passing": 2,
  "Free Kick": 2,
  "Awareness": 3,
  "Reactions": 4,
  "Ball Control": 2,
  "Dribbling": 1,
  "Composure": 1,
  "Heading": 3,
  "Marking": 3,
  "Tackling": 2,
  "Strength": 3,
  "Aggression": 3
}, {
  "Acceleration": 4,
  "Sprint Speed": 3,
  "Finishing": 3,
  "Long Shot": 4,
  "Shot Power": 3,
  "Positioning": 3,
  "Crossing": 3,
  "Short Passing": 4,
  "Long Passing": 2,
  "Free Kick": 2,
  "Awareness": 4,
  "Reactions": 4,
  "Ball Control": 3,
  "Dribbling": 2,
  "Composure": 1,
  "Heading": 4,
  "Marking": 3,
  "Tackling": 3,
  "Strength": 3,
  "Aggression": 3
}, {
  "Acceleration": 4,
  "Sprint Speed": 3,
  "Finishing": 4,
  "Long Shot": 5,
  "Shot Power": 3,
  "Positioning": 3,
  "Crossing": 4,
  "Short Passing": 4,
  "Long Passing": 2,
  "Free Kick": 3,
  "Awareness": 4,
  "Reactions": 5,
  "Ball Control": 3,
  "Dribbling": 2,
  "Composure": 2,
  "Heading": 5,
  "Marking": 4,
  "Tackling": 4,
  "Strength": 4,
  "Aggression": 3
}, {
  "Acceleration": 4,
  "Sprint Speed": 4,
  "Finishing": 4,
  "Long Shot": 5,
  "Shot Power": 4,
  "Positioning": 3,
  "Crossing": 5,
  "Short Passing": 5,
  "Long Passing": 2,
  "Free Kick": 3,
  "Awareness": 5,
  "Reactions": 5,
  "Ball Control": 4,
  "Dribbling": 2,
  "Composure": 2,
  "Heading": 5,
  "Marking": 5,
  "Tackling": 5,
  "Strength": 4,
  "Aggression": 4
}, {
  "Acceleration": 5,
  "Sprint Speed": 4,
  "Finishing": 4,
  "Long Shot": 6,
  "Shot Power": 5,
  "Positioning": 3,
  "Crossing": 7,
  "Short Passing": 5,
  "Long Passing": 2,
  "Free Kick": 3,
  "Awareness": 5,
  "Reactions": 6,
  "Ball Control": 4,
  "Dribbling": 2,
  "Composure": 3,
  "Heading": 6,
  "Marking": 6,
  "Tackling": 5,
  "Strength": 5,
  "Aggression": 4
}, {
  "Acceleration": 5,
  "Sprint Speed": 5,
  "Finishing": 5,
  "Long Shot": 6,
  "Shot Power": 5,
  "Positioning": 3,
  "Crossing": 7,
  "Short Passing": 6,
  "Long Passing": 3,
  "Free Kick": 3,
  "Awareness": 6,
  "Reactions": 6,
  "Ball Control": 5,
  "Dribbling": 3,
  "Composure": 3,
  "Heading": 6,
  "Marking": 7,
  "Tackling": 6,
  "Strength": 5,
  "Aggression": 5
}, {
  "Acceleration": 5,
  "Sprint Speed": 6,
  "Finishing": 5,
  "Long Shot": 6,
  "Shot Power": 5,
  "Positioning": 3,
  "Crossing": 8,
  "Short Passing": 7,
  "Long Passing": 3,
  "Free Kick": 4,
  "Awareness": 6,
  "Reactions": 6,
  "Ball Control": 6,
  "Dribbling": 3,
  "Composure": 3,
  "Heading": 7,
  "Marking": 8,
  "Tackling": 7,
  "Strength": 6,
  "Aggression": 5
}, {
  "Acceleration": 6,
  "Sprint Speed": 6,
  "Finishing": 5,
  "Long Shot": 7,
  "Shot Power": 5,
  "Positioning": 4,
  "Crossing": 9,
  "Short Passing": 7,
  "Long Passing": 4,
  "Free Kick": 4,
  "Awareness": 7,
  "Reactions": 7,
  "Ball Control": 6,
  "Dribbling": 3,
  "Composure": 4,
  "Heading": 7,
  "Marking": 9,
  "Tackling": 7,
  "Strength": 6,
  "Aggression": 5
}, {
  "Acceleration": 6,
  "Sprint Speed": 7,
  "Finishing": 6,
  "Long Shot": 7,
  "Shot Power": 6,
  "Positioning": 4,
  "Crossing": 10,
  "Short Passing": 7,
  "Long Passing": 5,
  "Free Kick": 4,
  "Awareness": 7,
  "Reactions": 7,
  "Ball Control": 7,
  "Dribbling": 3,
  "Composure": 4,
  "Heading": 8,
  "Marking": 10,
  "Tackling": 7,
  "Strength": 7,
  "Aggression": 6
}, {
  "Acceleration": 6,
  "Sprint Speed": 7,
  "Finishing": 6,
  "Long Shot": 7,
  "Shot Power": 7,
  "Positioning": 4,
  "Crossing": 11,
  "Short Passing": 8,
  "Long Passing": 5,
  "Free Kick": 5,
  "Awareness": 8,
  "Reactions": 8,
  "Ball Control": 7,
  "Dribbling": 4,
  "Composure": 4,
  "Heading": 8,
  "Marking": 11,
  "Tackling": 8,
  "Strength": 7,
  "Aggression": 7
}, {
  "Acceleration": 7,
  "Sprint Speed": 7,
  "Finishing": 6,
  "Long Shot": 8,
  "Shot Power": 7,
  "Positioning": 4,
  "Crossing": 12,
  "Short Passing": 9,
  "Long Passing": 6,
  "Free Kick": 5,
  "Awareness": 8,
  "Reactions": 8,
  "Ball Control": 8,
  "Dribbling": 4,
  "Composure": 5,
  "Heading": 9,
  "Marking": 11,
  "Tackling": 8,
  "Strength": 7,
  "Aggression": 8
}, {
  "Acceleration": 10,
  "Sprint Speed": 10,
  "Finishing": 6,
  "Long Shot": 8,
  "Shot Power": 10,
  "Positioning": 7,
  "Crossing": 15,
  "Short Passing": 12,
  "Long Passing": 9,
  "Free Kick": 5,
  "Awareness": 11,
  "Reactions": 11,
  "Ball Control": 11,
  "Dribbling": 4,
  "Composure": 5,
  "Heading": 12,
  "Marking": 14,
  "Tackling": 11,
  "Strength": 10,
  "Aggression": 11
}, {
  "Acceleration": 11,
  "Sprint Speed": 10,
  "Finishing": 7,
  "Long Shot": 9,
  "Shot Power": 10,
  "Positioning": 8,
  "Crossing": 16,
  "Short Passing": 13,
  "Long Passing": 9,
  "Free Kick": 6,
  "Awareness": 11,
  "Reactions": 12,
  "Ball Control": 11,
  "Dribbling": 4,
  "Composure": 5,
  "Heading": 12,
  "Marking": 14,
  "Tackling": 12,
  "Strength": 11,
  "Aggression": 11
}, {
  "Acceleration": 11,
  "Sprint Speed": 11,
  "Finishing": 7,
  "Long Shot": 10,
  "Shot Power": 11,
  "Positioning": 8,
  "Crossing": 17,
  "Short Passing": 13,
  "Long Passing": 10,
  "Free Kick": 6,
  "Awareness": 11,
  "Reactions": 12,
  "Ball Control": 12,
  "Dribbling": 5,
  "Composure": 5,
  "Heading": 12,
  "Marking": 15,
  "Tackling": 12,
  "Strength": 11,
  "Aggression": 12
}, {
  "Acceleration": 12,
  "Sprint Speed": 12,
  "Finishing": 7,
  "Long Shot": 10,
  "Shot Power": 11,
  "Positioning": 8,
  "Crossing": 18,
  "Short Passing": 14,
  "Long Passing": 10,
  "Free Kick": 6,
  "Awareness": 12,
  "Reactions": 13,
  "Ball Control": 12,
  "Dribbling": 5,
  "Composure": 6,
  "Heading": 13,
  "Marking": 15,
  "Tackling": 12,
  "Strength": 11,
  "Aggression": 13
}, {
  "Acceleration": 12,
  "Sprint Speed": 12,
  "Finishing": 8,
  "Long Shot": 11,
  "Shot Power": 12,
  "Positioning": 8,
  "Crossing": 19,
  "Short Passing": 15,
  "Long Passing": 10,
  "Free Kick": 7,
  "Awareness": 12,
  "Reactions": 13,
  "Ball Control": 12,
  "Dribbling": 5,
  "Composure": 7,
  "Heading": 13,
  "Marking": 15,
  "Tackling": 13,
  "Strength": 12,
  "Aggression": 14
}, {
  "Acceleration": 13,
  "Sprint Speed": 12,
  "Finishing": 8,
  "Long Shot": 11,
  "Shot Power": 12,
  "Positioning": 8,
  "Crossing": 20,
  "Short Passing": 15,
  "Long Passing": 10,
  "Free Kick": 7,
  "Awareness": 13,
  "Reactions": 13,
  "Ball Control": 13,
  "Dribbling": 6,
  "Composure": 8,
  "Heading": 14,
  "Marking": 16,
  "Tackling": 13,
  "Strength": 12,
  "Aggression": 15
}, {
  "Acceleration": 13,
  "Sprint Speed": 13,
  "Finishing": 9,
  "Long Shot": 11,
  "Shot Power": 13,
  "Positioning": 8,
  "Crossing": 21,
  "Short Passing": 16,
  "Long Passing": 10,
  "Free Kick": 7,
  "Awareness": 13,
  "Reactions": 14,
  "Ball Control": 13,
  "Dribbling": 6,
  "Composure": 8,
  "Heading": 14,
  "Marking": 17,
  "Tackling": 13,
  "Strength": 13,
  "Aggression": 16
}, {
  "Acceleration": 14,
  "Sprint Speed": 13,
  "Finishing": 9,
  "Long Shot": 12,
  "Shot Power": 13,
  "Positioning": 9,
  "Crossing": 22,
  "Short Passing": 16,
  "Long Passing": 11,
  "Free Kick": 7,
  "Awareness": 14,
  "Reactions": 14,
  "Ball Control": 13,
  "Dribbling": 6,
  "Composure": 8,
  "Heading": 15,
  "Marking": 18,
  "Tackling": 13,
  "Strength": 13,
  "Aggression": 17
}, {
  "Acceleration": 14,
  "Sprint Speed": 13,
  "Finishing": 10,
  "Long Shot": 12,
  "Shot Power": 14,
  "Positioning": 9,
  "Crossing": 23,
  "Short Passing": 17,
  "Long Passing": 11,
  "Free Kick": 8,
  "Awareness": 14,
  "Reactions": 14,
  "Ball Control": 14,
  "Dribbling": 6,
  "Composure": 9,
  "Heading": 15,
  "Marking": 18,
  "Tackling": 13,
  "Strength": 14,
  "Aggression": 17
}, {
  "Acceleration": 15,
  "Sprint Speed": 13,
  "Finishing": 10,
  "Long Shot": 13,
  "Shot Power": 14,
  "Positioning": 10,
  "Crossing": 24,
  "Short Passing": 17,
  "Long Passing": 11,
  "Free Kick": 8,
  "Awareness": 15,
  "Reactions": 15,
  "Ball Control": 14,
  "Dribbling": 6,
  "Composure": 9,
  "Heading": 16,
  "Marking": 19,
  "Tackling": 13,
  "Strength": 14,
  "Aggression": 18
}, {
  "Acceleration": 18,
  "Sprint Speed": 16,
  "Finishing": 10,
  "Long Shot": 13,
  "Shot Power": 17,
  "Positioning": 13,
  "Crossing": 27,
  "Short Passing": 20,
  "Long Passing": 14,
  "Free Kick": 8,
  "Awareness": 18,
  "Reactions": 18,
  "Ball Control": 17,
  "Dribbling": 6,
  "Composure": 9,
  "Heading": 19,
  "Marking": 22,
  "Tackling": 16,
  "Strength": 17,
  "Aggression": 21
}, {
  "Acceleration": 18,
  "Sprint Speed": 16,
  "Finishing": 11,
  "Long Shot": 13,
  "Shot Power": 18,
  "Positioning": 13,
  "Crossing": 28,
  "Short Passing": 21,
  "Long Passing": 14,
  "Free Kick": 9,
  "Awareness": 18,
  "Reactions": 18,
  "Ball Control": 18,
  "Dribbling": 6,
  "Composure": 9,
  "Heading": 20,
  "Marking": 23,
  "Tackling": 17,
  "Strength": 18,
  "Aggression": 22
}, {
  "Acceleration": 18,
  "Sprint Speed": 17,
  "Finishing": 11,
  "Long Shot": 14,
  "Shot Power": 18,
  "Positioning": 14,
  "Crossing": 29,
  "Short Passing": 22,
  "Long Passing": 14,
  "Free Kick": 9,
  "Awareness": 19,
  "Reactions": 19,
  "Ball Control": 18,
  "Dribbling": 6,
  "Composure": 9,
  "Heading": 20,
  "Marking": 23,
  "Tackling": 18,
  "Strength": 18,
  "Aggression": 23
}, {
  "Acceleration": 19,
  "Sprint Speed": 17,
  "Finishing": 11,
  "Long Shot": 14,
  "Shot Power": 18,
  "Positioning": 14,
  "Crossing": 30,
  "Short Passing": 22,
  "Long Passing": 15,
  "Free Kick": 9,
  "Awareness": 20,
  "Reactions": 19,
  "Ball Control": 18,
  "Dribbling": 7,
  "Composure": 10,
  "Heading": 21,
  "Marking": 24,
  "Tackling": 19,
  "Strength": 19,
  "Aggression": 24
}, {
  "Acceleration": 19,
  "Sprint Speed": 18,
  "Finishing": 12,
  "Long Shot": 14,
  "Shot Power": 19,
  "Positioning": 15,
  "Crossing": 31,
  "Short Passing": 22,
  "Long Passing": 15,
  "Free Kick": 10,
  "Awareness": 20,
  "Reactions": 20,
  "Ball Control": 19,
  "Dribbling": 7,
  "Composure": 10,
  "Heading": 21,
  "Marking": 24,
  "Tackling": 20,
  "Strength": 19,
  "Aggression": 25
}, {
  "Acceleration": 20,
  "Sprint Speed": 18,
  "Finishing": 12,
  "Long Shot": 14,
  "Shot Power": 20,
  "Positioning": 16,
  "Crossing": 32,
  "Short Passing": 23,
  "Long Passing": 15,
  "Free Kick": 10,
  "Awareness": 21,
  "Reactions": 21,
  "Ball Control": 19,
  "Dribbling": 7,
  "Composure": 10,
  "Heading": 22,
  "Marking": 25,
  "Tackling": 21,
  "Strength": 19,
  "Aggression": 26
}, {
  "Acceleration": 20,
  "Sprint Speed": 19,
  "Finishing": 12,
  "Long Shot": 15,
  "Shot Power": 20,
  "Positioning": 17,
  "Crossing": 33,
  "Short Passing": 24,
  "Long Passing": 16,
  "Free Kick": 11,
  "Awareness": 21,
  "Reactions": 21,
  "Ball Control": 19,
  "Dribbling": 7,
  "Composure": 10,
  "Heading": 22,
  "Marking": 26,
  "Tackling": 22,
  "Strength": 20,
  "Aggression": 27
}, {
  "Acceleration": 21,
  "Sprint Speed": 19,
  "Finishing": 12,
  "Long Shot": 15,
  "Shot Power": 20,
  "Positioning": 17,
  "Crossing": 34,
  "Short Passing": 25,
  "Long Passing": 16,
  "Free Kick": 11,
  "Awareness": 21,
  "Reactions": 22,
  "Ball Control": 20,
  "Dribbling": 8,
  "Composure": 10,
  "Heading": 23,
  "Marking": 27,
  "Tackling": 23,
  "Strength": 20,
  "Aggression": 27
}, {
  "Acceleration": 21,
  "Sprint Speed": 19,
  "Finishing": 13,
  "Long Shot": 15,
  "Shot Power": 21,
  "Positioning": 18,
  "Crossing": 35,
  "Short Passing": 25,
  "Long Passing": 16,
  "Free Kick": 11,
  "Awareness": 22,
  "Reactions": 22,
  "Ball Control": 20,
  "Dribbling": 8,
  "Composure": 11,
  "Heading": 24,
  "Marking": 28,
  "Tackling": 23,
  "Strength": 21,
  "Aggression": 28
}, {
  "Acceleration": 22,
  "Sprint Speed": 20,
  "Finishing": 13,
  "Long Shot": 16,
  "Shot Power": 21,
  "Positioning": 18,
  "Crossing": 36,
  "Short Passing": 25,
  "Long Passing": 17,
  "Free Kick": 12,
  "Awareness": 22,
  "Reactions": 22,
  "Ball Control": 21,
  "Dribbling": 8,
  "Composure": 12,
  "Heading": 24,
  "Marking": 28,
  "Tackling": 24,
  "Strength": 21,
  "Aggression": 28
}, {
  "Acceleration": 25,
  "Sprint Speed": 23,
  "Finishing": 13,
  "Long Shot": 16,
  "Shot Power": 24,
  "Positioning": 21,
  "Crossing": 39,
  "Short Passing": 28,
  "Long Passing": 20,
  "Free Kick": 12,
  "Awareness": 25,
  "Reactions": 25,
  "Ball Control": 24,
  "Dribbling": 8,
  "Composure": 12,
  "Heading": 27,
  "Marking": 31,
  "Tackling": 27,
  "Strength": 24,
  "Aggression": 31
}, {
  "Acceleration": 26,
  "Sprint Speed": 24,
  "Finishing": 13,
  "Long Shot": 16,
  "Shot Power": 25,
  "Positioning": 21,
  "Crossing": 40,
  "Short Passing": 28,
  "Long Passing": 20,
  "Free Kick": 12,
  "Awareness": 25,
  "Reactions": 25,
  "Ball Control": 25,
  "Dribbling": 9,
  "Composure": 12,
  "Heading": 28,
  "Marking": 31,
  "Tackling": 29,
  "Strength": 24,
  "Aggression": 32
}, {
  "Acceleration": 26,
  "Sprint Speed": 24,
  "Finishing": 13,
  "Long Shot": 17,
  "Shot Power": 25,
  "Positioning": 21,
  "Crossing": 41,
  "Short Passing": 28,
  "Long Passing": 21,
  "Free Kick": 13,
  "Awareness": 26,
  "Reactions": 26,
  "Ball Control": 25,
  "Dribbling": 9,
  "Composure": 13,
  "Heading": 29,
  "Marking": 32,
  "Tackling": 29,
  "Strength": 24,
  "Aggression": 33
}, {
  "Acceleration": 27,
  "Sprint Speed": 24,
  "Finishing": 14,
  "Long Shot": 17,
  "Shot Power": 25,
  "Positioning": 22,
  "Crossing": 42,
  "Short Passing": 29,
  "Long Passing": 21,
  "Free Kick": 13,
  "Awareness": 26,
  "Reactions": 27,
  "Ball Control": 26,
  "Dribbling": 9,
  "Composure": 13,
  "Heading": 29,
  "Marking": 32,
  "Tackling": 31,
  "Strength": 25,
  "Aggression": 34
}, {
  "Acceleration": 27,
  "Sprint Speed": 25,
  "Finishing": 15,
  "Long Shot": 17,
  "Shot Power": 26,
  "Positioning": 22,
  "Crossing": 43,
  "Short Passing": 29,
  "Long Passing": 22,
  "Free Kick": 13,
  "Awareness": 26,
  "Reactions": 27,
  "Ball Control": 27,
  "Dribbling": 10,
  "Composure": 14,
  "Heading": 30,
  "Marking": 35,
  "Tackling": 31,
  "Strength": 25,
  "Aggression": 35
}, {
  "Acceleration": 28,
  "Sprint Speed": 25,
  "Finishing": 15,
  "Long Shot": 18,
  "Shot Power": 26,
  "Positioning": 24,
  "Crossing": 44,
  "Short Passing": 30,
  "Long Passing": 22,
  "Free Kick": 14,
  "Awareness": 27,
  "Reactions": 28,
  "Ball Control": 27,
  "Dribbling": 10,
  "Composure": 14,
  "Heading": 31,
  "Marking": 35,
  "Tackling": 34,
  "Strength": 26,
  "Aggression": 36
}, {
  "Acceleration": 28,
  "Sprint Speed": 26,
  "Finishing": 15,
  "Long Shot": 18,
  "Shot Power": 27,
  "Positioning": 24,
  "Crossing": 45,
  "Short Passing": 32,
  "Long Passing": 23,
  "Free Kick": 14,
  "Awareness": 27,
  "Reactions": 28,
  "Ball Control": 28,
  "Dribbling": 11,
  "Composure": 15,
  "Heading": 31,
  "Marking": 37,
  "Tackling": 36,
  "Strength": 26,
  "Aggression": 37
}, {
  "Acceleration": 29,
  "Sprint Speed": 26,
  "Finishing": 15,
  "Long Shot": 18,
  "Shot Power": 27,
  "Positioning": 24,
  "Crossing": 46,
  "Short Passing": 33,
  "Long Passing": 24,
  "Free Kick": 14,
  "Awareness": 28,
  "Reactions": 29,
  "Ball Control": 29,
  "Dribbling": 11,
  "Composure": 15,
  "Heading": 32,
  "Marking": 37,
  "Tackling": 37,
  "Strength": 27,
  "Aggression": 38
}, {
  "Acceleration": 29,
  "Sprint Speed": 27,
  "Finishing": 16,
  "Long Shot": 19,
  "Shot Power": 28,
  "Positioning": 25,
  "Crossing": 47,
  "Short Passing": 33,
  "Long Passing": 24,
  "Free Kick": 15,
  "Awareness": 28,
  "Reactions": 29,
  "Ball Control": 30,
  "Dribbling": 11,
  "Composure": 15,
  "Heading": 33,
  "Marking": 37,
  "Tackling": 38,
  "Strength": 27,
  "Aggression": 39
}, {
  "Acceleration": 31,
  "Sprint Speed": 27,
  "Finishing": 17,
  "Long Shot": 19,
  "Shot Power": 28,
  "Positioning": 27,
  "Crossing": 48,
  "Short Passing": 34,
  "Long Passing": 24,
  "Free Kick": 15,
  "Awareness": 28,
  "Reactions": 29,
  "Ball Control": 32,
  "Dribbling": 11,
  "Composure": 17,
  "Heading": 34,
  "Marking": 38,
  "Tackling": 39,
  "Strength": 28,
  "Aggression": 39
}, {
  "Acceleration": 31,
  "Sprint Speed": 30,
  "Finishing": 17,
  "Long Shot": 19,
  "Shot Power": 28,
  "Positioning": 27,
  "Crossing": 49,
  "Short Passing": 37,
  "Long Passing": 28,
  "Free Kick": 18,
  "Awareness": 28,
  "Reactions": 31,
  "Ball Control": 32,
  "Dribbling": 13,
  "Composure": 37,
  "Heading": 34,
  "Marking": 40,
  "Tackling": 42,
  "Strength": 33,
  "Aggression": 40
}, {
  "Acceleration": 34,
  "Sprint Speed": 32,
  "Finishing": 17,
  "Long Shot": 20,
  "Shot Power": 38,
  "Positioning": 30,
  "Crossing": 54,
  "Short Passing": 39,
  "Long Passing": 28,
  "Free Kick": 18,
  "Awareness": 31,
  "Reactions": 34,
  "Ball Control": 36,
  "Dribbling": 13,
  "Composure": 37,
  "Heading": 38,
  "Marking": 43,
  "Tackling": 46,
  "Strength": 33,
  "Aggression": 40
}, {
  "Acceleration": 37,
  "Sprint Speed": 34,
  "Finishing": 17,
  "Long Shot": 20,
  "Shot Power": 38,
  "Positioning": 33,
  "Crossing": 56,
  "Short Passing": 43,
  "Long Passing": 32,
  "Free Kick": 26,
  "Awareness": 31,
  "Reactions": 38,
  "Ball Control": 36,
  "Dribbling": 13,
  "Composure": 42,
  "Heading": 42,
  "Marking": 47,
  "Tackling": 49,
  "Strength": 33,
  "Aggression": 45
}, {
  "Acceleration": 40,
  "Sprint Speed": 37,
  "Finishing": 27,
  "Long Shot": 20,
  "Shot Power": 38,
  "Positioning": 33,
  "Crossing": 60,
  "Short Passing": 43,
  "Long Passing": 35,
  "Free Kick": 26,
  "Awareness": 41,
  "Reactions": 41,
  "Ball Control": 41,
  "Dribbling": 15,
  "Composure": 42,
  "Heading": 45,
  "Marking": 51,
  "Tackling": 53,
  "Strength": 38,
  "Aggression": 45
}, {
  "Acceleration": 44,
  "Sprint Speed": 44,
  "Finishing": 27,
  "Long Shot": 20,
  "Shot Power": 48,
  "Positioning": 33,
  "Crossing": 62,
  "Short Passing": 49,
  "Long Passing": 39,
  "Free Kick": 26,
  "Awareness": 43,
  "Reactions": 45,
  "Ball Control": 41,
  "Dribbling": 15,
  "Composure": 47,
  "Heading": 49,
  "Marking": 54,
  "Tackling": 56,
  "Strength": 38,
  "Aggression": 50
}, {
  "Acceleration": 47,
  "Sprint Speed": 48,
  "Finishing": 27,
  "Long Shot": 23,
  "Shot Power": 48,
  "Positioning": 36,
  "Crossing": 66,
  "Short Passing": 49,
  "Long Passing": 41,
  "Free Kick": 26,
  "Awareness": 43,
  "Reactions": 48,
  "Ball Control": 45,
  "Dribbling": 18,
  "Composure": 47,
  "Heading": 52,
  "Marking": 58,
  "Tackling": 60,
  "Strength": 38,
  "Aggression": 50
}, {
  "Acceleration": 52,
  "Sprint Speed": 51,
  "Finishing": 37,
  "Long Shot": 23,
  "Shot Power": 48,
  "Positioning": 36,
  "Crossing": 68,
  "Short Passing": 57,
  "Long Passing": 47,
  "Free Kick": 26,
  "Awareness": 46,
  "Reactions": 54,
  "Ball Control": 50,
  "Dribbling": 18,
  "Composure": 52,
  "Heading": 55,
  "Marking": 61,
  "Tackling": 65,
  "Strength": 38,
  "Aggression": 50
}, {
  "Acceleration": 55,
  "Sprint Speed": 55,
  "Finishing": 37,
  "Long Shot": 26,
  "Shot Power": 48,
  "Positioning": 39,
  "Crossing": 71,
  "Short Passing": 57,
  "Long Passing": 47,
  "Free Kick": 26,
  "Awareness": 49,
  "Reactions": 54,
  "Ball Control": 53,
  "Dribbling": 20,
  "Composure": 52,
  "Heading": 59,
  "Marking": 66,
  "Tackling": 68,
  "Strength": 38,
  "Aggression": 55
}, {
  "Acceleration": 59,
  "Sprint Speed": 57,
  "Finishing": 37,
  "Long Shot": 26,
  "Shot Power": 48,
  "Positioning": 39,
  "Crossing": 74,
  "Short Passing": 60,
  "Long Passing": 50,
  "Free Kick": 26,
  "Awareness": 49,
  "Reactions": 57,
  "Ball Control": 57,
  "Dribbling": 23,
  "Composure": 57,
  "Heading": 62,
  "Marking": 69,
  "Tackling": 71,
  "Strength": 43,
  "Aggression": 55
}, {
  "Acceleration": 62,
  "Sprint Speed": 59,
  "Finishing": 37,
  "Long Shot": 29,
  "Shot Power": 48,
  "Positioning": 42,
  "Crossing": 79,
  "Short Passing": 64,
  "Long Passing": 52,
  "Free Kick": 26,
  "Awareness": 54,
  "Reactions": 57,
  "Ball Control": 57,
  "Dribbling": 23,
  "Composure": 57,
  "Heading": 66,
  "Marking": 73,
  "Tackling": 72,
  "Strength": 48,
  "Aggression": 55
}, {
  "Acceleration": 68,
  "Sprint Speed": 64,
  "Finishing": 37,
  "Long Shot": 29,
  "Shot Power": 48,
  "Positioning": 47,
  "Crossing": 84,
  "Short Passing": 64,
  "Long Passing": 57,
  "Free Kick": 26,
  "Awareness": 54,
  "Reactions": 67,
  "Ball Control": 62,
  "Dribbling": 28,
  "Composure": 57,
  "Heading": 66,
  "Marking": 78,
  "Tackling": 72,
  "Strength": 48,
  "Aggression": 55
}]