export default [{
  "Acceleration": 1,
  "Sprint Speed": 0,
  "Finishing": 1,
  "Long Shot": 0,
  "Shot Power": 1,
  "Positioning": 0,
  "Crossing": 0,
  "Short Passing": 0,
  "Long Passing": 1,
  "Free Kick": 0,
  "Awareness": 1,
  "Reactions": 0,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 1,
  "Heading": 0,
  "Marking": 1,
  "Tackling": 0,
  "Strength": 0,
  "Aggression": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 1,
  "Long Shot": 0,
  "Shot Power": 1,
  "Positioning": 1,
  "Crossing": 0,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 0,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 2,
  "Heading": 0,
  "Marking": 2,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 2,
  "Long Shot": 0,
  "Shot Power": 2,
  "Positioning": 2,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 2,
  "Heading": 1,
  "Marking": 3,
  "Tackling": 1,
  "Strength": 2,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 1,
  "Shot Power": 2,
  "Positioning": 2,
  "Crossing": 1,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 1,
  "Ball Control": 2,
  "Dribbling": 1,
  "Composure": 3,
  "Heading": 1,
  "Marking": 3,
  "Tackling": 2,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 2,
  "Shot Power": 3,
  "Positioning": 2,
  "Crossing": 2,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 2,
  "Ball Control": 3,
  "Dribbling": 2,
  "Composure": 4,
  "Heading": 1,
  "Marking": 4,
  "Tackling": 2,
  "Strength": 3,
  "Aggression": 2
}, {
  "Acceleration": 3,
  "Sprint Speed": 2,
  "Finishing": 3,
  "Long Shot": 2,
  "Shot Power": 3,
  "Positioning": 2,
  "Crossing": 3,
  "Short Passing": 3,
  "Long Passing": 2,
  "Free Kick": 2,
  "Awareness": 3,
  "Reactions": 2,
  "Ball Control": 3,
  "Dribbling": 2,
  "Composure": 4,
  "Heading": 2,
  "Marking": 5,
  "Tackling": 3,
  "Strength": 3,
  "Aggression": 3
}, {
  "Acceleration": 6,
  "Sprint Speed": 5,
  "Finishing": 6,
  "Long Shot": 5,
  "Shot Power": 6,
  "Positioning": 5,
  "Crossing": 3,
  "Short Passing": 6,
  "Long Passing": 2,
  "Free Kick": 2,
  "Awareness": 6,
  "Reactions": 5,
  "Ball Control": 6,
  "Dribbling": 5,
  "Composure": 4,
  "Heading": 5,
  "Marking": 5,
  "Tackling": 3,
  "Strength": 6,
  "Aggression": 3
}, {
  "Acceleration": 6,
  "Sprint Speed": 5,
  "Finishing": 7,
  "Long Shot": 5,
  "Shot Power": 6,
  "Positioning": 6,
  "Crossing": 3,
  "Short Passing": 7,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 6,
  "Reactions": 6,
  "Ball Control": 7,
  "Dribbling": 6,
  "Composure": 5,
  "Heading": 5,
  "Marking": 6,
  "Tackling": 4,
  "Strength": 7,
  "Aggression": 3
}, {
  "Acceleration": 7,
  "Sprint Speed": 5,
  "Finishing": 8,
  "Long Shot": 6,
  "Shot Power": 6,
  "Positioning": 6,
  "Crossing": 4,
  "Short Passing": 8,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 7,
  "Reactions": 6,
  "Ball Control": 7,
  "Dribbling": 6,
  "Composure": 5,
  "Heading": 6,
  "Marking": 7,
  "Tackling": 4,
  "Strength": 8,
  "Aggression": 3
}, {
  "Acceleration": 7,
  "Sprint Speed": 6,
  "Finishing": 8,
  "Long Shot": 7,
  "Shot Power": 7,
  "Positioning": 7,
  "Crossing": 4,
  "Short Passing": 8,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 8,
  "Reactions": 7,
  "Ball Control": 7,
  "Dribbling": 7,
  "Composure": 6,
  "Heading": 6,
  "Marking": 7,
  "Tackling": 5,
  "Strength": 8,
  "Aggression": 3
}, {
  "Acceleration": 8,
  "Sprint Speed": 6,
  "Finishing": 9,
  "Long Shot": 7,
  "Shot Power": 7,
  "Positioning": 8,
  "Crossing": 4,
  "Short Passing": 9,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 9,
  "Reactions": 7,
  "Ball Control": 8,
  "Dribbling": 7,
  "Composure": 6,
  "Heading": 6,
  "Marking": 8,
  "Tackling": 5,
  "Strength": 9,
  "Aggression": 4
}, {
  "Acceleration": 9,
  "Sprint Speed": 7,
  "Finishing": 9,
  "Long Shot": 8,
  "Shot Power": 8,
  "Positioning": 8,
  "Crossing": 5,
  "Short Passing": 10,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 9,
  "Reactions": 7,
  "Ball Control": 8,
  "Dribbling": 7,
  "Composure": 6,
  "Heading": 7,
  "Marking": 9,
  "Tackling": 5,
  "Strength": 10,
  "Aggression": 4
}, {
  "Acceleration": 9,
  "Sprint Speed": 7,
  "Finishing": 10,
  "Long Shot": 9,
  "Shot Power": 8,
  "Positioning": 9,
  "Crossing": 5,
  "Short Passing": 10,
  "Long Passing": 4,
  "Free Kick": 2,
  "Awareness": 10,
  "Reactions": 8,
  "Ball Control": 9,
  "Dribbling": 8,
  "Composure": 6,
  "Heading": 8,
  "Marking": 9,
  "Tackling": 5,
  "Strength": 10,
  "Aggression": 4
}, {
  "Acceleration": 10,
  "Sprint Speed": 7,
  "Finishing": 10,
  "Long Shot": 9,
  "Shot Power": 9,
  "Positioning": 9,
  "Crossing": 6,
  "Short Passing": 11,
  "Long Passing": 4,
  "Free Kick": 2,
  "Awareness": 10,
  "Reactions": 8,
  "Ball Control": 10,
  "Dribbling": 8,
  "Composure": 6,
  "Heading": 8,
  "Marking": 10,
  "Tackling": 6,
  "Strength": 11,
  "Aggression": 5
}, {
  "Acceleration": 10,
  "Sprint Speed": 7,
  "Finishing": 11,
  "Long Shot": 10,
  "Shot Power": 9,
  "Positioning": 10,
  "Crossing": 6,
  "Short Passing": 11,
  "Long Passing": 4,
  "Free Kick": 2,
  "Awareness": 11,
  "Reactions": 9,
  "Ball Control": 10,
  "Dribbling": 8,
  "Composure": 7,
  "Heading": 9,
  "Marking": 10,
  "Tackling": 7,
  "Strength": 12,
  "Aggression": 5
}, {
  "Acceleration": 10,
  "Sprint Speed": 8,
  "Finishing": 11,
  "Long Shot": 10,
  "Shot Power": 10,
  "Positioning": 10,
  "Crossing": 7,
  "Short Passing": 12,
  "Long Passing": 4,
  "Free Kick": 2,
  "Awareness": 11,
  "Reactions": 10,
  "Ball Control": 10,
  "Dribbling": 9,
  "Composure": 8,
  "Heading": 9,
  "Marking": 11,
  "Tackling": 7,
  "Strength": 13,
  "Aggression": 5
}, {
  "Acceleration": 13,
  "Sprint Speed": 11,
  "Finishing": 14,
  "Long Shot": 13,
  "Shot Power": 13,
  "Positioning": 13,
  "Crossing": 7,
  "Short Passing": 15,
  "Long Passing": 4,
  "Free Kick": 2,
  "Awareness": 14,
  "Reactions": 13,
  "Ball Control": 13,
  "Dribbling": 12,
  "Composure": 8,
  "Heading": 12,
  "Marking": 11,
  "Tackling": 7,
  "Strength": 16,
  "Aggression": 5
}, {
  "Acceleration": 13,
  "Sprint Speed": 12,
  "Finishing": 14,
  "Long Shot": 14,
  "Shot Power": 13,
  "Positioning": 13,
  "Crossing": 7,
  "Short Passing": 15,
  "Long Passing": 4,
  "Free Kick": 2,
  "Awareness": 14,
  "Reactions": 13,
  "Ball Control": 14,
  "Dribbling": 13,
  "Composure": 9,
  "Heading": 13,
  "Marking": 12,
  "Tackling": 7,
  "Strength": 17,
  "Aggression": 6
}, {
  "Acceleration": 14,
  "Sprint Speed": 12,
  "Finishing": 15,
  "Long Shot": 15,
  "Shot Power": 14,
  "Positioning": 13,
  "Crossing": 7,
  "Short Passing": 16,
  "Long Passing": 5,
  "Free Kick": 2,
  "Awareness": 14,
  "Reactions": 13,
  "Ball Control": 14,
  "Dribbling": 14,
  "Composure": 9,
  "Heading": 14,
  "Marking": 12,
  "Tackling": 8,
  "Strength": 17,
  "Aggression": 6
}, {
  "Acceleration": 14,
  "Sprint Speed": 13,
  "Finishing": 15,
  "Long Shot": 16,
  "Shot Power": 14,
  "Positioning": 14,
  "Crossing": 8,
  "Short Passing": 16,
  "Long Passing": 5,
  "Free Kick": 3,
  "Awareness": 15,
  "Reactions": 13,
  "Ball Control": 15,
  "Dribbling": 14,
  "Composure": 9,
  "Heading": 14,
  "Marking": 13,
  "Tackling": 9,
  "Strength": 17,
  "Aggression": 6
}, {
  "Acceleration": 14,
  "Sprint Speed": 13,
  "Finishing": 16,
  "Long Shot": 17,
  "Shot Power": 15,
  "Positioning": 14,
  "Crossing": 8,
  "Short Passing": 17,
  "Long Passing": 5,
  "Free Kick": 4,
  "Awareness": 15,
  "Reactions": 14,
  "Ball Control": 16,
  "Dribbling": 14,
  "Composure": 10,
  "Heading": 14,
  "Marking": 13,
  "Tackling": 9,
  "Strength": 18,
  "Aggression": 6
}, {
  "Acceleration": 15,
  "Sprint Speed": 14,
  "Finishing": 16,
  "Long Shot": 18,
  "Shot Power": 15,
  "Positioning": 15,
  "Crossing": 8,
  "Short Passing": 18,
  "Long Passing": 5,
  "Free Kick": 4,
  "Awareness": 16,
  "Reactions": 14,
  "Ball Control": 16,
  "Dribbling": 15,
  "Composure": 10,
  "Heading": 15,
  "Marking": 13,
  "Tackling": 10,
  "Strength": 19,
  "Aggression": 7
}, {
  "Acceleration": 16,
  "Sprint Speed": 14,
  "Finishing": 16,
  "Long Shot": 18,
  "Shot Power": 16,
  "Positioning": 15,
  "Crossing": 9,
  "Short Passing": 18,
  "Long Passing": 6,
  "Free Kick": 4,
  "Awareness": 17,
  "Reactions": 15,
  "Ball Control": 17,
  "Dribbling": 16,
  "Composure": 11,
  "Heading": 15,
  "Marking": 14,
  "Tackling": 11,
  "Strength": 19,
  "Aggression": 7
}, {
  "Acceleration": 16,
  "Sprint Speed": 15,
  "Finishing": 17,
  "Long Shot": 19,
  "Shot Power": 17,
  "Positioning": 15,
  "Crossing": 9,
  "Short Passing": 19,
  "Long Passing": 6,
  "Free Kick": 4,
  "Awareness": 18,
  "Reactions": 15,
  "Ball Control": 17,
  "Dribbling": 16,
  "Composure": 12,
  "Heading": 15,
  "Marking": 15,
  "Tackling": 12,
  "Strength": 20,
  "Aggression": 7
}, {
  "Acceleration": 16,
  "Sprint Speed": 15,
  "Finishing": 18,
  "Long Shot": 19,
  "Shot Power": 17,
  "Positioning": 16,
  "Crossing": 9,
  "Short Passing": 19,
  "Long Passing": 6,
  "Free Kick": 4,
  "Awareness": 19,
  "Reactions": 16,
  "Ball Control": 18,
  "Dribbling": 17,
  "Composure": 13,
  "Heading": 16,
  "Marking": 15,
  "Tackling": 12,
  "Strength": 21,
  "Aggression": 8
}, {
  "Acceleration": 17,
  "Sprint Speed": 15,
  "Finishing": 19,
  "Long Shot": 20,
  "Shot Power": 18,
  "Positioning": 16,
  "Crossing": 10,
  "Short Passing": 20,
  "Long Passing": 7,
  "Free Kick": 4,
  "Awareness": 19,
  "Reactions": 16,
  "Ball Control": 19,
  "Dribbling": 17,
  "Composure": 13,
  "Heading": 16,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 22,
  "Aggression": 8
}, {
  "Acceleration": 20,
  "Sprint Speed": 18,
  "Finishing": 22,
  "Long Shot": 23,
  "Shot Power": 21,
  "Positioning": 19,
  "Crossing": 10,
  "Short Passing": 23,
  "Long Passing": 7,
  "Free Kick": 4,
  "Awareness": 22,
  "Reactions": 19,
  "Ball Control": 22,
  "Dribbling": 20,
  "Composure": 13,
  "Heading": 19,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 25,
  "Aggression": 8
}, {
  "Acceleration": 21,
  "Sprint Speed": 18,
  "Finishing": 22,
  "Long Shot": 24,
  "Shot Power": 22,
  "Positioning": 20,
  "Crossing": 11,
  "Short Passing": 24,
  "Long Passing": 7,
  "Free Kick": 4,
  "Awareness": 23,
  "Reactions": 20,
  "Ball Control": 23,
  "Dribbling": 20,
  "Composure": 14,
  "Heading": 20,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 25,
  "Aggression": 8
}, {
  "Acceleration": 22,
  "Sprint Speed": 19,
  "Finishing": 23,
  "Long Shot": 25,
  "Shot Power": 23,
  "Positioning": 20,
  "Crossing": 11,
  "Short Passing": 25,
  "Long Passing": 8,
  "Free Kick": 5,
  "Awareness": 23,
  "Reactions": 20,
  "Ball Control": 24,
  "Dribbling": 21,
  "Composure": 14,
  "Heading": 20,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 25,
  "Aggression": 9
}, {
  "Acceleration": 23,
  "Sprint Speed": 20,
  "Finishing": 24,
  "Long Shot": 26,
  "Shot Power": 24,
  "Positioning": 21,
  "Crossing": 11,
  "Short Passing": 26,
  "Long Passing": 8,
  "Free Kick": 5,
  "Awareness": 23,
  "Reactions": 21,
  "Ball Control": 25,
  "Dribbling": 22,
  "Composure": 14,
  "Heading": 20,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 26,
  "Aggression": 9
}, {
  "Acceleration": 24,
  "Sprint Speed": 20,
  "Finishing": 25,
  "Long Shot": 27,
  "Shot Power": 24,
  "Positioning": 22,
  "Crossing": 11,
  "Short Passing": 27,
  "Long Passing": 8,
  "Free Kick": 5,
  "Awareness": 24,
  "Reactions": 21,
  "Ball Control": 26,
  "Dribbling": 23,
  "Composure": 15,
  "Heading": 21,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 27,
  "Aggression": 9
}, {
  "Acceleration": 25,
  "Sprint Speed": 20,
  "Finishing": 25,
  "Long Shot": 28,
  "Shot Power": 25,
  "Positioning": 23,
  "Crossing": 11,
  "Short Passing": 28,
  "Long Passing": 9,
  "Free Kick": 6,
  "Awareness": 24,
  "Reactions": 22,
  "Ball Control": 27,
  "Dribbling": 23,
  "Composure": 16,
  "Heading": 21,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 27,
  "Aggression": 10
}, {
  "Acceleration": 26,
  "Sprint Speed": 21,
  "Finishing": 26,
  "Long Shot": 29,
  "Shot Power": 25,
  "Positioning": 23,
  "Crossing": 12,
  "Short Passing": 29,
  "Long Passing": 10,
  "Free Kick": 6,
  "Awareness": 25,
  "Reactions": 22,
  "Ball Control": 28,
  "Dribbling": 24,
  "Composure": 16,
  "Heading": 21,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 28,
  "Aggression": 10
}, {
  "Acceleration": 26,
  "Sprint Speed": 22,
  "Finishing": 27,
  "Long Shot": 30,
  "Shot Power": 26,
  "Positioning": 23,
  "Crossing": 13,
  "Short Passing": 30,
  "Long Passing": 10,
  "Free Kick": 6,
  "Awareness": 26,
  "Reactions": 23,
  "Ball Control": 29,
  "Dribbling": 24,
  "Composure": 17,
  "Heading": 22,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 28,
  "Aggression": 10
}, {
  "Acceleration": 27,
  "Sprint Speed": 23,
  "Finishing": 27,
  "Long Shot": 31,
  "Shot Power": 27,
  "Positioning": 23,
  "Crossing": 13,
  "Short Passing": 31,
  "Long Passing": 10,
  "Free Kick": 7,
  "Awareness": 26,
  "Reactions": 24,
  "Ball Control": 30,
  "Dribbling": 25,
  "Composure": 17,
  "Heading": 23,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 29,
  "Aggression": 10
}, {
  "Acceleration": 27,
  "Sprint Speed": 23,
  "Finishing": 28,
  "Long Shot": 32,
  "Shot Power": 27,
  "Positioning": 24,
  "Crossing": 14,
  "Short Passing": 32,
  "Long Passing": 11,
  "Free Kick": 8,
  "Awareness": 27,
  "Reactions": 24,
  "Ball Control": 31,
  "Dribbling": 25,
  "Composure": 18,
  "Heading": 23,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 30,
  "Aggression": 10
}, {
  "Acceleration": 30,
  "Sprint Speed": 26,
  "Finishing": 31,
  "Long Shot": 32,
  "Shot Power": 32,
  "Positioning": 29,
  "Crossing": 14,
  "Short Passing": 33,
  "Long Passing": 11,
  "Free Kick": 8,
  "Awareness": 27,
  "Reactions": 28,
  "Ball Control": 34,
  "Dribbling": 28,
  "Composure": 28,
  "Heading": 29,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 30,
  "Aggression": 10
}, {
  "Acceleration": 32,
  "Sprint Speed": 29,
  "Finishing": 35,
  "Long Shot": 32,
  "Shot Power": 37,
  "Positioning": 29,
  "Crossing": 17,
  "Short Passing": 37,
  "Long Passing": 16,
  "Free Kick": 8,
  "Awareness": 37,
  "Reactions": 33,
  "Ball Control": 34,
  "Dribbling": 31,
  "Composure": 28,
  "Heading": 29,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 34,
  "Aggression": 10
}, {
  "Acceleration": 36,
  "Sprint Speed": 33,
  "Finishing": 39,
  "Long Shot": 37,
  "Shot Power": 37,
  "Positioning": 36,
  "Crossing": 17,
  "Short Passing": 40,
  "Long Passing": 16,
  "Free Kick": 8,
  "Awareness": 37,
  "Reactions": 36,
  "Ball Control": 38,
  "Dribbling": 35,
  "Composure": 28,
  "Heading": 33,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 37,
  "Aggression": 10
}, {
  "Acceleration": 39,
  "Sprint Speed": 36,
  "Finishing": 42,
  "Long Shot": 37,
  "Shot Power": 42,
  "Positioning": 36,
  "Crossing": 20,
  "Short Passing": 40,
  "Long Passing": 16,
  "Free Kick": 18,
  "Awareness": 41,
  "Reactions": 40,
  "Ball Control": 41,
  "Dribbling": 38,
  "Composure": 28,
  "Heading": 33,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 37,
  "Aggression": 15
}, {
  "Acceleration": 41,
  "Sprint Speed": 40,
  "Finishing": 47,
  "Long Shot": 37,
  "Shot Power": 42,
  "Positioning": 41,
  "Crossing": 20,
  "Short Passing": 44,
  "Long Passing": 21,
  "Free Kick": 18,
  "Awareness": 41,
  "Reactions": 43,
  "Ball Control": 44,
  "Dribbling": 42,
  "Composure": 28,
  "Heading": 37,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 42,
  "Aggression": 15
}, {
  "Acceleration": 45,
  "Sprint Speed": 44,
  "Finishing": 50,
  "Long Shot": 42,
  "Shot Power": 42,
  "Positioning": 41,
  "Crossing": 23,
  "Short Passing": 48,
  "Long Passing": 21,
  "Free Kick": 18,
  "Awareness": 44,
  "Reactions": 46,
  "Ball Control": 44,
  "Dribbling": 46,
  "Composure": 38,
  "Heading": 37,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 42,
  "Aggression": 20
}, {
  "Acceleration": 48,
  "Sprint Speed": 47,
  "Finishing": 54,
  "Long Shot": 48,
  "Shot Power": 47,
  "Positioning": 47,
  "Crossing": 23,
  "Short Passing": 48,
  "Long Passing": 21,
  "Free Kick": 18,
  "Awareness": 48,
  "Reactions": 49,
  "Ball Control": 44,
  "Dribbling": 49,
  "Composure": 38,
  "Heading": 43,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 47,
  "Aggression": 20
}, {
  "Acceleration": 51,
  "Sprint Speed": 50,
  "Finishing": 59,
  "Long Shot": 53,
  "Shot Power": 47,
  "Positioning": 47,
  "Crossing": 26,
  "Short Passing": 51,
  "Long Passing": 26,
  "Free Kick": 18,
  "Awareness": 48,
  "Reactions": 52,
  "Ball Control": 48,
  "Dribbling": 53,
  "Composure": 38,
  "Heading": 43,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 47,
  "Aggression": 25
}, {
  "Acceleration": 55,
  "Sprint Speed": 54,
  "Finishing": 63,
  "Long Shot": 53,
  "Shot Power": 52,
  "Positioning": 52,
  "Crossing": 26,
  "Short Passing": 51,
  "Long Passing": 26,
  "Free Kick": 18,
  "Awareness": 53,
  "Reactions": 55,
  "Ball Control": 53,
  "Dribbling": 57,
  "Composure": 38,
  "Heading": 46,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 51,
  "Aggression": 25
}, {
  "Acceleration": 58,
  "Sprint Speed": 57,
  "Finishing": 66,
  "Long Shot": 59,
  "Shot Power": 57,
  "Positioning": 52,
  "Crossing": 29,
  "Short Passing": 54,
  "Long Passing": 26,
  "Free Kick": 18,
  "Awareness": 53,
  "Reactions": 58,
  "Ball Control": 56,
  "Dribbling": 60,
  "Composure": 38,
  "Heading": 46,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 55,
  "Aggression": 25
}, {
  "Acceleration": 63,
  "Sprint Speed": 62,
  "Finishing": 69,
  "Long Shot": 59,
  "Shot Power": 62,
  "Positioning": 59,
  "Crossing": 29,
  "Short Passing": 59,
  "Long Passing": 26,
  "Free Kick": 18,
  "Awareness": 53,
  "Reactions": 63,
  "Ball Control": 61,
  "Dribbling": 65,
  "Composure": 38,
  "Heading": 54,
  "Marking": 16,
  "Tackling": 12,
  "Strength": 60,
  "Aggression": 30
}]