export default [{
  "Acceleration": 0,
  "Sprint Speed": 1,
  "Finishing": 0,
  "Long Shot": 1,
  "Shot Power": 0,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 0,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 0,
  "Heading": 0,
  "Marking": 1,
  "Tackling": 0,
  "Strength": 0,
  "Aggression": 0
}, {
  "Acceleration": 1,
  "Sprint Speed": 2,
  "Finishing": 0,
  "Long Shot": 1,
  "Shot Power": 1,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 0,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 2,
  "Reactions": 2,
  "Ball Control": 1,
  "Dribbling": 2,
  "Composure": 1,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 0,
  "Strength": 1,
  "Aggression": 0
}, {
  "Acceleration": 1,
  "Sprint Speed": 3,
  "Finishing": 0,
  "Long Shot": 1,
  "Shot Power": 1,
  "Positioning": 2,
  "Crossing": 2,
  "Short Passing": 1,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 2,
  "Reactions": 2,
  "Ball Control": 2,
  "Dribbling": 3,
  "Composure": 1,
  "Heading": 2,
  "Marking": 1,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 3,
  "Finishing": 0,
  "Long Shot": 2,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 2,
  "Short Passing": 1,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 3,
  "Reactions": 3,
  "Ball Control": 2,
  "Dribbling": 3,
  "Composure": 2,
  "Heading": 2,
  "Marking": 2,
  "Tackling": 2,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 4,
  "Finishing": 0,
  "Long Shot": 2,
  "Shot Power": 2,
  "Positioning": 4,
  "Crossing": 3,
  "Short Passing": 1,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 3,
  "Reactions": 3,
  "Ball Control": 3,
  "Dribbling": 4,
  "Composure": 2,
  "Heading": 3,
  "Marking": 2,
  "Tackling": 3,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 2,
  "Sprint Speed": 4,
  "Finishing": 1,
  "Long Shot": 3,
  "Shot Power": 2,
  "Positioning": 5,
  "Crossing": 3,
  "Short Passing": 2,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 4,
  "Reactions": 4,
  "Ball Control": 3,
  "Dribbling": 4,
  "Composure": 2,
  "Heading": 3,
  "Marking": 3,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 3,
  "Sprint Speed": 5,
  "Finishing": 1,
  "Long Shot": 4,
  "Shot Power": 2,
  "Positioning": 5,
  "Crossing": 4,
  "Short Passing": 2,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 4,
  "Reactions": 5,
  "Ball Control": 3,
  "Dribbling": 5,
  "Composure": 3,
  "Heading": 3,
  "Marking": 3,
  "Tackling": 5,
  "Strength": 3,
  "Aggression": 3
}, {
  "Acceleration": 4,
  "Sprint Speed": 6,
  "Finishing": 1,
  "Long Shot": 4,
  "Shot Power": 3,
  "Positioning": 6,
  "Crossing": 5,
  "Short Passing": 2,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 5,
  "Reactions": 5,
  "Ball Control": 3,
  "Dribbling": 5,
  "Composure": 3,
  "Heading": 4,
  "Marking": 3,
  "Tackling": 6,
  "Strength": 3,
  "Aggression": 3
}, {
  "Acceleration": 5,
  "Sprint Speed": 6,
  "Finishing": 2,
  "Long Shot": 4,
  "Shot Power": 3,
  "Positioning": 6,
  "Crossing": 5,
  "Short Passing": 3,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 5,
  "Reactions": 5,
  "Ball Control": 4,
  "Dribbling": 6,
  "Composure": 3,
  "Heading": 5,
  "Marking": 4,
  "Tackling": 6,
  "Strength": 4,
  "Aggression": 4
}, {
  "Acceleration": 5,
  "Sprint Speed": 6,
  "Finishing": 3,
  "Long Shot": 5,
  "Shot Power": 4,
  "Positioning": 7,
  "Crossing": 6,
  "Short Passing": 3,
  "Long Passing": 1,
  "Free Kick": 0,
  "Awareness": 6,
  "Reactions": 6,
  "Ball Control": 5,
  "Dribbling": 6,
  "Composure": 4,
  "Heading": 5,
  "Marking": 4,
  "Tackling": 6,
  "Strength": 4,
  "Aggression": 4
}, {
  "Acceleration": 6,
  "Sprint Speed": 7,
  "Finishing": 3,
  "Long Shot": 5,
  "Shot Power": 4,
  "Positioning": 7,
  "Crossing": 7,
  "Short Passing": 4,
  "Long Passing": 2,
  "Free Kick": 0,
  "Awareness": 6,
  "Reactions": 6,
  "Ball Control": 5,
  "Dribbling": 7,
  "Composure": 4,
  "Heading": 6,
  "Marking": 5,
  "Tackling": 6,
  "Strength": 5,
  "Aggression": 5
}, {
  "Acceleration": 7,
  "Sprint Speed": 8,
  "Finishing": 4,
  "Long Shot": 5,
  "Shot Power": 4,
  "Positioning": 8,
  "Crossing": 7,
  "Short Passing": 4,
  "Long Passing": 2,
  "Free Kick": 0,
  "Awareness": 7,
  "Reactions": 7,
  "Ball Control": 5,
  "Dribbling": 8,
  "Composure": 5,
  "Heading": 6,
  "Marking": 5,
  "Tackling": 7,
  "Strength": 5,
  "Aggression": 5
}, {
  "Acceleration": 10,
  "Sprint Speed": 11,
  "Finishing": 7,
  "Long Shot": 8,
  "Shot Power": 7,
  "Positioning": 11,
  "Crossing": 10,
  "Short Passing": 7,
  "Long Passing": 5,
  "Free Kick": 0,
  "Awareness": 10,
  "Reactions": 10,
  "Ball Control": 8,
  "Dribbling": 11,
  "Composure": 5,
  "Heading": 6,
  "Marking": 5,
  "Tackling": 7,
  "Strength": 5,
  "Aggression": 6
}, {
  "Acceleration": 11,
  "Sprint Speed": 12,
  "Finishing": 7,
  "Long Shot": 9,
  "Shot Power": 7,
  "Positioning": 11,
  "Crossing": 10,
  "Short Passing": 7,
  "Long Passing": 5,
  "Free Kick": 0,
  "Awareness": 10,
  "Reactions": 10,
  "Ball Control": 8,
  "Dribbling": 12,
  "Composure": 6,
  "Heading": 7,
  "Marking": 6,
  "Tackling": 8,
  "Strength": 6,
  "Aggression": 6
}, {
  "Acceleration": 11,
  "Sprint Speed": 12,
  "Finishing": 8,
  "Long Shot": 9,
  "Shot Power": 8,
  "Positioning": 11,
  "Crossing": 11,
  "Short Passing": 8,
  "Long Passing": 6,
  "Free Kick": 1,
  "Awareness": 11,
  "Reactions": 11,
  "Ball Control": 9,
  "Dribbling": 12,
  "Composure": 7,
  "Heading": 7,
  "Marking": 6,
  "Tackling": 9,
  "Strength": 6,
  "Aggression": 7
}, {
  "Acceleration": 12,
  "Sprint Speed": 13,
  "Finishing": 8,
  "Long Shot": 10,
  "Shot Power": 8,
  "Positioning": 12,
  "Crossing": 11,
  "Short Passing": 9,
  "Long Passing": 6,
  "Free Kick": 1,
  "Awareness": 11,
  "Reactions": 11,
  "Ball Control": 9,
  "Dribbling": 13,
  "Composure": 8,
  "Heading": 7,
  "Marking": 7,
  "Tackling": 9,
  "Strength": 7,
  "Aggression": 7
}, {
  "Acceleration": 12,
  "Sprint Speed": 13,
  "Finishing": 8,
  "Long Shot": 11,
  "Shot Power": 8,
  "Positioning": 13,
  "Crossing": 12,
  "Short Passing": 9,
  "Long Passing": 7,
  "Free Kick": 1,
  "Awareness": 12,
  "Reactions": 12,
  "Ball Control": 9,
  "Dribbling": 14,
  "Composure": 8,
  "Heading": 8,
  "Marking": 7,
  "Tackling": 10,
  "Strength": 7,
  "Aggression": 8
}, {
  "Acceleration": 13,
  "Sprint Speed": 14,
  "Finishing": 8,
  "Long Shot": 11,
  "Shot Power": 9,
  "Positioning": 13,
  "Crossing": 12,
  "Short Passing": 10,
  "Long Passing": 7,
  "Free Kick": 1,
  "Awareness": 12,
  "Reactions": 12,
  "Ball Control": 10,
  "Dribbling": 14,
  "Composure": 9,
  "Heading": 8,
  "Marking": 7,
  "Tackling": 11,
  "Strength": 8,
  "Aggression": 8
}, {
  "Acceleration": 13,
  "Sprint Speed": 15,
  "Finishing": 9,
  "Long Shot": 11,
  "Shot Power": 9,
  "Positioning": 14,
  "Crossing": 13,
  "Short Passing": 10,
  "Long Passing": 7,
  "Free Kick": 1,
  "Awareness": 12,
  "Reactions": 13,
  "Ball Control": 10,
  "Dribbling": 15,
  "Composure": 9,
  "Heading": 9,
  "Marking": 8,
  "Tackling": 12,
  "Strength": 8,
  "Aggression": 8
}, {
  "Acceleration": 14,
  "Sprint Speed": 15,
  "Finishing": 10,
  "Long Shot": 12,
  "Shot Power": 9,
  "Positioning": 14,
  "Crossing": 13,
  "Short Passing": 11,
  "Long Passing": 8,
  "Free Kick": 1,
  "Awareness": 13,
  "Reactions": 14,
  "Ball Control": 10,
  "Dribbling": 16,
  "Composure": 10,
  "Heading": 9,
  "Marking": 8,
  "Tackling": 12,
  "Strength": 8,
  "Aggression": 9
}, {
  "Acceleration": 14,
  "Sprint Speed": 16,
  "Finishing": 10,
  "Long Shot": 12,
  "Shot Power": 10,
  "Positioning": 15,
  "Crossing": 13,
  "Short Passing": 11,
  "Long Passing": 8,
  "Free Kick": 2,
  "Awareness": 13,
  "Reactions": 14,
  "Ball Control": 11,
  "Dribbling": 17,
  "Composure": 10,
  "Heading": 9,
  "Marking": 8,
  "Tackling": 13,
  "Strength": 9,
  "Aggression": 9
}, {
  "Acceleration": 14,
  "Sprint Speed": 16,
  "Finishing": 11,
  "Long Shot": 13,
  "Shot Power": 10,
  "Positioning": 15,
  "Crossing": 14,
  "Short Passing": 12,
  "Long Passing": 9,
  "Free Kick": 2,
  "Awareness": 14,
  "Reactions": 14,
  "Ball Control": 11,
  "Dribbling": 17,
  "Composure": 10,
  "Heading": 10,
  "Marking": 9,
  "Tackling": 13,
  "Strength": 9,
  "Aggression": 10
}, {
  "Acceleration": 17,
  "Sprint Speed": 19,
  "Finishing": 14,
  "Long Shot": 16,
  "Shot Power": 13,
  "Positioning": 18,
  "Crossing": 17,
  "Short Passing": 15,
  "Long Passing": 12,
  "Free Kick": 2,
  "Awareness": 17,
  "Reactions": 17,
  "Ball Control": 14,
  "Dribbling": 20,
  "Composure": 10,
  "Heading": 10,
  "Marking": 9,
  "Tackling": 13,
  "Strength": 9,
  "Aggression": 11
}, {
  "Acceleration": 18,
  "Sprint Speed": 19,
  "Finishing": 14,
  "Long Shot": 16,
  "Shot Power": 13,
  "Positioning": 18,
  "Crossing": 18,
  "Short Passing": 16,
  "Long Passing": 13,
  "Free Kick": 2,
  "Awareness": 18,
  "Reactions": 18,
  "Ball Control": 15,
  "Dribbling": 21,
  "Composure": 11,
  "Heading": 10,
  "Marking": 9,
  "Tackling": 13,
  "Strength": 9,
  "Aggression": 12
}, {
  "Acceleration": 18,
  "Sprint Speed": 20,
  "Finishing": 15,
  "Long Shot": 17,
  "Shot Power": 13,
  "Positioning": 18,
  "Crossing": 18,
  "Short Passing": 17,
  "Long Passing": 14,
  "Free Kick": 2,
  "Awareness": 18,
  "Reactions": 18,
  "Ball Control": 15,
  "Dribbling": 21,
  "Composure": 11,
  "Heading": 11,
  "Marking": 10,
  "Tackling": 14,
  "Strength": 10,
  "Aggression": 12
}, {
  "Acceleration": 19,
  "Sprint Speed": 21,
  "Finishing": 15,
  "Long Shot": 17,
  "Shot Power": 14,
  "Positioning": 19,
  "Crossing": 18,
  "Short Passing": 17,
  "Long Passing": 14,
  "Free Kick": 2,
  "Awareness": 19,
  "Reactions": 19,
  "Ball Control": 16,
  "Dribbling": 22,
  "Composure": 12,
  "Heading": 11,
  "Marking": 10,
  "Tackling": 14,
  "Strength": 10,
  "Aggression": 13
}, {
  "Acceleration": 20,
  "Sprint Speed": 22,
  "Finishing": 16,
  "Long Shot": 18,
  "Shot Power": 14,
  "Positioning": 19,
  "Crossing": 18,
  "Short Passing": 18,
  "Long Passing": 15,
  "Free Kick": 2,
  "Awareness": 19,
  "Reactions": 19,
  "Ball Control": 16,
  "Dribbling": 22,
  "Composure": 13,
  "Heading": 11,
  "Marking": 11,
  "Tackling": 15,
  "Strength": 11,
  "Aggression": 13
}, {
  "Acceleration": 20,
  "Sprint Speed": 22,
  "Finishing": 17,
  "Long Shot": 19,
  "Shot Power": 14,
  "Positioning": 20,
  "Crossing": 19,
  "Short Passing": 19,
  "Long Passing": 15,
  "Free Kick": 3,
  "Awareness": 20,
  "Reactions": 20,
  "Ball Control": 16,
  "Dribbling": 23,
  "Composure": 14,
  "Heading": 12,
  "Marking": 11,
  "Tackling": 15,
  "Strength": 11,
  "Aggression": 13
}, {
  "Acceleration": 21,
  "Sprint Speed": 22,
  "Finishing": 18,
  "Long Shot": 19,
  "Shot Power": 15,
  "Positioning": 21,
  "Crossing": 20,
  "Short Passing": 19,
  "Long Passing": 16,
  "Free Kick": 3,
  "Awareness": 20,
  "Reactions": 20,
  "Ball Control": 17,
  "Dribbling": 23,
  "Composure": 14,
  "Heading": 12,
  "Marking": 11,
  "Tackling": 16,
  "Strength": 12,
  "Aggression": 14
}, {
  "Acceleration": 22,
  "Sprint Speed": 23,
  "Finishing": 18,
  "Long Shot": 20,
  "Shot Power": 15,
  "Positioning": 21,
  "Crossing": 20,
  "Short Passing": 20,
  "Long Passing": 16,
  "Free Kick": 3,
  "Awareness": 21,
  "Reactions": 21,
  "Ball Control": 17,
  "Dribbling": 24,
  "Composure": 15,
  "Heading": 13,
  "Marking": 12,
  "Tackling": 16,
  "Strength": 12,
  "Aggression": 14
}, {
  "Acceleration": 22,
  "Sprint Speed": 23,
  "Finishing": 19,
  "Long Shot": 20,
  "Shot Power": 15,
  "Positioning": 22,
  "Crossing": 21,
  "Short Passing": 20,
  "Long Passing": 17,
  "Free Kick": 4,
  "Awareness": 21,
  "Reactions": 21,
  "Ball Control": 18,
  "Dribbling": 24,
  "Composure": 16,
  "Heading": 13,
  "Marking": 12,
  "Tackling": 17,
  "Strength": 13,
  "Aggression": 15
}, {
  "Acceleration": 23,
  "Sprint Speed": 24,
  "Finishing": 19,
  "Long Shot": 20,
  "Shot Power": 16,
  "Positioning": 23,
  "Crossing": 22,
  "Short Passing": 21,
  "Long Passing": 17,
  "Free Kick": 4,
  "Awareness": 22,
  "Reactions": 22,
  "Ball Control": 18,
  "Dribbling": 25,
  "Composure": 17,
  "Heading": 13,
  "Marking": 12,
  "Tackling": 17,
  "Strength": 13,
  "Aggression": 15
}, {
  "Acceleration": 26,
  "Sprint Speed": 27,
  "Finishing": 22,
  "Long Shot": 23,
  "Shot Power": 19,
  "Positioning": 26,
  "Crossing": 25,
  "Short Passing": 24,
  "Long Passing": 20,
  "Free Kick": 4,
  "Awareness": 25,
  "Reactions": 25,
  "Ball Control": 21,
  "Dribbling": 28,
  "Composure": 17,
  "Heading": 13,
  "Marking": 12,
  "Tackling": 17,
  "Strength": 13,
  "Aggression": 16
}, {
  "Acceleration": 27,
  "Sprint Speed": 28,
  "Finishing": 22,
  "Long Shot": 24,
  "Shot Power": 19,
  "Positioning": 26,
  "Crossing": 26,
  "Short Passing": 25,
  "Long Passing": 20,
  "Free Kick": 5,
  "Awareness": 25,
  "Reactions": 26,
  "Ball Control": 21,
  "Dribbling": 29,
  "Composure": 18,
  "Heading": 13,
  "Marking": 13,
  "Tackling": 18,
  "Strength": 13,
  "Aggression": 16
}, {
  "Acceleration": 27,
  "Sprint Speed": 28,
  "Finishing": 23,
  "Long Shot": 24,
  "Shot Power": 20,
  "Positioning": 27,
  "Crossing": 27,
  "Short Passing": 25,
  "Long Passing": 21,
  "Free Kick": 5,
  "Awareness": 26,
  "Reactions": 26,
  "Ball Control": 22,
  "Dribbling": 30,
  "Composure": 18,
  "Heading": 13,
  "Marking": 14,
  "Tackling": 18,
  "Strength": 13,
  "Aggression": 17
}, {
  "Acceleration": 28,
  "Sprint Speed": 29,
  "Finishing": 24,
  "Long Shot": 25,
  "Shot Power": 20,
  "Positioning": 27,
  "Crossing": 28,
  "Short Passing": 25,
  "Long Passing": 21,
  "Free Kick": 6,
  "Awareness": 26,
  "Reactions": 27,
  "Ball Control": 22,
  "Dribbling": 30,
  "Composure": 19,
  "Heading": 14,
  "Marking": 14,
  "Tackling": 19,
  "Strength": 14,
  "Aggression": 17
}, {
  "Acceleration": 29,
  "Sprint Speed": 29,
  "Finishing": 25,
  "Long Shot": 25,
  "Shot Power": 20,
  "Positioning": 27,
  "Crossing": 29,
  "Short Passing": 26,
  "Long Passing": 22,
  "Free Kick": 6,
  "Awareness": 27,
  "Reactions": 27,
  "Ball Control": 23,
  "Dribbling": 31,
  "Composure": 19,
  "Heading": 14,
  "Marking": 15,
  "Tackling": 19,
  "Strength": 14,
  "Aggression": 18
}, {
  "Acceleration": 29,
  "Sprint Speed": 30,
  "Finishing": 25,
  "Long Shot": 26,
  "Shot Power": 21,
  "Positioning": 29,
  "Crossing": 30,
  "Short Passing": 26,
  "Long Passing": 22,
  "Free Kick": 7,
  "Awareness": 27,
  "Reactions": 28,
  "Ball Control": 23,
  "Dribbling": 32,
  "Composure": 20,
  "Heading": 14,
  "Marking": 15,
  "Tackling": 20,
  "Strength": 14,
  "Aggression": 18
}, {
  "Acceleration": 30,
  "Sprint Speed": 31,
  "Finishing": 26,
  "Long Shot": 26,
  "Shot Power": 21,
  "Positioning": 29,
  "Crossing": 31,
  "Short Passing": 27,
  "Long Passing": 22,
  "Free Kick": 7,
  "Awareness": 28,
  "Reactions": 28,
  "Ball Control": 24,
  "Dribbling": 33,
  "Composure": 20,
  "Heading": 15,
  "Marking": 16,
  "Tackling": 20,
  "Strength": 15,
  "Aggression": 18
}, {
  "Acceleration": 30,
  "Sprint Speed": 31,
  "Finishing": 27,
  "Long Shot": 27,
  "Shot Power": 21,
  "Positioning": 30,
  "Crossing": 32,
  "Short Passing": 28,
  "Long Passing": 22,
  "Free Kick": 8,
  "Awareness": 28,
  "Reactions": 29,
  "Ball Control": 24,
  "Dribbling": 33,
  "Composure": 21,
  "Heading": 15,
  "Marking": 16,
  "Tackling": 21,
  "Strength": 16,
  "Aggression": 19
}, {
  "Acceleration": 31,
  "Sprint Speed": 32,
  "Finishing": 27,
  "Long Shot": 27,
  "Shot Power": 22,
  "Positioning": 30,
  "Crossing": 33,
  "Short Passing": 28,
  "Long Passing": 23,
  "Free Kick": 8,
  "Awareness": 29,
  "Reactions": 29,
  "Ball Control": 25,
  "Dribbling": 34,
  "Composure": 21,
  "Heading": 15,
  "Marking": 17,
  "Tackling": 22,
  "Strength": 17,
  "Aggression": 19
}, {
  "Acceleration": 32,
  "Sprint Speed": 33,
  "Finishing": 28,
  "Long Shot": 28,
  "Shot Power": 22,
  "Positioning": 30,
  "Crossing": 34,
  "Short Passing": 29,
  "Long Passing": 23,
  "Free Kick": 10,
  "Awareness": 29,
  "Reactions": 30,
  "Ball Control": 25,
  "Dribbling": 35,
  "Composure": 21,
  "Heading": 16,
  "Marking": 17,
  "Tackling": 23,
  "Strength": 17,
  "Aggression": 20
}, {
  "Acceleration": 34,
  "Sprint Speed": 36,
  "Finishing": 31,
  "Long Shot": 28,
  "Shot Power": 22,
  "Positioning": 34,
  "Crossing": 37,
  "Short Passing": 29,
  "Long Passing": 26,
  "Free Kick": 10,
  "Awareness": 36,
  "Reactions": 34,
  "Ball Control": 29,
  "Dribbling": 38,
  "Composure": 36,
  "Heading": 16,
  "Marking": 17,
  "Tackling": 23,
  "Strength": 17,
  "Aggression": 20
}, {
  "Acceleration": 37,
  "Sprint Speed": 39,
  "Finishing": 31,
  "Long Shot": 31,
  "Shot Power": 22,
  "Positioning": 34,
  "Crossing": 40,
  "Short Passing": 32,
  "Long Passing": 29,
  "Free Kick": 10,
  "Awareness": 40,
  "Reactions": 34,
  "Ball Control": 32,
  "Dribbling": 38,
  "Composure": 36,
  "Heading": 21,
  "Marking": 22,
  "Tackling": 28,
  "Strength": 17,
  "Aggression": 25
}, {
  "Acceleration": 41,
  "Sprint Speed": 41,
  "Finishing": 35,
  "Long Shot": 31,
  "Shot Power": 30,
  "Positioning": 37,
  "Crossing": 42,
  "Short Passing": 33,
  "Long Passing": 32,
  "Free Kick": 20,
  "Awareness": 40,
  "Reactions": 39,
  "Ball Control": 36,
  "Dribbling": 42,
  "Composure": 36,
  "Heading": 21,
  "Marking": 22,
  "Tackling": 28,
  "Strength": 17,
  "Aggression": 25
}, {
  "Acceleration": 44,
  "Sprint Speed": 45,
  "Finishing": 35,
  "Long Shot": 34,
  "Shot Power": 30,
  "Positioning": 41,
  "Crossing": 44,
  "Short Passing": 36,
  "Long Passing": 35,
  "Free Kick": 20,
  "Awareness": 43,
  "Reactions": 44,
  "Ball Control": 39,
  "Dribbling": 42,
  "Composure": 36,
  "Heading": 21,
  "Marking": 27,
  "Tackling": 28,
  "Strength": 20,
  "Aggression": 25
}, {
  "Acceleration": 46,
  "Sprint Speed": 47,
  "Finishing": 38,
  "Long Shot": 38,
  "Shot Power": 30,
  "Positioning": 47,
  "Crossing": 47,
  "Short Passing": 40,
  "Long Passing": 38,
  "Free Kick": 20,
  "Awareness": 43,
  "Reactions": 44,
  "Ball Control": 42,
  "Dribbling": 46,
  "Composure": 41,
  "Heading": 21,
  "Marking": 27,
  "Tackling": 28,
  "Strength": 20,
  "Aggression": 30
}, {
  "Acceleration": 50,
  "Sprint Speed": 49,
  "Finishing": 41,
  "Long Shot": 38,
  "Shot Power": 30,
  "Positioning": 50,
  "Crossing": 49,
  "Short Passing": 43,
  "Long Passing": 41,
  "Free Kick": 20,
  "Awareness": 49,
  "Reactions": 48,
  "Ball Control": 46,
  "Dribbling": 49,
  "Composure": 41,
  "Heading": 21,
  "Marking": 27,
  "Tackling": 28,
  "Strength": 23,
  "Aggression": 30
}, {
  "Acceleration": 52,
  "Sprint Speed": 52,
  "Finishing": 45,
  "Long Shot": 43,
  "Shot Power": 38,
  "Positioning": 50,
  "Crossing": 51,
  "Short Passing": 48,
  "Long Passing": 44,
  "Free Kick": 20,
  "Awareness": 49,
  "Reactions": 48,
  "Ball Control": 49,
  "Dribbling": 54,
  "Composure": 41,
  "Heading": 21,
  "Marking": 32,
  "Tackling": 33,
  "Strength": 23,
  "Aggression": 30
}, {
  "Acceleration": 55,
  "Sprint Speed": 56,
  "Finishing": 49,
  "Long Shot": 43,
  "Shot Power": 38,
  "Positioning": 53,
  "Crossing": 54,
  "Short Passing": 52,
  "Long Passing": 47,
  "Free Kick": 20,
  "Awareness": 52,
  "Reactions": 51,
  "Ball Control": 54,
  "Dribbling": 54,
  "Composure": 41,
  "Heading": 26,
  "Marking": 37,
  "Tackling": 33,
  "Strength": 23,
  "Aggression": 30
}, {
  "Acceleration": 59,
  "Sprint Speed": 58,
  "Finishing": 52,
  "Long Shot": 47,
  "Shot Power": 38,
  "Positioning": 53,
  "Crossing": 56,
  "Short Passing": 56,
  "Long Passing": 50,
  "Free Kick": 20,
  "Awareness": 52,
  "Reactions": 56,
  "Ball Control": 57,
  "Dribbling": 57,
  "Composure": 46,
  "Heading": 26,
  "Marking": 37,
  "Tackling": 33,
  "Strength": 26,
  "Aggression": 30
}, {
  "Acceleration": 62,
  "Sprint Speed": 61,
  "Finishing": 52,
  "Long Shot": 50,
  "Shot Power": 38,
  "Positioning": 56,
  "Crossing": 59,
  "Short Passing": 59,
  "Long Passing": 53,
  "Free Kick": 20,
  "Awareness": 56,
  "Reactions": 59,
  "Ball Control": 60,
  "Dribbling": 59,
  "Composure": 46,
  "Heading": 26,
  "Marking": 37,
  "Tackling": 33,
  "Strength": 29,
  "Aggression": 30
}, {
  "Acceleration": 67,
  "Sprint Speed": 66,
  "Finishing": 57,
  "Long Shot": 55,
  "Shot Power": 46,
  "Positioning": 63,
  "Crossing": 64,
  "Short Passing": 64,
  "Long Passing": 58,
  "Free Kick": 20,
  "Awareness": 56,
  "Reactions": 64,
  "Ball Control": 65,
  "Dribbling": 64,
  "Composure": 46,
  "Heading": 26,
  "Marking": 37,
  "Tackling": 33,
  "Strength": 29,
  "Aggression": 30
}]