export default [{
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 1,
  "Positioning": 0,
  "Crossing": 0,
  "Short Passing": 0,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 0,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 0,
  "Heading": 1,
  "Marking": 0,
  "Tackling": 2,
  "Strength": 0,
  "Aggression": 0
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 0,
  "Long Shot": 1,
  "Shot Power": 1,
  "Positioning": 1,
  "Crossing": 0,
  "Short Passing": 0,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 0,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 1,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 2,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 0,
  "Long Shot": 1,
  "Shot Power": 2,
  "Positioning": 1,
  "Crossing": 0,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 2,
  "Awareness": 0,
  "Reactions": 2,
  "Ball Control": 2,
  "Dribbling": 0,
  "Composure": 2,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 2,
  "Strength": 2,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 1,
  "Long Shot": 1,
  "Shot Power": 2,
  "Positioning": 2,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 2,
  "Free Kick": 2,
  "Awareness": 0,
  "Reactions": 2,
  "Ball Control": 2,
  "Dribbling": 0,
  "Composure": 3,
  "Heading": 2,
  "Marking": 2,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 1,
  "Long Shot": 2,
  "Shot Power": 2,
  "Positioning": 2,
  "Crossing": 1,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 2,
  "Awareness": 2,
  "Reactions": 2,
  "Ball Control": 2,
  "Dribbling": 1,
  "Composure": 3,
  "Heading": 3,
  "Marking": 3,
  "Tackling": 4,
  "Strength": 3,
  "Aggression": 2
}, {
  "Acceleration": 2,
  "Sprint Speed": 3,
  "Finishing": 1,
  "Long Shot": 2,
  "Shot Power": 3,
  "Positioning": 3,
  "Crossing": 1,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 3,
  "Awareness": 2,
  "Reactions": 3,
  "Ball Control": 3,
  "Dribbling": 1,
  "Composure": 4,
  "Heading": 3,
  "Marking": 3,
  "Tackling": 4,
  "Strength": 4,
  "Aggression": 2
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 2,
  "Long Shot": 2,
  "Shot Power": 3,
  "Positioning": 3,
  "Crossing": 1,
  "Short Passing": 3,
  "Long Passing": 3,
  "Free Kick": 3,
  "Awareness": 2,
  "Reactions": 3,
  "Ball Control": 3,
  "Dribbling": 2,
  "Composure": 4,
  "Heading": 4,
  "Marking": 4,
  "Tackling": 6,
  "Strength": 4,
  "Aggression": 2
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 2,
  "Long Shot": 3,
  "Shot Power": 3,
  "Positioning": 4,
  "Crossing": 2,
  "Short Passing": 3,
  "Long Passing": 3,
  "Free Kick": 3,
  "Awareness": 2,
  "Reactions": 4,
  "Ball Control": 3,
  "Dribbling": 2,
  "Composure": 5,
  "Heading": 4,
  "Marking": 4,
  "Tackling": 10,
  "Strength": 4,
  "Aggression": 3
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 2,
  "Long Shot": 3,
  "Shot Power": 4,
  "Positioning": 5,
  "Crossing": 2,
  "Short Passing": 4,
  "Long Passing": 3,
  "Free Kick": 4,
  "Awareness": 2,
  "Reactions": 4,
  "Ball Control": 4,
  "Dribbling": 3,
  "Composure": 6,
  "Heading": 4,
  "Marking": 5,
  "Tackling": 10,
  "Strength": 4,
  "Aggression": 3
}, {
  "Acceleration": 4,
  "Sprint Speed": 4,
  "Finishing": 3,
  "Long Shot": 4,
  "Shot Power": 5,
  "Positioning": 5,
  "Crossing": 2,
  "Short Passing": 4,
  "Long Passing": 4,
  "Free Kick": 4,
  "Awareness": 2,
  "Reactions": 4,
  "Ball Control": 4,
  "Dribbling": 3,
  "Composure": 7,
  "Heading": 5,
  "Marking": 5,
  "Tackling": 10,
  "Strength": 4,
  "Aggression": 3
}, {
  "Acceleration": 4,
  "Sprint Speed": 4,
  "Finishing": 3,
  "Long Shot": 4,
  "Shot Power": 6,
  "Positioning": 5,
  "Crossing": 2,
  "Short Passing": 5,
  "Long Passing": 4,
  "Free Kick": 4,
  "Awareness": 2,
  "Reactions": 5,
  "Ball Control": 4,
  "Dribbling": 4,
  "Composure": 7,
  "Heading": 6,
  "Marking": 6,
  "Tackling": 14,
  "Strength": 4,
  "Aggression": 4
}, {
  "Acceleration": 4,
  "Sprint Speed": 4,
  "Finishing": 4,
  "Long Shot": 5,
  "Shot Power": 7,
  "Positioning": 6,
  "Crossing": 2,
  "Short Passing": 5,
  "Long Passing": 4,
  "Free Kick": 4,
  "Awareness": 2,
  "Reactions": 6,
  "Ball Control": 5,
  "Dribbling": 4,
  "Composure": 8,
  "Heading": 6,
  "Marking": 6,
  "Tackling": 14,
  "Strength": 5,
  "Aggression": 4
}, {
  "Acceleration": 5,
  "Sprint Speed": 5,
  "Finishing": 4,
  "Long Shot": 5,
  "Shot Power": 7,
  "Positioning": 6,
  "Crossing": 3,
  "Short Passing": 5,
  "Long Passing": 5,
  "Free Kick": 4,
  "Awareness": 2,
  "Reactions": 6,
  "Ball Control": 5,
  "Dribbling": 5,
  "Composure": 9,
  "Heading": 7,
  "Marking": 6,
  "Tackling": 19,
  "Strength": 6,
  "Aggression": 4
}, {
  "Acceleration": 5,
  "Sprint Speed": 5,
  "Finishing": 4,
  "Long Shot": 7,
  "Shot Power": 8,
  "Positioning": 7,
  "Crossing": 3,
  "Short Passing": 6,
  "Long Passing": 5,
  "Free Kick": 5,
  "Awareness": 2,
  "Reactions": 7,
  "Ball Control": 5,
  "Dribbling": 5,
  "Composure": 9,
  "Heading": 8,
  "Marking": 6,
  "Tackling": 19,
  "Strength": 6,
  "Aggression": 5
}, {
  "Acceleration": 8,
  "Sprint Speed": 8,
  "Finishing": 7,
  "Long Shot": 10,
  "Shot Power": 11,
  "Positioning": 10,
  "Crossing": 3,
  "Short Passing": 9,
  "Long Passing": 5,
  "Free Kick": 5,
  "Awareness": 4,
  "Reactions": 10,
  "Ball Control": 8,
  "Dribbling": 8,
  "Composure": 9,
  "Heading": 11,
  "Marking": 6,
  "Tackling": 19,
  "Strength": 9,
  "Aggression": 8
}, {
  "Acceleration": 9,
  "Sprint Speed": 9,
  "Finishing": 7,
  "Long Shot": 11,
  "Shot Power": 11,
  "Positioning": 11,
  "Crossing": 3,
  "Short Passing": 9,
  "Long Passing": 6,
  "Free Kick": 5,
  "Awareness": 4,
  "Reactions": 11,
  "Ball Control": 8,
  "Dribbling": 8,
  "Composure": 10,
  "Heading": 13,
  "Marking": 7,
  "Tackling": 19,
  "Strength": 10,
  "Aggression": 8
}, {
  "Acceleration": 10,
  "Sprint Speed": 9,
  "Finishing": 7,
  "Long Shot": 13,
  "Shot Power": 11,
  "Positioning": 11,
  "Crossing": 3,
  "Short Passing": 10,
  "Long Passing": 6,
  "Free Kick": 6,
  "Awareness": 4,
  "Reactions": 12,
  "Ball Control": 8,
  "Dribbling": 9,
  "Composure": 11,
  "Heading": 14,
  "Marking": 7,
  "Tackling": 19,
  "Strength": 10,
  "Aggression": 9
}, {
  "Acceleration": 10,
  "Sprint Speed": 9,
  "Finishing": 8,
  "Long Shot": 13,
  "Shot Power": 12,
  "Positioning": 12,
  "Crossing": 4,
  "Short Passing": 10,
  "Long Passing": 6,
  "Free Kick": 7,
  "Awareness": 5,
  "Reactions": 12,
  "Ball Control": 9,
  "Dribbling": 9,
  "Composure": 12,
  "Heading": 14,
  "Marking": 7,
  "Tackling": 19,
  "Strength": 11,
  "Aggression": 9
}, {
  "Acceleration": 10,
  "Sprint Speed": 10,
  "Finishing": 8,
  "Long Shot": 14,
  "Shot Power": 13,
  "Positioning": 12,
  "Crossing": 4,
  "Short Passing": 10,
  "Long Passing": 7,
  "Free Kick": 7,
  "Awareness": 5,
  "Reactions": 12,
  "Ball Control": 10,
  "Dribbling": 9,
  "Composure": 13,
  "Heading": 15,
  "Marking": 8,
  "Tackling": 19,
  "Strength": 11,
  "Aggression": 9
}, {
  "Acceleration": 11,
  "Sprint Speed": 10,
  "Finishing": 8,
  "Long Shot": 14,
  "Shot Power": 14,
  "Positioning": 13,
  "Crossing": 4,
  "Short Passing": 11,
  "Long Passing": 7,
  "Free Kick": 7,
  "Awareness": 5,
  "Reactions": 13,
  "Ball Control": 11,
  "Dribbling": 10,
  "Composure": 14,
  "Heading": 15,
  "Marking": 8,
  "Tackling": 19,
  "Strength": 11,
  "Aggression": 10
}, {
  "Acceleration": 12,
  "Sprint Speed": 11,
  "Finishing": 9,
  "Long Shot": 14,
  "Shot Power": 15,
  "Positioning": 13,
  "Crossing": 5,
  "Short Passing": 11,
  "Long Passing": 7,
  "Free Kick": 7,
  "Awareness": 5,
  "Reactions": 13,
  "Ball Control": 12,
  "Dribbling": 10,
  "Composure": 15,
  "Heading": 15,
  "Marking": 9,
  "Tackling": 19,
  "Strength": 12,
  "Aggression": 10
}, {
  "Acceleration": 12,
  "Sprint Speed": 12,
  "Finishing": 9,
  "Long Shot": 15,
  "Shot Power": 16,
  "Positioning": 14,
  "Crossing": 6,
  "Short Passing": 11,
  "Long Passing": 7,
  "Free Kick": 8,
  "Awareness": 6,
  "Reactions": 13,
  "Ball Control": 12,
  "Dribbling": 10,
  "Composure": 16,
  "Heading": 16,
  "Marking": 9,
  "Tackling": 19,
  "Strength": 13,
  "Aggression": 10
}, {
  "Acceleration": 12,
  "Sprint Speed": 13,
  "Finishing": 10,
  "Long Shot": 15,
  "Shot Power": 16,
  "Positioning": 14,
  "Crossing": 7,
  "Short Passing": 12,
  "Long Passing": 8,
  "Free Kick": 9,
  "Awareness": 6,
  "Reactions": 13,
  "Ball Control": 12,
  "Dribbling": 11,
  "Composure": 16,
  "Heading": 16,
  "Marking": 9,
  "Tackling": 19,
  "Strength": 14,
  "Aggression": 11
}, {
  "Acceleration": 13,
  "Sprint Speed": 13,
  "Finishing": 11,
  "Long Shot": 16,
  "Shot Power": 16,
  "Positioning": 15,
  "Crossing": 7,
  "Short Passing": 12,
  "Long Passing": 8,
  "Free Kick": 9,
  "Awareness": 6,
  "Reactions": 14,
  "Ball Control": 13,
  "Dribbling": 11,
  "Composure": 17,
  "Heading": 17,
  "Marking": 9,
  "Tackling": 19,
  "Strength": 15,
  "Aggression": 11
}, {
  "Acceleration": 16,
  "Sprint Speed": 16,
  "Finishing": 14,
  "Long Shot": 19,
  "Shot Power": 19,
  "Positioning": 18,
  "Crossing": 7,
  "Short Passing": 15,
  "Long Passing": 8,
  "Free Kick": 9,
  "Awareness": 8,
  "Reactions": 17,
  "Ball Control": 16,
  "Dribbling": 14,
  "Composure": 17,
  "Heading": 20,
  "Marking": 9,
  "Tackling": 19,
  "Strength": 18,
  "Aggression": 14
}, {
  "Acceleration": 17,
  "Sprint Speed": 16,
  "Finishing": 14,
  "Long Shot": 20,
  "Shot Power": 19,
  "Positioning": 19,
  "Crossing": 8,
  "Short Passing": 15,
  "Long Passing": 8,
  "Free Kick": 9,
  "Awareness": 8,
  "Reactions": 18,
  "Ball Control": 17,
  "Dribbling": 14,
  "Composure": 17,
  "Heading": 20,
  "Marking": 9,
  "Tackling": 19,
  "Strength": 19,
  "Aggression": 15
}, {
  "Acceleration": 18,
  "Sprint Speed": 16,
  "Finishing": 15,
  "Long Shot": 20,
  "Shot Power": 20,
  "Positioning": 19,
  "Crossing": 8,
  "Short Passing": 16,
  "Long Passing": 9,
  "Free Kick": 10,
  "Awareness": 8,
  "Reactions": 19,
  "Ball Control": 17,
  "Dribbling": 15,
  "Composure": 17,
  "Heading": 22,
  "Marking": 9,
  "Tackling": 19,
  "Strength": 20,
  "Aggression": 15
}, {
  "Acceleration": 18,
  "Sprint Speed": 17,
  "Finishing": 15,
  "Long Shot": 20,
  "Shot Power": 21,
  "Positioning": 20,
  "Crossing": 9,
  "Short Passing": 16,
  "Long Passing": 10,
  "Free Kick": 10,
  "Awareness": 9,
  "Reactions": 19,
  "Ball Control": 18,
  "Dribbling": 15,
  "Composure": 17,
  "Heading": 22,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 20,
  "Aggression": 15
}, {
  "Acceleration": 18,
  "Sprint Speed": 18,
  "Finishing": 15,
  "Long Shot": 21,
  "Shot Power": 22,
  "Positioning": 20,
  "Crossing": 10,
  "Short Passing": 17,
  "Long Passing": 11,
  "Free Kick": 10,
  "Awareness": 9,
  "Reactions": 20,
  "Ball Control": 18,
  "Dribbling": 16,
  "Composure": 17,
  "Heading": 22,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 21,
  "Aggression": 16
}, {
  "Acceleration": 19,
  "Sprint Speed": 18,
  "Finishing": 16,
  "Long Shot": 22,
  "Shot Power": 22,
  "Positioning": 21,
  "Crossing": 10,
  "Short Passing": 17,
  "Long Passing": 12,
  "Free Kick": 10,
  "Awareness": 9,
  "Reactions": 20,
  "Ball Control": 18,
  "Dribbling": 16,
  "Composure": 17,
  "Heading": 23,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 22,
  "Aggression": 16
}, {
  "Acceleration": 19,
  "Sprint Speed": 18,
  "Finishing": 16,
  "Long Shot": 22,
  "Shot Power": 23,
  "Positioning": 21,
  "Crossing": 10,
  "Short Passing": 18,
  "Long Passing": 13,
  "Free Kick": 10,
  "Awareness": 10,
  "Reactions": 20,
  "Ball Control": 19,
  "Dribbling": 17,
  "Composure": 17,
  "Heading": 24,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 23,
  "Aggression": 16
}, {
  "Acceleration": 20,
  "Sprint Speed": 19,
  "Finishing": 17,
  "Long Shot": 23,
  "Shot Power": 23,
  "Positioning": 22,
  "Crossing": 11,
  "Short Passing": 18,
  "Long Passing": 14,
  "Free Kick": 11,
  "Awareness": 10,
  "Reactions": 21,
  "Ball Control": 19,
  "Dribbling": 17,
  "Composure": 17,
  "Heading": 24,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 24,
  "Aggression": 16
}, {
  "Acceleration": 20,
  "Sprint Speed": 19,
  "Finishing": 17,
  "Long Shot": 24,
  "Shot Power": 24,
  "Positioning": 22,
  "Crossing": 12,
  "Short Passing": 19,
  "Long Passing": 14,
  "Free Kick": 11,
  "Awareness": 10,
  "Reactions": 21,
  "Ball Control": 20,
  "Dribbling": 18,
  "Composure": 17,
  "Heading": 25,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 24,
  "Aggression": 17
}, {
  "Acceleration": 21,
  "Sprint Speed": 19,
  "Finishing": 18,
  "Long Shot": 24,
  "Shot Power": 24,
  "Positioning": 23,
  "Crossing": 13,
  "Short Passing": 20,
  "Long Passing": 14,
  "Free Kick": 11,
  "Awareness": 10,
  "Reactions": 22,
  "Ball Control": 21,
  "Dribbling": 18,
  "Composure": 17,
  "Heading": 25,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 25,
  "Aggression": 17
}, {
  "Acceleration": 24,
  "Sprint Speed": 22,
  "Finishing": 21,
  "Long Shot": 27,
  "Shot Power": 27,
  "Positioning": 26,
  "Crossing": 13,
  "Short Passing": 23,
  "Long Passing": 14,
  "Free Kick": 11,
  "Awareness": 12,
  "Reactions": 25,
  "Ball Control": 24,
  "Dribbling": 21,
  "Composure": 17,
  "Heading": 28,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 28,
  "Aggression": 20
}, {
  "Acceleration": 25,
  "Sprint Speed": 23,
  "Finishing": 22,
  "Long Shot": 29,
  "Shot Power": 27,
  "Positioning": 26,
  "Crossing": 13,
  "Short Passing": 23,
  "Long Passing": 14,
  "Free Kick": 12,
  "Awareness": 13,
  "Reactions": 26,
  "Ball Control": 24,
  "Dribbling": 22,
  "Composure": 17,
  "Heading": 30,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 30,
  "Aggression": 21
}, {
  "Acceleration": 25,
  "Sprint Speed": 24,
  "Finishing": 22,
  "Long Shot": 29,
  "Shot Power": 28,
  "Positioning": 27,
  "Crossing": 13,
  "Short Passing": 25,
  "Long Passing": 15,
  "Free Kick": 12,
  "Awareness": 14,
  "Reactions": 28,
  "Ball Control": 24,
  "Dribbling": 23,
  "Composure": 17,
  "Heading": 31,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 32,
  "Aggression": 21
}, {
  "Acceleration": 26,
  "Sprint Speed": 25,
  "Finishing": 23,
  "Long Shot": 29,
  "Shot Power": 29,
  "Positioning": 28,
  "Crossing": 13,
  "Short Passing": 26,
  "Long Passing": 15,
  "Free Kick": 12,
  "Awareness": 15,
  "Reactions": 29,
  "Ball Control": 24,
  "Dribbling": 24,
  "Composure": 17,
  "Heading": 32,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 33,
  "Aggression": 21
}, {
  "Acceleration": 27,
  "Sprint Speed": 26,
  "Finishing": 23,
  "Long Shot": 31,
  "Shot Power": 29,
  "Positioning": 28,
  "Crossing": 14,
  "Short Passing": 26,
  "Long Passing": 16,
  "Free Kick": 12,
  "Awareness": 16,
  "Reactions": 30,
  "Ball Control": 24,
  "Dribbling": 25,
  "Composure": 17,
  "Heading": 33,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 34,
  "Aggression": 22
}, {
  "Acceleration": 28,
  "Sprint Speed": 28,
  "Finishing": 24,
  "Long Shot": 31,
  "Shot Power": 31,
  "Positioning": 28,
  "Crossing": 15,
  "Short Passing": 27,
  "Long Passing": 16,
  "Free Kick": 12,
  "Awareness": 17,
  "Reactions": 32,
  "Ball Control": 25,
  "Dribbling": 26,
  "Composure": 17,
  "Heading": 33,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 35,
  "Aggression": 22
}, {
  "Acceleration": 28,
  "Sprint Speed": 29,
  "Finishing": 25,
  "Long Shot": 32,
  "Shot Power": 31,
  "Positioning": 30,
  "Crossing": 16,
  "Short Passing": 28,
  "Long Passing": 17,
  "Free Kick": 13,
  "Awareness": 18,
  "Reactions": 33,
  "Ball Control": 25,
  "Dribbling": 27,
  "Composure": 17,
  "Heading": 34,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 35,
  "Aggression": 22
}, {
  "Acceleration": 29,
  "Sprint Speed": 30,
  "Finishing": 26,
  "Long Shot": 33,
  "Shot Power": 31,
  "Positioning": 31,
  "Crossing": 16,
  "Short Passing": 29,
  "Long Passing": 17,
  "Free Kick": 14,
  "Awareness": 19,
  "Reactions": 36,
  "Ball Control": 25,
  "Dribbling": 28,
  "Composure": 17,
  "Heading": 34,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 37,
  "Aggression": 23
}, {
  "Acceleration": 29,
  "Sprint Speed": 32,
  "Finishing": 27,
  "Long Shot": 34,
  "Shot Power": 32,
  "Positioning": 31,
  "Crossing": 16,
  "Short Passing": 30,
  "Long Passing": 18,
  "Free Kick": 14,
  "Awareness": 20,
  "Reactions": 37,
  "Ball Control": 25,
  "Dribbling": 29,
  "Composure": 17,
  "Heading": 35,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 38,
  "Aggression": 24
}, {
  "Acceleration": 30,
  "Sprint Speed": 33,
  "Finishing": 28,
  "Long Shot": 35,
  "Shot Power": 34,
  "Positioning": 33,
  "Crossing": 18,
  "Short Passing": 32,
  "Long Passing": 18,
  "Free Kick": 14,
  "Awareness": 21,
  "Reactions": 39,
  "Ball Control": 25,
  "Dribbling": 30,
  "Composure": 17,
  "Heading": 35,
  "Marking": 10,
  "Tackling": 19,
  "Strength": 40,
  "Aggression": 24
}, {
  "Acceleration": 30,
  "Sprint Speed": 34,
  "Finishing": 30,
  "Long Shot": 37,
  "Shot Power": 34,
  "Positioning": 33,
  "Crossing": 20,
  "Short Passing": 33,
  "Long Passing": 20,
  "Free Kick": 16,
  "Awareness": 24,
  "Reactions": 41,
  "Ball Control": 25,
  "Dribbling": 31,
  "Composure": 20,
  "Heading": 38,
  "Marking": 10,
  "Tackling": 29,
  "Strength": 40,
  "Aggression": 24
}, {
  "Acceleration": 34,
  "Sprint Speed": 35,
  "Finishing": 32,
  "Long Shot": 41,
  "Shot Power": 35,
  "Positioning": 36,
  "Crossing": 20,
  "Short Passing": 33,
  "Long Passing": 20,
  "Free Kick": 16,
  "Awareness": 24,
  "Reactions": 43,
  "Ball Control": 31,
  "Dribbling": 35,
  "Composure": 20,
  "Heading": 40,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 42,
  "Aggression": 24
}, {
  "Acceleration": 36,
  "Sprint Speed": 37,
  "Finishing": 33,
  "Long Shot": 42,
  "Shot Power": 37,
  "Positioning": 39,
  "Crossing": 22,
  "Short Passing": 36,
  "Long Passing": 20,
  "Free Kick": 17,
  "Awareness": 24,
  "Reactions": 45,
  "Ball Control": 31,
  "Dribbling": 37,
  "Composure": 20,
  "Heading": 43,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 45,
  "Aggression": 24
}, {
  "Acceleration": 38,
  "Sprint Speed": 40,
  "Finishing": 36,
  "Long Shot": 42,
  "Shot Power": 41,
  "Positioning": 41,
  "Crossing": 22,
  "Short Passing": 39,
  "Long Passing": 22,
  "Free Kick": 22,
  "Awareness": 27,
  "Reactions": 45,
  "Ball Control": 31,
  "Dribbling": 40,
  "Composure": 30,
  "Heading": 45,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 47,
  "Aggression": 30
}, {
  "Acceleration": 42,
  "Sprint Speed": 43,
  "Finishing": 38,
  "Long Shot": 44,
  "Shot Power": 43,
  "Positioning": 44,
  "Crossing": 25,
  "Short Passing": 41,
  "Long Passing": 29,
  "Free Kick": 22,
  "Awareness": 29,
  "Reactions": 47,
  "Ball Control": 31,
  "Dribbling": 42,
  "Composure": 30,
  "Heading": 49,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 49,
  "Aggression": 30
}, {
  "Acceleration": 44,
  "Sprint Speed": 45,
  "Finishing": 42,
  "Long Shot": 47,
  "Shot Power": 46,
  "Positioning": 49,
  "Crossing": 25,
  "Short Passing": 47,
  "Long Passing": 29,
  "Free Kick": 23,
  "Awareness": 32,
  "Reactions": 52,
  "Ball Control": 37,
  "Dribbling": 44,
  "Composure": 30,
  "Heading": 51,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 53,
  "Aggression": 30
}, {
  "Acceleration": 47,
  "Sprint Speed": 49,
  "Finishing": 48,
  "Long Shot": 51,
  "Shot Power": 48,
  "Positioning": 51,
  "Crossing": 28,
  "Short Passing": 50,
  "Long Passing": 29,
  "Free Kick": 23,
  "Awareness": 36,
  "Reactions": 55,
  "Ball Control": 37,
  "Dribbling": 49,
  "Composure": 40,
  "Heading": 54,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 54,
  "Aggression": 30
}, {
  "Acceleration": 52,
  "Sprint Speed": 52,
  "Finishing": 51,
  "Long Shot": 53,
  "Shot Power": 51,
  "Positioning": 54,
  "Crossing": 28,
  "Short Passing": 53,
  "Long Passing": 29,
  "Free Kick": 25,
  "Awareness": 40,
  "Reactions": 58,
  "Ball Control": 42,
  "Dribbling": 54,
  "Composure": 40,
  "Heading": 56,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 55,
  "Aggression": 30
}, {
  "Acceleration": 56,
  "Sprint Speed": 57,
  "Finishing": 56,
  "Long Shot": 55,
  "Shot Power": 59,
  "Positioning": 57,
  "Crossing": 28,
  "Short Passing": 56,
  "Long Passing": 34,
  "Free Kick": 25,
  "Awareness": 43,
  "Reactions": 60,
  "Ball Control": 47,
  "Dribbling": 57,
  "Composure": 40,
  "Heading": 64,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 56,
  "Aggression": 30
}, {
  "Acceleration": 56,
  "Sprint Speed": 62,
  "Finishing": 61,
  "Long Shot": 57,
  "Shot Power": 63,
  "Positioning": 59,
  "Crossing": 28,
  "Short Passing": 60,
  "Long Passing": 39,
  "Free Kick": 28,
  "Awareness": 46,
  "Reactions": 60,
  "Ball Control": 52,
  "Dribbling": 59,
  "Composure": 40,
  "Heading": 66,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 57,
  "Aggression": 30
}, {
  "Acceleration": 56,
  "Sprint Speed": 65,
  "Finishing": 65,
  "Long Shot": 63,
  "Shot Power": 67,
  "Positioning": 63,
  "Crossing": 28,
  "Short Passing": 64,
  "Long Passing": 39,
  "Free Kick": 38,
  "Awareness": 51,
  "Reactions": 66,
  "Ball Control": 57,
  "Dribbling": 64,
  "Composure": 40,
  "Heading": 66,
  "Marking": 20,
  "Tackling": 29,
  "Strength": 62,
  "Aggression": 30
}]