export default [{
  "Acceleration": 1,
  "Sprint Speed": 0,
  "Finishing": 1,
  "Long Shot": 1,
  "Shot Power": 0,
  "Positioning": 0,
  "Crossing": 1,
  "Short Passing": 0,
  "Long Passing": 1,
  "Free Kick": 0,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 1,
  "Composure": 0,
  "Heading": 0,
  "Marking": 0,
  "Tackling": 0,
  "Strength": 0,
  "Aggression": 0
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 2,
  "Long Shot": 1,
  "Shot Power": 0,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 0,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 2,
  "Composure": 1,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 0,
  "Strength": 1,
  "Aggression": 0
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 2,
  "Long Shot": 2,
  "Shot Power": 1,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 2,
  "Free Kick": 0,
  "Awareness": 2,
  "Reactions": 2,
  "Ball Control": 2,
  "Dribbling": 3,
  "Composure": 1,
  "Heading": 1,
  "Marking": 1,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 3,
  "Shot Power": 1,
  "Positioning": 2,
  "Crossing": 2,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 0,
  "Awareness": 2,
  "Reactions": 2,
  "Ball Control": 2,
  "Dribbling": 4,
  "Composure": 1,
  "Heading": 2,
  "Marking": 2,
  "Tackling": 2,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 3,
  "Long Shot": 3,
  "Shot Power": 2,
  "Positioning": 2,
  "Crossing": 2,
  "Short Passing": 2,
  "Long Passing": 3,
  "Free Kick": 0,
  "Awareness": 3,
  "Reactions": 2,
  "Ball Control": 3,
  "Dribbling": 4,
  "Composure": 2,
  "Heading": 2,
  "Marking": 3,
  "Tackling": 3,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 4,
  "Long Shot": 4,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 3,
  "Short Passing": 2,
  "Long Passing": 3,
  "Free Kick": 0,
  "Awareness": 3,
  "Reactions": 3,
  "Ball Control": 3,
  "Dribbling": 5,
  "Composure": 2,
  "Heading": 3,
  "Marking": 3,
  "Tackling": 3,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 4,
  "Long Shot": 4,
  "Shot Power": 3,
  "Positioning": 3,
  "Crossing": 3,
  "Short Passing": 3,
  "Long Passing": 4,
  "Free Kick": 0,
  "Awareness": 4,
  "Reactions": 3,
  "Ball Control": 4,
  "Dribbling": 5,
  "Composure": 3,
  "Heading": 3,
  "Marking": 4,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 3
}, {
  "Acceleration": 3,
  "Sprint Speed": 4,
  "Finishing": 4,
  "Long Shot": 5,
  "Shot Power": 3,
  "Positioning": 4,
  "Crossing": 4,
  "Short Passing": 4,
  "Long Passing": 4,
  "Free Kick": 0,
  "Awareness": 4,
  "Reactions": 4,
  "Ball Control": 5,
  "Dribbling": 6,
  "Composure": 3,
  "Heading": 3,
  "Marking": 4,
  "Tackling": 4,
  "Strength": 3,
  "Aggression": 3
}, {
  "Acceleration": 4,
  "Sprint Speed": 4,
  "Finishing": 5,
  "Long Shot": 5,
  "Shot Power": 4,
  "Positioning": 4,
  "Crossing": 4,
  "Short Passing": 5,
  "Long Passing": 4,
  "Free Kick": 0,
  "Awareness": 5,
  "Reactions": 5,
  "Ball Control": 5,
  "Dribbling": 6,
  "Composure": 3,
  "Heading": 4,
  "Marking": 4,
  "Tackling": 5,
  "Strength": 3,
  "Aggression": 4
}, {
  "Acceleration": 4,
  "Sprint Speed": 5,
  "Finishing": 6,
  "Long Shot": 6,
  "Shot Power": 4,
  "Positioning": 4,
  "Crossing": 5,
  "Short Passing": 5,
  "Long Passing": 5,
  "Free Kick": 0,
  "Awareness": 5,
  "Reactions": 5,
  "Ball Control": 6,
  "Dribbling": 7,
  "Composure": 4,
  "Heading": 4,
  "Marking": 5,
  "Tackling": 5,
  "Strength": 3,
  "Aggression": 4
}, {
  "Acceleration": 5,
  "Sprint Speed": 5,
  "Finishing": 7,
  "Long Shot": 6,
  "Shot Power": 5,
  "Positioning": 5,
  "Crossing": 5,
  "Short Passing": 6,
  "Long Passing": 5,
  "Free Kick": 0,
  "Awareness": 6,
  "Reactions": 6,
  "Ball Control": 6,
  "Dribbling": 7,
  "Composure": 4,
  "Heading": 5,
  "Marking": 5,
  "Tackling": 6,
  "Strength": 3,
  "Aggression": 5
}, {
  "Acceleration": 5,
  "Sprint Speed": 6,
  "Finishing": 7,
  "Long Shot": 6,
  "Shot Power": 5,
  "Positioning": 5,
  "Crossing": 6,
  "Short Passing": 7,
  "Long Passing": 6,
  "Free Kick": 0,
  "Awareness": 6,
  "Reactions": 7,
  "Ball Control": 7,
  "Dribbling": 8,
  "Composure": 5,
  "Heading": 5,
  "Marking": 5,
  "Tackling": 7,
  "Strength": 3,
  "Aggression": 5
}, {
  "Acceleration": 6,
  "Sprint Speed": 6,
  "Finishing": 8,
  "Long Shot": 7,
  "Shot Power": 6,
  "Positioning": 6,
  "Crossing": 7,
  "Short Passing": 7,
  "Long Passing": 7,
  "Free Kick": 0,
  "Awareness": 7,
  "Reactions": 7,
  "Ball Control": 7,
  "Dribbling": 9,
  "Composure": 5,
  "Heading": 6,
  "Marking": 6,
  "Tackling": 7,
  "Strength": 3,
  "Aggression": 5
}, {
  "Acceleration": 9,
  "Sprint Speed": 9,
  "Finishing": 11,
  "Long Shot": 10,
  "Shot Power": 6,
  "Positioning": 9,
  "Crossing": 10,
  "Short Passing": 10,
  "Long Passing": 10,
  "Free Kick": 0,
  "Awareness": 10,
  "Reactions": 10,
  "Ball Control": 10,
  "Dribbling": 12,
  "Composure": 5,
  "Heading": 6,
  "Marking": 6,
  "Tackling": 8,
  "Strength": 4,
  "Aggression": 5
}, {
  "Acceleration": 9,
  "Sprint Speed": 10,
  "Finishing": 12,
  "Long Shot": 11,
  "Shot Power": 7,
  "Positioning": 10,
  "Crossing": 10,
  "Short Passing": 11,
  "Long Passing": 11,
  "Free Kick": 0,
  "Awareness": 11,
  "Reactions": 11,
  "Ball Control": 10,
  "Dribbling": 12,
  "Composure": 6,
  "Heading": 6,
  "Marking": 6,
  "Tackling": 8,
  "Strength": 4,
  "Aggression": 6
}, {
  "Acceleration": 10,
  "Sprint Speed": 10,
  "Finishing": 13,
  "Long Shot": 11,
  "Shot Power": 7,
  "Positioning": 10,
  "Crossing": 11,
  "Short Passing": 11,
  "Long Passing": 12,
  "Free Kick": 0,
  "Awareness": 11,
  "Reactions": 11,
  "Ball Control": 10,
  "Dribbling": 13,
  "Composure": 6,
  "Heading": 7,
  "Marking": 7,
  "Tackling": 9,
  "Strength": 4,
  "Aggression": 7
}, {
  "Acceleration": 10,
  "Sprint Speed": 11,
  "Finishing": 13,
  "Long Shot": 12,
  "Shot Power": 8,
  "Positioning": 10,
  "Crossing": 11,
  "Short Passing": 12,
  "Long Passing": 12,
  "Free Kick": 0,
  "Awareness": 12,
  "Reactions": 12,
  "Ball Control": 11,
  "Dribbling": 13,
  "Composure": 7,
  "Heading": 7,
  "Marking": 7,
  "Tackling": 9,
  "Strength": 5,
  "Aggression": 7
}, {
  "Acceleration": 11,
  "Sprint Speed": 11,
  "Finishing": 14,
  "Long Shot": 12,
  "Shot Power": 9,
  "Positioning": 11,
  "Crossing": 11,
  "Short Passing": 13,
  "Long Passing": 13,
  "Free Kick": 0,
  "Awareness": 12,
  "Reactions": 13,
  "Ball Control": 11,
  "Dribbling": 14,
  "Composure": 7,
  "Heading": 7,
  "Marking": 8,
  "Tackling": 10,
  "Strength": 5,
  "Aggression": 8
}, {
  "Acceleration": 11,
  "Sprint Speed": 12,
  "Finishing": 14,
  "Long Shot": 13,
  "Shot Power": 9,
  "Positioning": 11,
  "Crossing": 12,
  "Short Passing": 14,
  "Long Passing": 13,
  "Free Kick": 0,
  "Awareness": 13,
  "Reactions": 13,
  "Ball Control": 12,
  "Dribbling": 15,
  "Composure": 7,
  "Heading": 8,
  "Marking": 8,
  "Tackling": 10,
  "Strength": 6,
  "Aggression": 8
}, {
  "Acceleration": 12,
  "Sprint Speed": 13,
  "Finishing": 15,
  "Long Shot": 13,
  "Shot Power": 10,
  "Positioning": 12,
  "Crossing": 12,
  "Short Passing": 14,
  "Long Passing": 14,
  "Free Kick": 0,
  "Awareness": 13,
  "Reactions": 13,
  "Ball Control": 12,
  "Dribbling": 15,
  "Composure": 8,
  "Heading": 8,
  "Marking": 9,
  "Tackling": 11,
  "Strength": 6,
  "Aggression": 9
}, {
  "Acceleration": 12,
  "Sprint Speed": 13,
  "Finishing": 15,
  "Long Shot": 14,
  "Shot Power": 10,
  "Positioning": 12,
  "Crossing": 13,
  "Short Passing": 15,
  "Long Passing": 15,
  "Free Kick": 0,
  "Awareness": 14,
  "Reactions": 14,
  "Ball Control": 13,
  "Dribbling": 15,
  "Composure": 8,
  "Heading": 8,
  "Marking": 10,
  "Tackling": 12,
  "Strength": 6,
  "Aggression": 9
}, {
  "Acceleration": 13,
  "Sprint Speed": 13,
  "Finishing": 15,
  "Long Shot": 15,
  "Shot Power": 10,
  "Positioning": 13,
  "Crossing": 13,
  "Short Passing": 15,
  "Long Passing": 15,
  "Free Kick": 0,
  "Awareness": 14,
  "Reactions": 14,
  "Ball Control": 14,
  "Dribbling": 16,
  "Composure": 9,
  "Heading": 9,
  "Marking": 10,
  "Tackling": 13,
  "Strength": 7,
  "Aggression": 10
}, {
  "Acceleration": 14,
  "Sprint Speed": 14,
  "Finishing": 15,
  "Long Shot": 16,
  "Shot Power": 11,
  "Positioning": 13,
  "Crossing": 14,
  "Short Passing": 15,
  "Long Passing": 16,
  "Free Kick": 0,
  "Awareness": 15,
  "Reactions": 15,
  "Ball Control": 14,
  "Dribbling": 17,
  "Composure": 9,
  "Heading": 9,
  "Marking": 11,
  "Tackling": 13,
  "Strength": 8,
  "Aggression": 10
}, {
  "Acceleration": 17,
  "Sprint Speed": 17,
  "Finishing": 18,
  "Long Shot": 19,
  "Shot Power": 11,
  "Positioning": 16,
  "Crossing": 17,
  "Short Passing": 18,
  "Long Passing": 19,
  "Free Kick": 0,
  "Awareness": 18,
  "Reactions": 18,
  "Ball Control": 17,
  "Dribbling": 20,
  "Composure": 9,
  "Heading": 9,
  "Marking": 11,
  "Tackling": 14,
  "Strength": 9,
  "Aggression": 10
}, {
  "Acceleration": 18,
  "Sprint Speed": 17,
  "Finishing": 19,
  "Long Shot": 20,
  "Shot Power": 11,
  "Positioning": 16,
  "Crossing": 18,
  "Short Passing": 19,
  "Long Passing": 19,
  "Free Kick": 0,
  "Awareness": 19,
  "Reactions": 18,
  "Ball Control": 18,
  "Dribbling": 21,
  "Composure": 10,
  "Heading": 10,
  "Marking": 11,
  "Tackling": 14,
  "Strength": 10,
  "Aggression": 10
}, {
  "Acceleration": 18,
  "Sprint Speed": 18,
  "Finishing": 20,
  "Long Shot": 21,
  "Shot Power": 11,
  "Positioning": 17,
  "Crossing": 18,
  "Short Passing": 19,
  "Long Passing": 20,
  "Free Kick": 0,
  "Awareness": 19,
  "Reactions": 19,
  "Ball Control": 18,
  "Dribbling": 21,
  "Composure": 11,
  "Heading": 10,
  "Marking": 12,
  "Tackling": 15,
  "Strength": 10,
  "Aggression": 11
}, {
  "Acceleration": 19,
  "Sprint Speed": 18,
  "Finishing": 20,
  "Long Shot": 22,
  "Shot Power": 12,
  "Positioning": 17,
  "Crossing": 19,
  "Short Passing": 20,
  "Long Passing": 21,
  "Free Kick": 0,
  "Awareness": 19,
  "Reactions": 19,
  "Ball Control": 19,
  "Dribbling": 22,
  "Composure": 11,
  "Heading": 11,
  "Marking": 12,
  "Tackling": 15,
  "Strength": 10,
  "Aggression": 11
}, {
  "Acceleration": 19,
  "Sprint Speed": 19,
  "Finishing": 20,
  "Long Shot": 22,
  "Shot Power": 12,
  "Positioning": 18,
  "Crossing": 19,
  "Short Passing": 21,
  "Long Passing": 21,
  "Free Kick": 0,
  "Awareness": 20,
  "Reactions": 19,
  "Ball Control": 20,
  "Dribbling": 22,
  "Composure": 12,
  "Heading": 12,
  "Marking": 13,
  "Tackling": 16,
  "Strength": 11,
  "Aggression": 11
}, {
  "Acceleration": 20,
  "Sprint Speed": 19,
  "Finishing": 21,
  "Long Shot": 23,
  "Shot Power": 13,
  "Positioning": 18,
  "Crossing": 19,
  "Short Passing": 22,
  "Long Passing": 21,
  "Free Kick": 0,
  "Awareness": 21,
  "Reactions": 20,
  "Ball Control": 21,
  "Dribbling": 23,
  "Composure": 12,
  "Heading": 12,
  "Marking": 14,
  "Tackling": 16,
  "Strength": 11,
  "Aggression": 12
}, {
  "Acceleration": 20,
  "Sprint Speed": 20,
  "Finishing": 21,
  "Long Shot": 24,
  "Shot Power": 13,
  "Positioning": 19,
  "Crossing": 20,
  "Short Passing": 22,
  "Long Passing": 22,
  "Free Kick": 0,
  "Awareness": 21,
  "Reactions": 20,
  "Ball Control": 22,
  "Dribbling": 23,
  "Composure": 13,
  "Heading": 13,
  "Marking": 14,
  "Tackling": 17,
  "Strength": 11,
  "Aggression": 12
}, {
  "Acceleration": 21,
  "Sprint Speed": 21,
  "Finishing": 22,
  "Long Shot": 24,
  "Shot Power": 14,
  "Positioning": 20,
  "Crossing": 20,
  "Short Passing": 23,
  "Long Passing": 22,
  "Free Kick": 0,
  "Awareness": 22,
  "Reactions": 20,
  "Ball Control": 23,
  "Dribbling": 23,
  "Composure": 14,
  "Heading": 13,
  "Marking": 15,
  "Tackling": 17,
  "Strength": 11,
  "Aggression": 13
}, {
  "Acceleration": 22,
  "Sprint Speed": 21,
  "Finishing": 23,
  "Long Shot": 25,
  "Shot Power": 14,
  "Positioning": 20,
  "Crossing": 21,
  "Short Passing": 24,
  "Long Passing": 23,
  "Free Kick": 0,
  "Awareness": 22,
  "Reactions": 21,
  "Ball Control": 24,
  "Dribbling": 24,
  "Composure": 14,
  "Heading": 13,
  "Marking": 15,
  "Tackling": 17,
  "Strength": 12,
  "Aggression": 13
}, {
  "Acceleration": 22,
  "Sprint Speed": 22,
  "Finishing": 23,
  "Long Shot": 26,
  "Shot Power": 14,
  "Positioning": 21,
  "Crossing": 22,
  "Short Passing": 25,
  "Long Passing": 23,
  "Free Kick": 0,
  "Awareness": 23,
  "Reactions": 22,
  "Ball Control": 25,
  "Dribbling": 24,
  "Composure": 14,
  "Heading": 14,
  "Marking": 16,
  "Tackling": 18,
  "Strength": 12,
  "Aggression": 13
}, {
  "Acceleration": 25,
  "Sprint Speed": 25,
  "Finishing": 26,
  "Long Shot": 29,
  "Shot Power": 14,
  "Positioning": 24,
  "Crossing": 25,
  "Short Passing": 28,
  "Long Passing": 26,
  "Free Kick": 0,
  "Awareness": 26,
  "Reactions": 25,
  "Ball Control": 28,
  "Dribbling": 27,
  "Composure": 14,
  "Heading": 14,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 13,
  "Aggression": 13
}, {
  "Acceleration": 25,
  "Sprint Speed": 26,
  "Finishing": 26,
  "Long Shot": 30,
  "Shot Power": 14,
  "Positioning": 25,
  "Crossing": 26,
  "Short Passing": 29,
  "Long Passing": 26,
  "Free Kick": 0,
  "Awareness": 26,
  "Reactions": 25,
  "Ball Control": 29,
  "Dribbling": 28,
  "Composure": 15,
  "Heading": 14,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 14,
  "Aggression": 13
}, {
  "Acceleration": 26,
  "Sprint Speed": 26,
  "Finishing": 27,
  "Long Shot": 30,
  "Shot Power": 15,
  "Positioning": 25,
  "Crossing": 26,
  "Short Passing": 30,
  "Long Passing": 27,
  "Free Kick": 1,
  "Awareness": 27,
  "Reactions": 26,
  "Ball Control": 30,
  "Dribbling": 28,
  "Composure": 16,
  "Heading": 14,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 14,
  "Aggression": 14
}, {
  "Acceleration": 26,
  "Sprint Speed": 26,
  "Finishing": 28,
  "Long Shot": 31,
  "Shot Power": 15,
  "Positioning": 26,
  "Crossing": 27,
  "Short Passing": 31,
  "Long Passing": 28,
  "Free Kick": 2,
  "Awareness": 27,
  "Reactions": 26,
  "Ball Control": 31,
  "Dribbling": 29,
  "Composure": 17,
  "Heading": 15,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 14,
  "Aggression": 14
}, {
  "Acceleration": 27,
  "Sprint Speed": 27,
  "Finishing": 29,
  "Long Shot": 31,
  "Shot Power": 16,
  "Positioning": 26,
  "Crossing": 28,
  "Short Passing": 31,
  "Long Passing": 28,
  "Free Kick": 3,
  "Awareness": 28,
  "Reactions": 27,
  "Ball Control": 32,
  "Dribbling": 29,
  "Composure": 17,
  "Heading": 16,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 14,
  "Aggression": 14
}, {
  "Acceleration": 27,
  "Sprint Speed": 28,
  "Finishing": 29,
  "Long Shot": 32,
  "Shot Power": 16,
  "Positioning": 27,
  "Crossing": 28,
  "Short Passing": 32,
  "Long Passing": 29,
  "Free Kick": 3,
  "Awareness": 29,
  "Reactions": 28,
  "Ball Control": 33,
  "Dribbling": 30,
  "Composure": 17,
  "Heading": 17,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 14,
  "Aggression": 15
}, {
  "Acceleration": 28,
  "Sprint Speed": 28,
  "Finishing": 30,
  "Long Shot": 33,
  "Shot Power": 17,
  "Positioning": 28,
  "Crossing": 29,
  "Short Passing": 32,
  "Long Passing": 29,
  "Free Kick": 4,
  "Awareness": 29,
  "Reactions": 28,
  "Ball Control": 34,
  "Dribbling": 30,
  "Composure": 18,
  "Heading": 17,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 15,
  "Aggression": 15
}, {
  "Acceleration": 28,
  "Sprint Speed": 29,
  "Finishing": 30,
  "Long Shot": 33,
  "Shot Power": 17,
  "Positioning": 28,
  "Crossing": 29,
  "Short Passing": 33,
  "Long Passing": 29,
  "Free Kick": 5,
  "Awareness": 30,
  "Reactions": 29,
  "Ball Control": 35,
  "Dribbling": 31,
  "Composure": 19,
  "Heading": 18,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 16,
  "Aggression": 17
}, {
  "Acceleration": 29,
  "Sprint Speed": 29,
  "Finishing": 31,
  "Long Shot": 33,
  "Shot Power": 18,
  "Positioning": 29,
  "Crossing": 30,
  "Short Passing": 34,
  "Long Passing": 30,
  "Free Kick": 6,
  "Awareness": 31,
  "Reactions": 29,
  "Ball Control": 36,
  "Dribbling": 31,
  "Composure": 19,
  "Heading": 19,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 16,
  "Aggression": 17
}, {
  "Acceleration": 29,
  "Sprint Speed": 30,
  "Finishing": 31,
  "Long Shot": 34,
  "Shot Power": 18,
  "Positioning": 29,
  "Crossing": 31,
  "Short Passing": 34,
  "Long Passing": 30,
  "Free Kick": 6,
  "Awareness": 32,
  "Reactions": 30,
  "Ball Control": 37,
  "Dribbling": 32,
  "Composure": 20,
  "Heading": 20,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 17,
  "Aggression": 17
}, {
  "Acceleration": 31,
  "Sprint Speed": 32,
  "Finishing": 33,
  "Long Shot": 36,
  "Shot Power": 20,
  "Positioning": 31,
  "Crossing": 33,
  "Short Passing": 36,
  "Long Passing": 32,
  "Free Kick": 6,
  "Awareness": 34,
  "Reactions": 32,
  "Ball Control": 39,
  "Dribbling": 34,
  "Composure": 20,
  "Heading": 20,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 19,
  "Aggression": 17
}, {
  "Acceleration": 34,
  "Sprint Speed": 36,
  "Finishing": 36,
  "Long Shot": 36,
  "Shot Power": 20,
  "Positioning": 34,
  "Crossing": 40,
  "Short Passing": 39,
  "Long Passing": 34,
  "Free Kick": 6,
  "Awareness": 44,
  "Reactions": 35,
  "Ball Control": 42,
  "Dribbling": 37,
  "Composure": 20,
  "Heading": 20,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 19,
  "Aggression": 17
}, {
  "Acceleration": 38,
  "Sprint Speed": 41,
  "Finishing": 39,
  "Long Shot": 40,
  "Shot Power": 20,
  "Positioning": 37,
  "Crossing": 40,
  "Short Passing": 41,
  "Long Passing": 37,
  "Free Kick": 18,
  "Awareness": 47,
  "Reactions": 38,
  "Ball Control": 46,
  "Dribbling": 41,
  "Composure": 20,
  "Heading": 20,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 19,
  "Aggression": 17
}, {
  "Acceleration": 42,
  "Sprint Speed": 44,
  "Finishing": 43,
  "Long Shot": 44,
  "Shot Power": 20,
  "Positioning": 37,
  "Crossing": 47,
  "Short Passing": 44,
  "Long Passing": 37,
  "Free Kick": 18,
  "Awareness": 51,
  "Reactions": 41,
  "Ball Control": 49,
  "Dribbling": 44,
  "Composure": 20,
  "Heading": 20,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 23,
  "Aggression": 22
}, {
  "Acceleration": 45,
  "Sprint Speed": 49,
  "Finishing": 46,
  "Long Shot": 49,
  "Shot Power": 20,
  "Positioning": 41,
  "Crossing": 47,
  "Short Passing": 47,
  "Long Passing": 39,
  "Free Kick": 18,
  "Awareness": 54,
  "Reactions": 44,
  "Ball Control": 53,
  "Dribbling": 47,
  "Composure": 20,
  "Heading": 25,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 23,
  "Aggression": 22
}, {
  "Acceleration": 49,
  "Sprint Speed": 52,
  "Finishing": 49,
  "Long Shot": 49,
  "Shot Power": 28,
  "Positioning": 44,
  "Crossing": 47,
  "Short Passing": 50,
  "Long Passing": 39,
  "Free Kick": 18,
  "Awareness": 58,
  "Reactions": 47,
  "Ball Control": 56,
  "Dribbling": 51,
  "Composure": 45,
  "Heading": 25,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 23,
  "Aggression": 27
}, {
  "Acceleration": 52,
  "Sprint Speed": 54,
  "Finishing": 53,
  "Long Shot": 49,
  "Shot Power": 28,
  "Positioning": 48,
  "Crossing": 54,
  "Short Passing": 52,
  "Long Passing": 42,
  "Free Kick": 18,
  "Awareness": 61,
  "Reactions": 51,
  "Ball Control": 60,
  "Dribbling": 54,
  "Composure": 45,
  "Heading": 30,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 23,
  "Aggression": 27
}, {
  "Acceleration": 56,
  "Sprint Speed": 59,
  "Finishing": 56,
  "Long Shot": 54,
  "Shot Power": 28,
  "Positioning": 51,
  "Crossing": 54,
  "Short Passing": 55,
  "Long Passing": 46,
  "Free Kick": 18,
  "Awareness": 65,
  "Reactions": 54,
  "Ball Control": 63,
  "Dribbling": 58,
  "Composure": 45,
  "Heading": 30,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 27,
  "Aggression": 27
}, {
  "Acceleration": 60,
  "Sprint Speed": 61,
  "Finishing": 59,
  "Long Shot": 58,
  "Shot Power": 28,
  "Positioning": 55,
  "Crossing": 61,
  "Short Passing": 58,
  "Long Passing": 49,
  "Free Kick": 18,
  "Awareness": 65,
  "Reactions": 56,
  "Ball Control": 67,
  "Dribbling": 62,
  "Composure": 45,
  "Heading": 30,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 31,
  "Aggression": 27
}, {
  "Acceleration": 63,
  "Sprint Speed": 64,
  "Finishing": 62,
  "Long Shot": 58,
  "Shot Power": 36,
  "Positioning": 58,
  "Crossing": 61,
  "Short Passing": 61,
  "Long Passing": 52,
  "Free Kick": 18,
  "Awareness": 68,
  "Reactions": 59,
  "Ball Control": 70,
  "Dribbling": 65,
  "Composure": 45,
  "Heading": 30,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 35,
  "Aggression": 27
}, {
  "Acceleration": 68,
  "Sprint Speed": 69,
  "Finishing": 67,
  "Long Shot": 63,
  "Shot Power": 46,
  "Positioning": 63,
  "Crossing": 68,
  "Short Passing": 66,
  "Long Passing": 57,
  "Free Kick": 18,
  "Awareness": 68,
  "Reactions": 64,
  "Ball Control": 75,
  "Dribbling": 70,
  "Composure": 45,
  "Heading": 30,
  "Marking": 16,
  "Tackling": 19,
  "Strength": 35,
  "Aggression": 27
}]