export default [{
  "Acceleration": 1,
  "Sprint Speed": 0,
  "Finishing": 0,
  "Long Shot": 0,
  "Shot Power": 1,
  "Positioning": 1,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 0,
  "Free Kick": 0,
  "Awareness": 0,
  "Reactions": 1,
  "Ball Control": 0,
  "Dribbling": 0,
  "Composure": 0,
  "Heading": 0,
  "Marking": 1,
  "Tackling": 1,
  "Strength": 0,
  "Aggression": 1
}, {
  "Acceleration": 1,
  "Sprint Speed": 1,
  "Finishing": 1,
  "Long Shot": 1,
  "Shot Power": 1,
  "Positioning": 2,
  "Crossing": 1,
  "Short Passing": 1,
  "Long Passing": 1,
  "Free Kick": 0,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 0,
  "Dribbling": 0,
  "Composure": 1,
  "Heading": 0,
  "Marking": 1,
  "Tackling": 1,
  "Strength": 0,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 1,
  "Finishing": 2,
  "Long Shot": 1,
  "Shot Power": 1,
  "Positioning": 3,
  "Crossing": 2,
  "Short Passing": 2,
  "Long Passing": 1,
  "Free Kick": 0,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 0,
  "Dribbling": 0,
  "Composure": 1,
  "Heading": 0,
  "Marking": 2,
  "Tackling": 1,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 2,
  "Finishing": 2,
  "Long Shot": 2,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 2,
  "Short Passing": 2,
  "Long Passing": 1,
  "Free Kick": 1,
  "Awareness": 1,
  "Reactions": 1,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 2,
  "Heading": 1,
  "Marking": 2,
  "Tackling": 2,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 2,
  "Sprint Speed": 3,
  "Finishing": 3,
  "Long Shot": 2,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 3,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 2,
  "Reactions": 2,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 4,
  "Heading": 1,
  "Marking": 2,
  "Tackling": 2,
  "Strength": 1,
  "Aggression": 1
}, {
  "Acceleration": 3,
  "Sprint Speed": 3,
  "Finishing": 3,
  "Long Shot": 3,
  "Shot Power": 2,
  "Positioning": 3,
  "Crossing": 3,
  "Short Passing": 2,
  "Long Passing": 2,
  "Free Kick": 1,
  "Awareness": 3,
  "Reactions": 3,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 5,
  "Heading": 1,
  "Marking": 2,
  "Tackling": 3,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 3,
  "Sprint Speed": 4,
  "Finishing": 3,
  "Long Shot": 3,
  "Shot Power": 2,
  "Positioning": 4,
  "Crossing": 4,
  "Short Passing": 2,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 3,
  "Reactions": 4,
  "Ball Control": 1,
  "Dribbling": 0,
  "Composure": 5,
  "Heading": 2,
  "Marking": 3,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 4,
  "Sprint Speed": 5,
  "Finishing": 4,
  "Long Shot": 4,
  "Shot Power": 3,
  "Positioning": 5,
  "Crossing": 4,
  "Short Passing": 2,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 3,
  "Reactions": 4,
  "Ball Control": 2,
  "Dribbling": 0,
  "Composure": 6,
  "Heading": 2,
  "Marking": 4,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 4,
  "Sprint Speed": 6,
  "Finishing": 4,
  "Long Shot": 4,
  "Shot Power": 3,
  "Positioning": 5,
  "Crossing": 5,
  "Short Passing": 3,
  "Long Passing": 3,
  "Free Kick": 2,
  "Awareness": 4,
  "Reactions": 5,
  "Ball Control": 3,
  "Dribbling": 0,
  "Composure": 7,
  "Heading": 2,
  "Marking": 5,
  "Tackling": 4,
  "Strength": 2,
  "Aggression": 2
}, {
  "Acceleration": 4,
  "Sprint Speed": 7,
  "Finishing": 4,
  "Long Shot": 5,
  "Shot Power": 3,
  "Positioning": 6,
  "Crossing": 5,
  "Short Passing": 3,
  "Long Passing": 4,
  "Free Kick": 3,
  "Awareness": 4,
  "Reactions": 6,
  "Ball Control": 3,
  "Dribbling": 0,
  "Composure": 7,
  "Heading": 3,
  "Marking": 5,
  "Tackling": 5,
  "Strength": 2,
  "Aggression": 3
}, {
  "Acceleration": 5,
  "Sprint Speed": 7,
  "Finishing": 4,
  "Long Shot": 6,
  "Shot Power": 4,
  "Positioning": 6,
  "Crossing": 6,
  "Short Passing": 4,
  "Long Passing": 4,
  "Free Kick": 4,
  "Awareness": 4,
  "Reactions": 6,
  "Ball Control": 3,
  "Dribbling": 0,
  "Composure": 8,
  "Heading": 3,
  "Marking": 6,
  "Tackling": 6,
  "Strength": 3,
  "Aggression": 4
}, {
  "Acceleration": 8,
  "Sprint Speed": 10,
  "Finishing": 4,
  "Long Shot": 9,
  "Shot Power": 4,
  "Positioning": 9,
  "Crossing": 9,
  "Short Passing": 7,
  "Long Passing": 7,
  "Free Kick": 4,
  "Awareness": 7,
  "Reactions": 9,
  "Ball Control": 6,
  "Dribbling": 3,
  "Composure": 8,
  "Heading": 3,
  "Marking": 9,
  "Tackling": 9,
  "Strength": 3,
  "Aggression": 4
}, {
  "Acceleration": 9,
  "Sprint Speed": 10,
  "Finishing": 5,
  "Long Shot": 10,
  "Shot Power": 4,
  "Positioning": 9,
  "Crossing": 10,
  "Short Passing": 8,
  "Long Passing": 7,
  "Free Kick": 5,
  "Awareness": 8,
  "Reactions": 9,
  "Ball Control": 6,
  "Dribbling": 3,
  "Composure": 10,
  "Heading": 4,
  "Marking": 10,
  "Tackling": 9,
  "Strength": 3,
  "Aggression": 4
}, {
  "Acceleration": 9,
  "Sprint Speed": 11,
  "Finishing": 6,
  "Long Shot": 10,
  "Shot Power": 4,
  "Positioning": 10,
  "Crossing": 11,
  "Short Passing": 8,
  "Long Passing": 7,
  "Free Kick": 5,
  "Awareness": 8,
  "Reactions": 10,
  "Ball Control": 6,
  "Dribbling": 3,
  "Composure": 10,
  "Heading": 4,
  "Marking": 10,
  "Tackling": 10,
  "Strength": 4,
  "Aggression": 4
}, {
  "Acceleration": 9,
  "Sprint Speed": 11,
  "Finishing": 6,
  "Long Shot": 10,
  "Shot Power": 4,
  "Positioning": 11,
  "Crossing": 12,
  "Short Passing": 8,
  "Long Passing": 8,
  "Free Kick": 6,
  "Awareness": 8,
  "Reactions": 11,
  "Ball Control": 7,
  "Dribbling": 3,
  "Composure": 11,
  "Heading": 4,
  "Marking": 11,
  "Tackling": 10,
  "Strength": 4,
  "Aggression": 5
}, {
  "Acceleration": 10,
  "Sprint Speed": 12,
  "Finishing": 7,
  "Long Shot": 11,
  "Shot Power": 4,
  "Positioning": 11,
  "Crossing": 13,
  "Short Passing": 9,
  "Long Passing": 8,
  "Free Kick": 6,
  "Awareness": 8,
  "Reactions": 11,
  "Ball Control": 7,
  "Dribbling": 3,
  "Composure": 11,
  "Heading": 5,
  "Marking": 11,
  "Tackling": 11,
  "Strength": 4,
  "Aggression": 5
}, {
  "Acceleration": 10,
  "Sprint Speed": 12,
  "Finishing": 7,
  "Long Shot": 11,
  "Shot Power": 5,
  "Positioning": 11,
  "Crossing": 14,
  "Short Passing": 9,
  "Long Passing": 8,
  "Free Kick": 6,
  "Awareness": 8,
  "Reactions": 12,
  "Ball Control": 7,
  "Dribbling": 3,
  "Composure": 12,
  "Heading": 5,
  "Marking": 12,
  "Tackling": 12,
  "Strength": 5,
  "Aggression": 5
}, {
  "Acceleration": 10,
  "Sprint Speed": 12,
  "Finishing": 8,
  "Long Shot": 11,
  "Shot Power": 6,
  "Positioning": 12,
  "Crossing": 15,
  "Short Passing": 9,
  "Long Passing": 9,
  "Free Kick": 7,
  "Awareness": 9,
  "Reactions": 12,
  "Ball Control": 8,
  "Dribbling": 3,
  "Composure": 12,
  "Heading": 6,
  "Marking": 12,
  "Tackling": 12,
  "Strength": 5,
  "Aggression": 5
}, {
  "Acceleration": 11,
  "Sprint Speed": 13,
  "Finishing": 8,
  "Long Shot": 12,
  "Shot Power": 6,
  "Positioning": 12,
  "Crossing": 16,
  "Short Passing": 10,
  "Long Passing": 9,
  "Free Kick": 7,
  "Awareness": 9,
  "Reactions": 13,
  "Ball Control": 8,
  "Dribbling": 3,
  "Composure": 12,
  "Heading": 7,
  "Marking": 13,
  "Tackling": 12,
  "Strength": 5,
  "Aggression": 6
}, {
  "Acceleration": 11,
  "Sprint Speed": 14,
  "Finishing": 9,
  "Long Shot": 12,
  "Shot Power": 6,
  "Positioning": 13,
  "Crossing": 17,
  "Short Passing": 10,
  "Long Passing": 9,
  "Free Kick": 7,
  "Awareness": 9,
  "Reactions": 14,
  "Ball Control": 8,
  "Dribbling": 3,
  "Composure": 13,
  "Heading": 7,
  "Marking": 13,
  "Tackling": 13,
  "Strength": 6,
  "Aggression": 7
}, {
  "Acceleration": 11,
  "Sprint Speed": 14,
  "Finishing": 9,
  "Long Shot": 12,
  "Shot Power": 7,
  "Positioning": 13,
  "Crossing": 18,
  "Short Passing": 11,
  "Long Passing": 10,
  "Free Kick": 8,
  "Awareness": 10,
  "Reactions": 14,
  "Ball Control": 9,
  "Dribbling": 3,
  "Composure": 13,
  "Heading": 8,
  "Marking": 14,
  "Tackling": 13,
  "Strength": 6,
  "Aggression": 7
}, {
  "Acceleration": 14,
  "Sprint Speed": 17,
  "Finishing": 9,
  "Long Shot": 15,
  "Shot Power": 7,
  "Positioning": 16,
  "Crossing": 21,
  "Short Passing": 14,
  "Long Passing": 13,
  "Free Kick": 8,
  "Awareness": 13,
  "Reactions": 17,
  "Ball Control": 12,
  "Dribbling": 6,
  "Composure": 13,
  "Heading": 8,
  "Marking": 17,
  "Tackling": 16,
  "Strength": 6,
  "Aggression": 7
}, {
  "Acceleration": 14,
  "Sprint Speed": 17,
  "Finishing": 10,
  "Long Shot": 15,
  "Shot Power": 7,
  "Positioning": 17,
  "Crossing": 22,
  "Short Passing": 14,
  "Long Passing": 13,
  "Free Kick": 8,
  "Awareness": 14,
  "Reactions": 17,
  "Ball Control": 13,
  "Dribbling": 7,
  "Composure": 13,
  "Heading": 9,
  "Marking": 18,
  "Tackling": 16,
  "Strength": 7,
  "Aggression": 8
}, {
  "Acceleration": 14,
  "Sprint Speed": 18,
  "Finishing": 11,
  "Long Shot": 15,
  "Shot Power": 8,
  "Positioning": 17,
  "Crossing": 23,
  "Short Passing": 15,
  "Long Passing": 14,
  "Free Kick": 8,
  "Awareness": 14,
  "Reactions": 18,
  "Ball Control": 13,
  "Dribbling": 7,
  "Composure": 13,
  "Heading": 9,
  "Marking": 18,
  "Tackling": 17,
  "Strength": 7,
  "Aggression": 8
}, {
  "Acceleration": 15,
  "Sprint Speed": 18,
  "Finishing": 11,
  "Long Shot": 16,
  "Shot Power": 8,
  "Positioning": 18,
  "Crossing": 24,
  "Short Passing": 15,
  "Long Passing": 14,
  "Free Kick": 8,
  "Awareness": 15,
  "Reactions": 18,
  "Ball Control": 14,
  "Dribbling": 8,
  "Composure": 14,
  "Heading": 9,
  "Marking": 19,
  "Tackling": 17,
  "Strength": 7,
  "Aggression": 8
}, {
  "Acceleration": 15,
  "Sprint Speed": 18,
  "Finishing": 12,
  "Long Shot": 16,
  "Shot Power": 8,
  "Positioning": 18,
  "Crossing": 25,
  "Short Passing": 15,
  "Long Passing": 14,
  "Free Kick": 9,
  "Awareness": 16,
  "Reactions": 19,
  "Ball Control": 14,
  "Dribbling": 8,
  "Composure": 14,
  "Heading": 10,
  "Marking": 20,
  "Tackling": 18,
  "Strength": 7,
  "Aggression": 8
}, {
  "Acceleration": 15,
  "Sprint Speed": 19,
  "Finishing": 12,
  "Long Shot": 16,
  "Shot Power": 9,
  "Positioning": 18,
  "Crossing": 26,
  "Short Passing": 16,
  "Long Passing": 15,
  "Free Kick": 10,
  "Awareness": 16,
  "Reactions": 19,
  "Ball Control": 14,
  "Dribbling": 9,
  "Composure": 14,
  "Heading": 11,
  "Marking": 20,
  "Tackling": 18,
  "Strength": 8,
  "Aggression": 8
}, {
  "Acceleration": 16,
  "Sprint Speed": 19,
  "Finishing": 13,
  "Long Shot": 17,
  "Shot Power": 9,
  "Positioning": 19,
  "Crossing": 27,
  "Short Passing": 16,
  "Long Passing": 15,
  "Free Kick": 10,
  "Awareness": 16,
  "Reactions": 20,
  "Ball Control": 15,
  "Dribbling": 10,
  "Composure": 14,
  "Heading": 11,
  "Marking": 21,
  "Tackling": 19,
  "Strength": 8,
  "Aggression": 8
}, {
  "Acceleration": 16,
  "Sprint Speed": 19,
  "Finishing": 13,
  "Long Shot": 17,
  "Shot Power": 10,
  "Positioning": 20,
  "Crossing": 28,
  "Short Passing": 17,
  "Long Passing": 16,
  "Free Kick": 10,
  "Awareness": 16,
  "Reactions": 20,
  "Ball Control": 16,
  "Dribbling": 10,
  "Composure": 15,
  "Heading": 12,
  "Marking": 21,
  "Tackling": 19,
  "Strength": 8,
  "Aggression": 9
}, {
  "Acceleration": 17,
  "Sprint Speed": 19,
  "Finishing": 14,
  "Long Shot": 17,
  "Shot Power": 10,
  "Positioning": 20,
  "Crossing": 29,
  "Short Passing": 17,
  "Long Passing": 16,
  "Free Kick": 11,
  "Awareness": 16,
  "Reactions": 20,
  "Ball Control": 16,
  "Dribbling": 11,
  "Composure": 15,
  "Heading": 13,
  "Marking": 22,
  "Tackling": 20,
  "Strength": 8,
  "Aggression": 10
}, {
  "Acceleration": 17,
  "Sprint Speed": 20,
  "Finishing": 14,
  "Long Shot": 18,
  "Shot Power": 10,
  "Positioning": 20,
  "Crossing": 30,
  "Short Passing": 18,
  "Long Passing": 16,
  "Free Kick": 11,
  "Awareness": 17,
  "Reactions": 21,
  "Ball Control": 16,
  "Dribbling": 12,
  "Composure": 15,
  "Heading": 13,
  "Marking": 22,
  "Tackling": 20,
  "Strength": 9,
  "Aggression": 10
}, {
  "Acceleration": 20,
  "Sprint Speed": 23,
  "Finishing": 14,
  "Long Shot": 21,
  "Shot Power": 10,
  "Positioning": 23,
  "Crossing": 33,
  "Short Passing": 21,
  "Long Passing": 19,
  "Free Kick": 11,
  "Awareness": 20,
  "Reactions": 24,
  "Ball Control": 19,
  "Dribbling": 15,
  "Composure": 15,
  "Heading": 13,
  "Marking": 25,
  "Tackling": 23,
  "Strength": 9,
  "Aggression": 10
}, {
  "Acceleration": 21,
  "Sprint Speed": 24,
  "Finishing": 15,
  "Long Shot": 21,
  "Shot Power": 11,
  "Positioning": 23,
  "Crossing": 34,
  "Short Passing": 22,
  "Long Passing": 20,
  "Free Kick": 12,
  "Awareness": 20,
  "Reactions": 24,
  "Ball Control": 19,
  "Dribbling": 15,
  "Composure": 16,
  "Heading": 13,
  "Marking": 25,
  "Tackling": 23,
  "Strength": 9,
  "Aggression": 11
}, {
  "Acceleration": 21,
  "Sprint Speed": 25,
  "Finishing": 15,
  "Long Shot": 22,
  "Shot Power": 11,
  "Positioning": 24,
  "Crossing": 35,
  "Short Passing": 22,
  "Long Passing": 20,
  "Free Kick": 12,
  "Awareness": 21,
  "Reactions": 24,
  "Ball Control": 20,
  "Dribbling": 16,
  "Composure": 16,
  "Heading": 14,
  "Marking": 25,
  "Tackling": 24,
  "Strength": 9,
  "Aggression": 11
}, {
  "Acceleration": 22,
  "Sprint Speed": 25,
  "Finishing": 16,
  "Long Shot": 22,
  "Shot Power": 11,
  "Positioning": 24,
  "Crossing": 36,
  "Short Passing": 22,
  "Long Passing": 20,
  "Free Kick": 12,
  "Awareness": 21,
  "Reactions": 25,
  "Ball Control": 20,
  "Dribbling": 17,
  "Composure": 16,
  "Heading": 14,
  "Marking": 26,
  "Tackling": 25,
  "Strength": 10,
  "Aggression": 12
}, {
  "Acceleration": 22,
  "Sprint Speed": 26,
  "Finishing": 16,
  "Long Shot": 23,
  "Shot Power": 11,
  "Positioning": 25,
  "Crossing": 37,
  "Short Passing": 22,
  "Long Passing": 21,
  "Free Kick": 13,
  "Awareness": 21,
  "Reactions": 25,
  "Ball Control": 21,
  "Dribbling": 17,
  "Composure": 17,
  "Heading": 15,
  "Marking": 26,
  "Tackling": 25,
  "Strength": 10,
  "Aggression": 12
}, {
  "Acceleration": 23,
  "Sprint Speed": 26,
  "Finishing": 17,
  "Long Shot": 24,
  "Shot Power": 11,
  "Positioning": 26,
  "Crossing": 38,
  "Short Passing": 23,
  "Long Passing": 21,
  "Free Kick": 13,
  "Awareness": 21,
  "Reactions": 26,
  "Ball Control": 21,
  "Dribbling": 18,
  "Composure": 17,
  "Heading": 15,
  "Marking": 27,
  "Tackling": 26,
  "Strength": 11,
  "Aggression": 12
}, {
  "Acceleration": 23,
  "Sprint Speed": 26,
  "Finishing": 18,
  "Long Shot": 25,
  "Shot Power": 12,
  "Positioning": 26,
  "Crossing": 39,
  "Short Passing": 23,
  "Long Passing": 22,
  "Free Kick": 14,
  "Awareness": 22,
  "Reactions": 26,
  "Ball Control": 22,
  "Dribbling": 18,
  "Composure": 17,
  "Heading": 16,
  "Marking": 27,
  "Tackling": 27,
  "Strength": 11,
  "Aggression": 12
}, {
  "Acceleration": 24,
  "Sprint Speed": 27,
  "Finishing": 18,
  "Long Shot": 26,
  "Shot Power": 12,
  "Positioning": 26,
  "Crossing": 40,
  "Short Passing": 23,
  "Long Passing": 22,
  "Free Kick": 14,
  "Awareness": 22,
  "Reactions": 27,
  "Ball Control": 22,
  "Dribbling": 18,
  "Composure": 18,
  "Heading": 17,
  "Marking": 27,
  "Tackling": 27,
  "Strength": 11,
  "Aggression": 14
}, {
  "Acceleration": 24,
  "Sprint Speed": 27,
  "Finishing": 18,
  "Long Shot": 26,
  "Shot Power": 13,
  "Positioning": 27,
  "Crossing": 41,
  "Short Passing": 23,
  "Long Passing": 22,
  "Free Kick": 14,
  "Awareness": 24,
  "Reactions": 27,
  "Ball Control": 23,
  "Dribbling": 19,
  "Composure": 18,
  "Heading": 17,
  "Marking": 28,
  "Tackling": 28,
  "Strength": 12,
  "Aggression": 15
}, {
  "Acceleration": 24,
  "Sprint Speed": 28,
  "Finishing": 19,
  "Long Shot": 26,
  "Shot Power": 13,
  "Positioning": 27,
  "Crossing": 42,
  "Short Passing": 24,
  "Long Passing": 23,
  "Free Kick": 15,
  "Awareness": 24,
  "Reactions": 28,
  "Ball Control": 23,
  "Dribbling": 19,
  "Composure": 18,
  "Heading": 18,
  "Marking": 28,
  "Tackling": 29,
  "Strength": 12,
  "Aggression": 15
}, {
  "Acceleration": 27,
  "Sprint Speed": 30,
  "Finishing": 19,
  "Long Shot": 27,
  "Shot Power": 23,
  "Positioning": 27,
  "Crossing": 43,
  "Short Passing": 24,
  "Long Passing": 23,
  "Free Kick": 15,
  "Awareness": 29,
  "Reactions": 28,
  "Ball Control": 26,
  "Dribbling": 19,
  "Composure": 19,
  "Heading": 18,
  "Marking": 29,
  "Tackling": 32,
  "Strength": 12,
  "Aggression": 15
}, {
  "Acceleration": 32,
  "Sprint Speed": 33,
  "Finishing": 24,
  "Long Shot": 27,
  "Shot Power": 23,
  "Positioning": 33,
  "Crossing": 46,
  "Short Passing": 27,
  "Long Passing": 23,
  "Free Kick": 15,
  "Awareness": 29,
  "Reactions": 31,
  "Ball Control": 28,
  "Dribbling": 24,
  "Composure": 34,
  "Heading": 22,
  "Marking": 29,
  "Tackling": 35,
  "Strength": 12,
  "Aggression": 20
}, {
  "Acceleration": 35,
  "Sprint Speed": 36,
  "Finishing": 24,
  "Long Shot": 32,
  "Shot Power": 23,
  "Positioning": 36,
  "Crossing": 49,
  "Short Passing": 30,
  "Long Passing": 28,
  "Free Kick": 15,
  "Awareness": 34,
  "Reactions": 33,
  "Ball Control": 31,
  "Dribbling": 29,
  "Composure": 34,
  "Heading": 22,
  "Marking": 39,
  "Tackling": 39,
  "Strength": 12,
  "Aggression": 20
}, {
  "Acceleration": 39,
  "Sprint Speed": 38,
  "Finishing": 29,
  "Long Shot": 32,
  "Shot Power": 23,
  "Positioning": 42,
  "Crossing": 54,
  "Short Passing": 33,
  "Long Passing": 32,
  "Free Kick": 15,
  "Awareness": 34,
  "Reactions": 38,
  "Ball Control": 34,
  "Dribbling": 32,
  "Composure": 34,
  "Heading": 29,
  "Marking": 39,
  "Tackling": 44,
  "Strength": 15,
  "Aggression": 20
}, {
  "Acceleration": 42,
  "Sprint Speed": 41,
  "Finishing": 33,
  "Long Shot": 32,
  "Shot Power": 23,
  "Positioning": 45,
  "Crossing": 58,
  "Short Passing": 36,
  "Long Passing": 35,
  "Free Kick": 15,
  "Awareness": 34,
  "Reactions": 43,
  "Ball Control": 36,
  "Dribbling": 34,
  "Composure": 34,
  "Heading": 29,
  "Marking": 39,
  "Tackling": 47,
  "Strength": 17,
  "Aggression": 25
}, {
  "Acceleration": 45,
  "Sprint Speed": 46,
  "Finishing": 36,
  "Long Shot": 32,
  "Shot Power": 23,
  "Positioning": 48,
  "Crossing": 61,
  "Short Passing": 40,
  "Long Passing": 37,
  "Free Kick": 15,
  "Awareness": 44,
  "Reactions": 47,
  "Ball Control": 39,
  "Dribbling": 37,
  "Composure": 34,
  "Heading": 29,
  "Marking": 44,
  "Tackling": 49,
  "Strength": 17,
  "Aggression": 25
}, {
  "Acceleration": 50,
  "Sprint Speed": 49,
  "Finishing": 40,
  "Long Shot": 32,
  "Shot Power": 23,
  "Positioning": 52,
  "Crossing": 64,
  "Short Passing": 42,
  "Long Passing": 40,
  "Free Kick": 15,
  "Awareness": 44,
  "Reactions": 50,
  "Ball Control": 42,
  "Dribbling": 42,
  "Composure": 34,
  "Heading": 36,
  "Marking": 44,
  "Tackling": 51,
  "Strength": 20,
  "Aggression": 25
}, {
  "Acceleration": 53,
  "Sprint Speed": 51,
  "Finishing": 43,
  "Long Shot": 42,
  "Shot Power": 23,
  "Positioning": 57,
  "Crossing": 67,
  "Short Passing": 47,
  "Long Passing": 42,
  "Free Kick": 15,
  "Awareness": 44,
  "Reactions": 52,
  "Ball Control": 44,
  "Dribbling": 47,
  "Composure": 34,
  "Heading": 36,
  "Marking": 49,
  "Tackling": 53,
  "Strength": 20,
  "Aggression": 25
}, {
  "Acceleration": 57,
  "Sprint Speed": 56,
  "Finishing": 43,
  "Long Shot": 42,
  "Shot Power": 28,
  "Positioning": 62,
  "Crossing": 67,
  "Short Passing": 51,
  "Long Passing": 45,
  "Free Kick": 21,
  "Awareness": 44,
  "Reactions": 56,
  "Ball Control": 47,
  "Dribbling": 51,
  "Composure": 34,
  "Heading": 36,
  "Marking": 49,
  "Tackling": 58,
  "Strength": 23,
  "Aggression": 25
}, {
  "Acceleration": 60,
  "Sprint Speed": 59,
  "Finishing": 48,
  "Long Shot": 42,
  "Shot Power": 28,
  "Positioning": 65,
  "Crossing": 67,
  "Short Passing": 53,
  "Long Passing": 48,
  "Free Kick": 21,
  "Awareness": 44,
  "Reactions": 59,
  "Ball Control": 50,
  "Dribbling": 54,
  "Composure": 34,
  "Heading": 43,
  "Marking": 49,
  "Tackling": 60,
  "Strength": 26,
  "Aggression": 25
}, {
  "Acceleration": 65,
  "Sprint Speed": 64,
  "Finishing": 48,
  "Long Shot": 42,
  "Shot Power": 28,
  "Positioning": 68,
  "Crossing": 67,
  "Short Passing": 58,
  "Long Passing": 53,
  "Free Kick": 26,
  "Awareness": 54,
  "Reactions": 62,
  "Ball Control": 55,
  "Dribbling": 59,
  "Composure": 34,
  "Heading": 43,
  "Marking": 49,
  "Tackling": 63,
  "Strength": 31,
  "Aggression": 25
}]